/*
 * Wodby API Client
 *
 * Wodby Developer Documentation https://wodby.com/docs/1.0/docs/dev
 *
 * API version: 3.0.19
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */

package client

type GitRepo struct {

	Id string `json:"id"`

	Title string `json:"title"`

	Url string `json:"url,omitempty"`

	OrgId string `json:"org_id"`

	Status string `json:"status"`

	Created int32 `json:"created"`

	Updated int32 `json:"updated"`
}
