/*
 * Wodby API Client
 *
 * Wodby Developer Documentation https://wodby.com/docs/dev
 *
 * API version: 3.0.12
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */

package client

type InstanceType string

// List of InstanceType
const (
	DEV InstanceType = "dev"
	STAGE InstanceType = "stage"
	PROD InstanceType = "prod"
)
