/*
Wodby 2 Public API

Public REST API for customer SDKs and code integrations. GraphQL remains internal for the dashboard. This contract is the versioned public surface. 

API version: 1.0.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package client

import (
	"encoding/json"
	"time"
	"bytes"
	"fmt"
)

// checks if the BackupPreset type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &BackupPreset{}

// BackupPreset struct for BackupPreset
type BackupPreset struct {
	Id int32 `json:"id"`
	AppInstanceId NullableInt32 `json:"appInstanceId,omitempty"`
	AppServiceId NullableInt32 `json:"appServiceId,omitempty"`
	DatabaseId NullableInt32 `json:"databaseId,omitempty"`
	DatabaseDbId NullableInt32 `json:"databaseDbId,omitempty"`
	OrgId NullableInt32 `json:"orgId,omitempty"`
	EnvId NullableInt32 `json:"envId,omitempty"`
	BackupName NullableString `json:"backupName,omitempty"`
	IntegrationId int32 `json:"integrationId"`
	Bucket string `json:"bucket"`
	StorageClass NullableString `json:"storageClass,omitempty"`
	Options []BackupOption `json:"options"`
	Override bool `json:"override"`
	Auto bool `json:"auto"`
	Disabled bool `json:"disabled"`
	Crontab NullableString `json:"crontab,omitempty"`
	TimeWindow *AutomationTimeWindow `json:"timeWindow,omitempty"`
	Duration NullableInt32 `json:"duration,omitempty"`
	NextRunAt NullableTime `json:"nextRunAt,omitempty"`
	CreatedAt time.Time `json:"createdAt"`
	UpdatedAt time.Time `json:"updatedAt"`
}

type _BackupPreset BackupPreset

// NewBackupPreset instantiates a new BackupPreset object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewBackupPreset(id int32, integrationId int32, bucket string, options []BackupOption, override bool, auto bool, disabled bool, createdAt time.Time, updatedAt time.Time) *BackupPreset {
	this := BackupPreset{}
	this.Id = id
	this.IntegrationId = integrationId
	this.Bucket = bucket
	this.Options = options
	this.Override = override
	this.Auto = auto
	this.Disabled = disabled
	this.CreatedAt = createdAt
	this.UpdatedAt = updatedAt
	return &this
}

// NewBackupPresetWithDefaults instantiates a new BackupPreset object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewBackupPresetWithDefaults() *BackupPreset {
	this := BackupPreset{}
	return &this
}

// GetId returns the Id field value
func (o *BackupPreset) GetId() int32 {
	if o == nil {
		var ret int32
		return ret
	}

	return o.Id
}

// GetIdOk returns a tuple with the Id field value
// and a boolean to check if the value has been set.
func (o *BackupPreset) GetIdOk() (*int32, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Id, true
}

// SetId sets field value
func (o *BackupPreset) SetId(v int32) {
	o.Id = v
}

// GetAppInstanceId returns the AppInstanceId field value if set, zero value otherwise (both if not set or set to explicit null).
func (o *BackupPreset) GetAppInstanceId() int32 {
	if o == nil || IsNil(o.AppInstanceId.Get()) {
		var ret int32
		return ret
	}
	return *o.AppInstanceId.Get()
}

// GetAppInstanceIdOk returns a tuple with the AppInstanceId field value if set, nil otherwise
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *BackupPreset) GetAppInstanceIdOk() (*int32, bool) {
	if o == nil {
		return nil, false
	}
	return o.AppInstanceId.Get(), o.AppInstanceId.IsSet()
}

// HasAppInstanceId returns a boolean if a field has been set.
func (o *BackupPreset) HasAppInstanceId() bool {
	if o != nil && o.AppInstanceId.IsSet() {
		return true
	}

	return false
}

// SetAppInstanceId gets a reference to the given NullableInt32 and assigns it to the AppInstanceId field.
func (o *BackupPreset) SetAppInstanceId(v int32) {
	o.AppInstanceId.Set(&v)
}
// SetAppInstanceIdNil sets the value for AppInstanceId to be an explicit nil
func (o *BackupPreset) SetAppInstanceIdNil() {
	o.AppInstanceId.Set(nil)
}

// UnsetAppInstanceId ensures that no value is present for AppInstanceId, not even an explicit nil
func (o *BackupPreset) UnsetAppInstanceId() {
	o.AppInstanceId.Unset()
}

// GetAppServiceId returns the AppServiceId field value if set, zero value otherwise (both if not set or set to explicit null).
func (o *BackupPreset) GetAppServiceId() int32 {
	if o == nil || IsNil(o.AppServiceId.Get()) {
		var ret int32
		return ret
	}
	return *o.AppServiceId.Get()
}

// GetAppServiceIdOk returns a tuple with the AppServiceId field value if set, nil otherwise
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *BackupPreset) GetAppServiceIdOk() (*int32, bool) {
	if o == nil {
		return nil, false
	}
	return o.AppServiceId.Get(), o.AppServiceId.IsSet()
}

// HasAppServiceId returns a boolean if a field has been set.
func (o *BackupPreset) HasAppServiceId() bool {
	if o != nil && o.AppServiceId.IsSet() {
		return true
	}

	return false
}

// SetAppServiceId gets a reference to the given NullableInt32 and assigns it to the AppServiceId field.
func (o *BackupPreset) SetAppServiceId(v int32) {
	o.AppServiceId.Set(&v)
}
// SetAppServiceIdNil sets the value for AppServiceId to be an explicit nil
func (o *BackupPreset) SetAppServiceIdNil() {
	o.AppServiceId.Set(nil)
}

// UnsetAppServiceId ensures that no value is present for AppServiceId, not even an explicit nil
func (o *BackupPreset) UnsetAppServiceId() {
	o.AppServiceId.Unset()
}

// GetDatabaseId returns the DatabaseId field value if set, zero value otherwise (both if not set or set to explicit null).
func (o *BackupPreset) GetDatabaseId() int32 {
	if o == nil || IsNil(o.DatabaseId.Get()) {
		var ret int32
		return ret
	}
	return *o.DatabaseId.Get()
}

// GetDatabaseIdOk returns a tuple with the DatabaseId field value if set, nil otherwise
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *BackupPreset) GetDatabaseIdOk() (*int32, bool) {
	if o == nil {
		return nil, false
	}
	return o.DatabaseId.Get(), o.DatabaseId.IsSet()
}

// HasDatabaseId returns a boolean if a field has been set.
func (o *BackupPreset) HasDatabaseId() bool {
	if o != nil && o.DatabaseId.IsSet() {
		return true
	}

	return false
}

// SetDatabaseId gets a reference to the given NullableInt32 and assigns it to the DatabaseId field.
func (o *BackupPreset) SetDatabaseId(v int32) {
	o.DatabaseId.Set(&v)
}
// SetDatabaseIdNil sets the value for DatabaseId to be an explicit nil
func (o *BackupPreset) SetDatabaseIdNil() {
	o.DatabaseId.Set(nil)
}

// UnsetDatabaseId ensures that no value is present for DatabaseId, not even an explicit nil
func (o *BackupPreset) UnsetDatabaseId() {
	o.DatabaseId.Unset()
}

// GetDatabaseDbId returns the DatabaseDbId field value if set, zero value otherwise (both if not set or set to explicit null).
func (o *BackupPreset) GetDatabaseDbId() int32 {
	if o == nil || IsNil(o.DatabaseDbId.Get()) {
		var ret int32
		return ret
	}
	return *o.DatabaseDbId.Get()
}

// GetDatabaseDbIdOk returns a tuple with the DatabaseDbId field value if set, nil otherwise
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *BackupPreset) GetDatabaseDbIdOk() (*int32, bool) {
	if o == nil {
		return nil, false
	}
	return o.DatabaseDbId.Get(), o.DatabaseDbId.IsSet()
}

// HasDatabaseDbId returns a boolean if a field has been set.
func (o *BackupPreset) HasDatabaseDbId() bool {
	if o != nil && o.DatabaseDbId.IsSet() {
		return true
	}

	return false
}

// SetDatabaseDbId gets a reference to the given NullableInt32 and assigns it to the DatabaseDbId field.
func (o *BackupPreset) SetDatabaseDbId(v int32) {
	o.DatabaseDbId.Set(&v)
}
// SetDatabaseDbIdNil sets the value for DatabaseDbId to be an explicit nil
func (o *BackupPreset) SetDatabaseDbIdNil() {
	o.DatabaseDbId.Set(nil)
}

// UnsetDatabaseDbId ensures that no value is present for DatabaseDbId, not even an explicit nil
func (o *BackupPreset) UnsetDatabaseDbId() {
	o.DatabaseDbId.Unset()
}

// GetOrgId returns the OrgId field value if set, zero value otherwise (both if not set or set to explicit null).
func (o *BackupPreset) GetOrgId() int32 {
	if o == nil || IsNil(o.OrgId.Get()) {
		var ret int32
		return ret
	}
	return *o.OrgId.Get()
}

// GetOrgIdOk returns a tuple with the OrgId field value if set, nil otherwise
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *BackupPreset) GetOrgIdOk() (*int32, bool) {
	if o == nil {
		return nil, false
	}
	return o.OrgId.Get(), o.OrgId.IsSet()
}

// HasOrgId returns a boolean if a field has been set.
func (o *BackupPreset) HasOrgId() bool {
	if o != nil && o.OrgId.IsSet() {
		return true
	}

	return false
}

// SetOrgId gets a reference to the given NullableInt32 and assigns it to the OrgId field.
func (o *BackupPreset) SetOrgId(v int32) {
	o.OrgId.Set(&v)
}
// SetOrgIdNil sets the value for OrgId to be an explicit nil
func (o *BackupPreset) SetOrgIdNil() {
	o.OrgId.Set(nil)
}

// UnsetOrgId ensures that no value is present for OrgId, not even an explicit nil
func (o *BackupPreset) UnsetOrgId() {
	o.OrgId.Unset()
}

// GetEnvId returns the EnvId field value if set, zero value otherwise (both if not set or set to explicit null).
func (o *BackupPreset) GetEnvId() int32 {
	if o == nil || IsNil(o.EnvId.Get()) {
		var ret int32
		return ret
	}
	return *o.EnvId.Get()
}

// GetEnvIdOk returns a tuple with the EnvId field value if set, nil otherwise
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *BackupPreset) GetEnvIdOk() (*int32, bool) {
	if o == nil {
		return nil, false
	}
	return o.EnvId.Get(), o.EnvId.IsSet()
}

// HasEnvId returns a boolean if a field has been set.
func (o *BackupPreset) HasEnvId() bool {
	if o != nil && o.EnvId.IsSet() {
		return true
	}

	return false
}

// SetEnvId gets a reference to the given NullableInt32 and assigns it to the EnvId field.
func (o *BackupPreset) SetEnvId(v int32) {
	o.EnvId.Set(&v)
}
// SetEnvIdNil sets the value for EnvId to be an explicit nil
func (o *BackupPreset) SetEnvIdNil() {
	o.EnvId.Set(nil)
}

// UnsetEnvId ensures that no value is present for EnvId, not even an explicit nil
func (o *BackupPreset) UnsetEnvId() {
	o.EnvId.Unset()
}

// GetBackupName returns the BackupName field value if set, zero value otherwise (both if not set or set to explicit null).
func (o *BackupPreset) GetBackupName() string {
	if o == nil || IsNil(o.BackupName.Get()) {
		var ret string
		return ret
	}
	return *o.BackupName.Get()
}

// GetBackupNameOk returns a tuple with the BackupName field value if set, nil otherwise
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *BackupPreset) GetBackupNameOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return o.BackupName.Get(), o.BackupName.IsSet()
}

// HasBackupName returns a boolean if a field has been set.
func (o *BackupPreset) HasBackupName() bool {
	if o != nil && o.BackupName.IsSet() {
		return true
	}

	return false
}

// SetBackupName gets a reference to the given NullableString and assigns it to the BackupName field.
func (o *BackupPreset) SetBackupName(v string) {
	o.BackupName.Set(&v)
}
// SetBackupNameNil sets the value for BackupName to be an explicit nil
func (o *BackupPreset) SetBackupNameNil() {
	o.BackupName.Set(nil)
}

// UnsetBackupName ensures that no value is present for BackupName, not even an explicit nil
func (o *BackupPreset) UnsetBackupName() {
	o.BackupName.Unset()
}

// GetIntegrationId returns the IntegrationId field value
func (o *BackupPreset) GetIntegrationId() int32 {
	if o == nil {
		var ret int32
		return ret
	}

	return o.IntegrationId
}

// GetIntegrationIdOk returns a tuple with the IntegrationId field value
// and a boolean to check if the value has been set.
func (o *BackupPreset) GetIntegrationIdOk() (*int32, bool) {
	if o == nil {
		return nil, false
	}
	return &o.IntegrationId, true
}

// SetIntegrationId sets field value
func (o *BackupPreset) SetIntegrationId(v int32) {
	o.IntegrationId = v
}

// GetBucket returns the Bucket field value
func (o *BackupPreset) GetBucket() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Bucket
}

// GetBucketOk returns a tuple with the Bucket field value
// and a boolean to check if the value has been set.
func (o *BackupPreset) GetBucketOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Bucket, true
}

// SetBucket sets field value
func (o *BackupPreset) SetBucket(v string) {
	o.Bucket = v
}

// GetStorageClass returns the StorageClass field value if set, zero value otherwise (both if not set or set to explicit null).
func (o *BackupPreset) GetStorageClass() string {
	if o == nil || IsNil(o.StorageClass.Get()) {
		var ret string
		return ret
	}
	return *o.StorageClass.Get()
}

// GetStorageClassOk returns a tuple with the StorageClass field value if set, nil otherwise
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *BackupPreset) GetStorageClassOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return o.StorageClass.Get(), o.StorageClass.IsSet()
}

// HasStorageClass returns a boolean if a field has been set.
func (o *BackupPreset) HasStorageClass() bool {
	if o != nil && o.StorageClass.IsSet() {
		return true
	}

	return false
}

// SetStorageClass gets a reference to the given NullableString and assigns it to the StorageClass field.
func (o *BackupPreset) SetStorageClass(v string) {
	o.StorageClass.Set(&v)
}
// SetStorageClassNil sets the value for StorageClass to be an explicit nil
func (o *BackupPreset) SetStorageClassNil() {
	o.StorageClass.Set(nil)
}

// UnsetStorageClass ensures that no value is present for StorageClass, not even an explicit nil
func (o *BackupPreset) UnsetStorageClass() {
	o.StorageClass.Unset()
}

// GetOptions returns the Options field value
func (o *BackupPreset) GetOptions() []BackupOption {
	if o == nil {
		var ret []BackupOption
		return ret
	}

	return o.Options
}

// GetOptionsOk returns a tuple with the Options field value
// and a boolean to check if the value has been set.
func (o *BackupPreset) GetOptionsOk() ([]BackupOption, bool) {
	if o == nil {
		return nil, false
	}
	return o.Options, true
}

// SetOptions sets field value
func (o *BackupPreset) SetOptions(v []BackupOption) {
	o.Options = v
}

// GetOverride returns the Override field value
func (o *BackupPreset) GetOverride() bool {
	if o == nil {
		var ret bool
		return ret
	}

	return o.Override
}

// GetOverrideOk returns a tuple with the Override field value
// and a boolean to check if the value has been set.
func (o *BackupPreset) GetOverrideOk() (*bool, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Override, true
}

// SetOverride sets field value
func (o *BackupPreset) SetOverride(v bool) {
	o.Override = v
}

// GetAuto returns the Auto field value
func (o *BackupPreset) GetAuto() bool {
	if o == nil {
		var ret bool
		return ret
	}

	return o.Auto
}

// GetAutoOk returns a tuple with the Auto field value
// and a boolean to check if the value has been set.
func (o *BackupPreset) GetAutoOk() (*bool, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Auto, true
}

// SetAuto sets field value
func (o *BackupPreset) SetAuto(v bool) {
	o.Auto = v
}

// GetDisabled returns the Disabled field value
func (o *BackupPreset) GetDisabled() bool {
	if o == nil {
		var ret bool
		return ret
	}

	return o.Disabled
}

// GetDisabledOk returns a tuple with the Disabled field value
// and a boolean to check if the value has been set.
func (o *BackupPreset) GetDisabledOk() (*bool, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Disabled, true
}

// SetDisabled sets field value
func (o *BackupPreset) SetDisabled(v bool) {
	o.Disabled = v
}

// GetCrontab returns the Crontab field value if set, zero value otherwise (both if not set or set to explicit null).
func (o *BackupPreset) GetCrontab() string {
	if o == nil || IsNil(o.Crontab.Get()) {
		var ret string
		return ret
	}
	return *o.Crontab.Get()
}

// GetCrontabOk returns a tuple with the Crontab field value if set, nil otherwise
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *BackupPreset) GetCrontabOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return o.Crontab.Get(), o.Crontab.IsSet()
}

// HasCrontab returns a boolean if a field has been set.
func (o *BackupPreset) HasCrontab() bool {
	if o != nil && o.Crontab.IsSet() {
		return true
	}

	return false
}

// SetCrontab gets a reference to the given NullableString and assigns it to the Crontab field.
func (o *BackupPreset) SetCrontab(v string) {
	o.Crontab.Set(&v)
}
// SetCrontabNil sets the value for Crontab to be an explicit nil
func (o *BackupPreset) SetCrontabNil() {
	o.Crontab.Set(nil)
}

// UnsetCrontab ensures that no value is present for Crontab, not even an explicit nil
func (o *BackupPreset) UnsetCrontab() {
	o.Crontab.Unset()
}

// GetTimeWindow returns the TimeWindow field value if set, zero value otherwise.
func (o *BackupPreset) GetTimeWindow() AutomationTimeWindow {
	if o == nil || IsNil(o.TimeWindow) {
		var ret AutomationTimeWindow
		return ret
	}
	return *o.TimeWindow
}

// GetTimeWindowOk returns a tuple with the TimeWindow field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *BackupPreset) GetTimeWindowOk() (*AutomationTimeWindow, bool) {
	if o == nil || IsNil(o.TimeWindow) {
		return nil, false
	}
	return o.TimeWindow, true
}

// HasTimeWindow returns a boolean if a field has been set.
func (o *BackupPreset) HasTimeWindow() bool {
	if o != nil && !IsNil(o.TimeWindow) {
		return true
	}

	return false
}

// SetTimeWindow gets a reference to the given AutomationTimeWindow and assigns it to the TimeWindow field.
func (o *BackupPreset) SetTimeWindow(v AutomationTimeWindow) {
	o.TimeWindow = &v
}

// GetDuration returns the Duration field value if set, zero value otherwise (both if not set or set to explicit null).
func (o *BackupPreset) GetDuration() int32 {
	if o == nil || IsNil(o.Duration.Get()) {
		var ret int32
		return ret
	}
	return *o.Duration.Get()
}

// GetDurationOk returns a tuple with the Duration field value if set, nil otherwise
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *BackupPreset) GetDurationOk() (*int32, bool) {
	if o == nil {
		return nil, false
	}
	return o.Duration.Get(), o.Duration.IsSet()
}

// HasDuration returns a boolean if a field has been set.
func (o *BackupPreset) HasDuration() bool {
	if o != nil && o.Duration.IsSet() {
		return true
	}

	return false
}

// SetDuration gets a reference to the given NullableInt32 and assigns it to the Duration field.
func (o *BackupPreset) SetDuration(v int32) {
	o.Duration.Set(&v)
}
// SetDurationNil sets the value for Duration to be an explicit nil
func (o *BackupPreset) SetDurationNil() {
	o.Duration.Set(nil)
}

// UnsetDuration ensures that no value is present for Duration, not even an explicit nil
func (o *BackupPreset) UnsetDuration() {
	o.Duration.Unset()
}

// GetNextRunAt returns the NextRunAt field value if set, zero value otherwise (both if not set or set to explicit null).
func (o *BackupPreset) GetNextRunAt() time.Time {
	if o == nil || IsNil(o.NextRunAt.Get()) {
		var ret time.Time
		return ret
	}
	return *o.NextRunAt.Get()
}

// GetNextRunAtOk returns a tuple with the NextRunAt field value if set, nil otherwise
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *BackupPreset) GetNextRunAtOk() (*time.Time, bool) {
	if o == nil {
		return nil, false
	}
	return o.NextRunAt.Get(), o.NextRunAt.IsSet()
}

// HasNextRunAt returns a boolean if a field has been set.
func (o *BackupPreset) HasNextRunAt() bool {
	if o != nil && o.NextRunAt.IsSet() {
		return true
	}

	return false
}

// SetNextRunAt gets a reference to the given NullableTime and assigns it to the NextRunAt field.
func (o *BackupPreset) SetNextRunAt(v time.Time) {
	o.NextRunAt.Set(&v)
}
// SetNextRunAtNil sets the value for NextRunAt to be an explicit nil
func (o *BackupPreset) SetNextRunAtNil() {
	o.NextRunAt.Set(nil)
}

// UnsetNextRunAt ensures that no value is present for NextRunAt, not even an explicit nil
func (o *BackupPreset) UnsetNextRunAt() {
	o.NextRunAt.Unset()
}

// GetCreatedAt returns the CreatedAt field value
func (o *BackupPreset) GetCreatedAt() time.Time {
	if o == nil {
		var ret time.Time
		return ret
	}

	return o.CreatedAt
}

// GetCreatedAtOk returns a tuple with the CreatedAt field value
// and a boolean to check if the value has been set.
func (o *BackupPreset) GetCreatedAtOk() (*time.Time, bool) {
	if o == nil {
		return nil, false
	}
	return &o.CreatedAt, true
}

// SetCreatedAt sets field value
func (o *BackupPreset) SetCreatedAt(v time.Time) {
	o.CreatedAt = v
}

// GetUpdatedAt returns the UpdatedAt field value
func (o *BackupPreset) GetUpdatedAt() time.Time {
	if o == nil {
		var ret time.Time
		return ret
	}

	return o.UpdatedAt
}

// GetUpdatedAtOk returns a tuple with the UpdatedAt field value
// and a boolean to check if the value has been set.
func (o *BackupPreset) GetUpdatedAtOk() (*time.Time, bool) {
	if o == nil {
		return nil, false
	}
	return &o.UpdatedAt, true
}

// SetUpdatedAt sets field value
func (o *BackupPreset) SetUpdatedAt(v time.Time) {
	o.UpdatedAt = v
}

func (o BackupPreset) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o BackupPreset) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["id"] = o.Id
	if o.AppInstanceId.IsSet() {
		toSerialize["appInstanceId"] = o.AppInstanceId.Get()
	}
	if o.AppServiceId.IsSet() {
		toSerialize["appServiceId"] = o.AppServiceId.Get()
	}
	if o.DatabaseId.IsSet() {
		toSerialize["databaseId"] = o.DatabaseId.Get()
	}
	if o.DatabaseDbId.IsSet() {
		toSerialize["databaseDbId"] = o.DatabaseDbId.Get()
	}
	if o.OrgId.IsSet() {
		toSerialize["orgId"] = o.OrgId.Get()
	}
	if o.EnvId.IsSet() {
		toSerialize["envId"] = o.EnvId.Get()
	}
	if o.BackupName.IsSet() {
		toSerialize["backupName"] = o.BackupName.Get()
	}
	toSerialize["integrationId"] = o.IntegrationId
	toSerialize["bucket"] = o.Bucket
	if o.StorageClass.IsSet() {
		toSerialize["storageClass"] = o.StorageClass.Get()
	}
	toSerialize["options"] = o.Options
	toSerialize["override"] = o.Override
	toSerialize["auto"] = o.Auto
	toSerialize["disabled"] = o.Disabled
	if o.Crontab.IsSet() {
		toSerialize["crontab"] = o.Crontab.Get()
	}
	if !IsNil(o.TimeWindow) {
		toSerialize["timeWindow"] = o.TimeWindow
	}
	if o.Duration.IsSet() {
		toSerialize["duration"] = o.Duration.Get()
	}
	if o.NextRunAt.IsSet() {
		toSerialize["nextRunAt"] = o.NextRunAt.Get()
	}
	toSerialize["createdAt"] = o.CreatedAt
	toSerialize["updatedAt"] = o.UpdatedAt
	return toSerialize, nil
}

func (o *BackupPreset) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"id",
		"integrationId",
		"bucket",
		"options",
		"override",
		"auto",
		"disabled",
		"createdAt",
		"updatedAt",
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err;
	}

	for _, requiredProperty := range(requiredProperties) {
		if _, exists := allProperties[requiredProperty]; !exists {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varBackupPreset := _BackupPreset{}

	decoder := json.NewDecoder(bytes.NewReader(data))
	decoder.DisallowUnknownFields()
	err = decoder.Decode(&varBackupPreset)

	if err != nil {
		return err
	}

	*o = BackupPreset(varBackupPreset)

	return err
}

type NullableBackupPreset struct {
	value *BackupPreset
	isSet bool
}

func (v NullableBackupPreset) Get() *BackupPreset {
	return v.value
}

func (v *NullableBackupPreset) Set(val *BackupPreset) {
	v.value = val
	v.isSet = true
}

func (v NullableBackupPreset) IsSet() bool {
	return v.isSet
}

func (v *NullableBackupPreset) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableBackupPreset(val *BackupPreset) *NullableBackupPreset {
	return &NullableBackupPreset{value: val, isSet: true}
}

func (v NullableBackupPreset) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableBackupPreset) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


