/*
Wodby Public API

Public REST API for customer SDKs and code integrations. GraphQL remains internal for the dashboard. This contract is the versioned public surface. 

API version: 1.0.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package client

import (
	"encoding/json"
	"time"
	"bytes"
	"fmt"
)

// checks if the Backup type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &Backup{}

// Backup struct for Backup
type Backup struct {
	Id int32 `json:"id"`
	Name string `json:"name"`
	Status string `json:"status"`
	AppInstanceId NullableInt32 `json:"appInstanceId,omitempty"`
	AppServiceId NullableInt32 `json:"appServiceId,omitempty"`
	DatabaseId NullableInt32 `json:"databaseId,omitempty"`
	DatabaseDbId NullableInt32 `json:"databaseDbId,omitempty"`
	CreatedAt time.Time `json:"createdAt"`
	UpdatedAt time.Time `json:"updatedAt"`
}

type _Backup Backup

// NewBackup instantiates a new Backup object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewBackup(id int32, name string, status string, createdAt time.Time, updatedAt time.Time) *Backup {
	this := Backup{}
	this.Id = id
	this.Name = name
	this.Status = status
	this.CreatedAt = createdAt
	this.UpdatedAt = updatedAt
	return &this
}

// NewBackupWithDefaults instantiates a new Backup object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewBackupWithDefaults() *Backup {
	this := Backup{}
	return &this
}

// GetId returns the Id field value
func (o *Backup) GetId() int32 {
	if o == nil {
		var ret int32
		return ret
	}

	return o.Id
}

// GetIdOk returns a tuple with the Id field value
// and a boolean to check if the value has been set.
func (o *Backup) GetIdOk() (*int32, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Id, true
}

// SetId sets field value
func (o *Backup) SetId(v int32) {
	o.Id = v
}

// GetName returns the Name field value
func (o *Backup) GetName() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Name
}

// GetNameOk returns a tuple with the Name field value
// and a boolean to check if the value has been set.
func (o *Backup) GetNameOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Name, true
}

// SetName sets field value
func (o *Backup) SetName(v string) {
	o.Name = v
}

// GetStatus returns the Status field value
func (o *Backup) GetStatus() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Status
}

// GetStatusOk returns a tuple with the Status field value
// and a boolean to check if the value has been set.
func (o *Backup) GetStatusOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Status, true
}

// SetStatus sets field value
func (o *Backup) SetStatus(v string) {
	o.Status = v
}

// GetAppInstanceId returns the AppInstanceId field value if set, zero value otherwise (both if not set or set to explicit null).
func (o *Backup) GetAppInstanceId() int32 {
	if o == nil || IsNil(o.AppInstanceId.Get()) {
		var ret int32
		return ret
	}
	return *o.AppInstanceId.Get()
}

// GetAppInstanceIdOk returns a tuple with the AppInstanceId field value if set, nil otherwise
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *Backup) GetAppInstanceIdOk() (*int32, bool) {
	if o == nil {
		return nil, false
	}
	return o.AppInstanceId.Get(), o.AppInstanceId.IsSet()
}

// HasAppInstanceId returns a boolean if a field has been set.
func (o *Backup) HasAppInstanceId() bool {
	if o != nil && o.AppInstanceId.IsSet() {
		return true
	}

	return false
}

// SetAppInstanceId gets a reference to the given NullableInt32 and assigns it to the AppInstanceId field.
func (o *Backup) SetAppInstanceId(v int32) {
	o.AppInstanceId.Set(&v)
}
// SetAppInstanceIdNil sets the value for AppInstanceId to be an explicit nil
func (o *Backup) SetAppInstanceIdNil() {
	o.AppInstanceId.Set(nil)
}

// UnsetAppInstanceId ensures that no value is present for AppInstanceId, not even an explicit nil
func (o *Backup) UnsetAppInstanceId() {
	o.AppInstanceId.Unset()
}

// GetAppServiceId returns the AppServiceId field value if set, zero value otherwise (both if not set or set to explicit null).
func (o *Backup) GetAppServiceId() int32 {
	if o == nil || IsNil(o.AppServiceId.Get()) {
		var ret int32
		return ret
	}
	return *o.AppServiceId.Get()
}

// GetAppServiceIdOk returns a tuple with the AppServiceId field value if set, nil otherwise
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *Backup) GetAppServiceIdOk() (*int32, bool) {
	if o == nil {
		return nil, false
	}
	return o.AppServiceId.Get(), o.AppServiceId.IsSet()
}

// HasAppServiceId returns a boolean if a field has been set.
func (o *Backup) HasAppServiceId() bool {
	if o != nil && o.AppServiceId.IsSet() {
		return true
	}

	return false
}

// SetAppServiceId gets a reference to the given NullableInt32 and assigns it to the AppServiceId field.
func (o *Backup) SetAppServiceId(v int32) {
	o.AppServiceId.Set(&v)
}
// SetAppServiceIdNil sets the value for AppServiceId to be an explicit nil
func (o *Backup) SetAppServiceIdNil() {
	o.AppServiceId.Set(nil)
}

// UnsetAppServiceId ensures that no value is present for AppServiceId, not even an explicit nil
func (o *Backup) UnsetAppServiceId() {
	o.AppServiceId.Unset()
}

// GetDatabaseId returns the DatabaseId field value if set, zero value otherwise (both if not set or set to explicit null).
func (o *Backup) GetDatabaseId() int32 {
	if o == nil || IsNil(o.DatabaseId.Get()) {
		var ret int32
		return ret
	}
	return *o.DatabaseId.Get()
}

// GetDatabaseIdOk returns a tuple with the DatabaseId field value if set, nil otherwise
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *Backup) GetDatabaseIdOk() (*int32, bool) {
	if o == nil {
		return nil, false
	}
	return o.DatabaseId.Get(), o.DatabaseId.IsSet()
}

// HasDatabaseId returns a boolean if a field has been set.
func (o *Backup) HasDatabaseId() bool {
	if o != nil && o.DatabaseId.IsSet() {
		return true
	}

	return false
}

// SetDatabaseId gets a reference to the given NullableInt32 and assigns it to the DatabaseId field.
func (o *Backup) SetDatabaseId(v int32) {
	o.DatabaseId.Set(&v)
}
// SetDatabaseIdNil sets the value for DatabaseId to be an explicit nil
func (o *Backup) SetDatabaseIdNil() {
	o.DatabaseId.Set(nil)
}

// UnsetDatabaseId ensures that no value is present for DatabaseId, not even an explicit nil
func (o *Backup) UnsetDatabaseId() {
	o.DatabaseId.Unset()
}

// GetDatabaseDbId returns the DatabaseDbId field value if set, zero value otherwise (both if not set or set to explicit null).
func (o *Backup) GetDatabaseDbId() int32 {
	if o == nil || IsNil(o.DatabaseDbId.Get()) {
		var ret int32
		return ret
	}
	return *o.DatabaseDbId.Get()
}

// GetDatabaseDbIdOk returns a tuple with the DatabaseDbId field value if set, nil otherwise
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *Backup) GetDatabaseDbIdOk() (*int32, bool) {
	if o == nil {
		return nil, false
	}
	return o.DatabaseDbId.Get(), o.DatabaseDbId.IsSet()
}

// HasDatabaseDbId returns a boolean if a field has been set.
func (o *Backup) HasDatabaseDbId() bool {
	if o != nil && o.DatabaseDbId.IsSet() {
		return true
	}

	return false
}

// SetDatabaseDbId gets a reference to the given NullableInt32 and assigns it to the DatabaseDbId field.
func (o *Backup) SetDatabaseDbId(v int32) {
	o.DatabaseDbId.Set(&v)
}
// SetDatabaseDbIdNil sets the value for DatabaseDbId to be an explicit nil
func (o *Backup) SetDatabaseDbIdNil() {
	o.DatabaseDbId.Set(nil)
}

// UnsetDatabaseDbId ensures that no value is present for DatabaseDbId, not even an explicit nil
func (o *Backup) UnsetDatabaseDbId() {
	o.DatabaseDbId.Unset()
}

// GetCreatedAt returns the CreatedAt field value
func (o *Backup) GetCreatedAt() time.Time {
	if o == nil {
		var ret time.Time
		return ret
	}

	return o.CreatedAt
}

// GetCreatedAtOk returns a tuple with the CreatedAt field value
// and a boolean to check if the value has been set.
func (o *Backup) GetCreatedAtOk() (*time.Time, bool) {
	if o == nil {
		return nil, false
	}
	return &o.CreatedAt, true
}

// SetCreatedAt sets field value
func (o *Backup) SetCreatedAt(v time.Time) {
	o.CreatedAt = v
}

// GetUpdatedAt returns the UpdatedAt field value
func (o *Backup) GetUpdatedAt() time.Time {
	if o == nil {
		var ret time.Time
		return ret
	}

	return o.UpdatedAt
}

// GetUpdatedAtOk returns a tuple with the UpdatedAt field value
// and a boolean to check if the value has been set.
func (o *Backup) GetUpdatedAtOk() (*time.Time, bool) {
	if o == nil {
		return nil, false
	}
	return &o.UpdatedAt, true
}

// SetUpdatedAt sets field value
func (o *Backup) SetUpdatedAt(v time.Time) {
	o.UpdatedAt = v
}

func (o Backup) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o Backup) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["id"] = o.Id
	toSerialize["name"] = o.Name
	toSerialize["status"] = o.Status
	if o.AppInstanceId.IsSet() {
		toSerialize["appInstanceId"] = o.AppInstanceId.Get()
	}
	if o.AppServiceId.IsSet() {
		toSerialize["appServiceId"] = o.AppServiceId.Get()
	}
	if o.DatabaseId.IsSet() {
		toSerialize["databaseId"] = o.DatabaseId.Get()
	}
	if o.DatabaseDbId.IsSet() {
		toSerialize["databaseDbId"] = o.DatabaseDbId.Get()
	}
	toSerialize["createdAt"] = o.CreatedAt
	toSerialize["updatedAt"] = o.UpdatedAt
	return toSerialize, nil
}

func (o *Backup) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"id",
		"name",
		"status",
		"createdAt",
		"updatedAt",
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err;
	}

	for _, requiredProperty := range(requiredProperties) {
		if _, exists := allProperties[requiredProperty]; !exists {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varBackup := _Backup{}

	decoder := json.NewDecoder(bytes.NewReader(data))
	decoder.DisallowUnknownFields()
	err = decoder.Decode(&varBackup)

	if err != nil {
		return err
	}

	*o = Backup(varBackup)

	return err
}

type NullableBackup struct {
	value *Backup
	isSet bool
}

func (v NullableBackup) Get() *Backup {
	return v.value
}

func (v *NullableBackup) Set(val *Backup) {
	v.value = val
	v.isSet = true
}

func (v NullableBackup) IsSet() bool {
	return v.isSet
}

func (v *NullableBackup) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableBackup(val *Backup) *NullableBackup {
	return &NullableBackup{value: val, isSet: true}
}

func (v NullableBackup) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableBackup) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


