/*
Wodby 2 Public API

Public REST API for customer SDKs and code integrations. GraphQL remains internal for the dashboard. This contract is the versioned public surface. 

API version: 1.0.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package client

import (
	"encoding/json"
	"time"
	"bytes"
	"fmt"
)

// checks if the TaskJob type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &TaskJob{}

// TaskJob struct for TaskJob
type TaskJob struct {
	Id int32 `json:"id"`
	Name string `json:"name"`
	Title string `json:"title"`
	Status string `json:"status"`
	After []string `json:"after,omitempty"`
	Timeout int32 `json:"timeout"`
	IsSystem bool `json:"isSystem"`
	StatusTitle string `json:"statusTitle"`
	Steps []TaskStep `json:"steps"`
	CreatedAt time.Time `json:"createdAt"`
	UpdatedAt time.Time `json:"updatedAt"`
	StartedAt NullableTime `json:"startedAt,omitempty"`
	EndedAt NullableTime `json:"endedAt,omitempty"`
}

type _TaskJob TaskJob

// NewTaskJob instantiates a new TaskJob object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewTaskJob(id int32, name string, title string, status string, timeout int32, isSystem bool, statusTitle string, steps []TaskStep, createdAt time.Time, updatedAt time.Time) *TaskJob {
	this := TaskJob{}
	this.Id = id
	this.Name = name
	this.Title = title
	this.Status = status
	this.Timeout = timeout
	this.IsSystem = isSystem
	this.StatusTitle = statusTitle
	this.Steps = steps
	this.CreatedAt = createdAt
	this.UpdatedAt = updatedAt
	return &this
}

// NewTaskJobWithDefaults instantiates a new TaskJob object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewTaskJobWithDefaults() *TaskJob {
	this := TaskJob{}
	return &this
}

// GetId returns the Id field value
func (o *TaskJob) GetId() int32 {
	if o == nil {
		var ret int32
		return ret
	}

	return o.Id
}

// GetIdOk returns a tuple with the Id field value
// and a boolean to check if the value has been set.
func (o *TaskJob) GetIdOk() (*int32, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Id, true
}

// SetId sets field value
func (o *TaskJob) SetId(v int32) {
	o.Id = v
}

// GetName returns the Name field value
func (o *TaskJob) GetName() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Name
}

// GetNameOk returns a tuple with the Name field value
// and a boolean to check if the value has been set.
func (o *TaskJob) GetNameOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Name, true
}

// SetName sets field value
func (o *TaskJob) SetName(v string) {
	o.Name = v
}

// GetTitle returns the Title field value
func (o *TaskJob) GetTitle() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Title
}

// GetTitleOk returns a tuple with the Title field value
// and a boolean to check if the value has been set.
func (o *TaskJob) GetTitleOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Title, true
}

// SetTitle sets field value
func (o *TaskJob) SetTitle(v string) {
	o.Title = v
}

// GetStatus returns the Status field value
func (o *TaskJob) GetStatus() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Status
}

// GetStatusOk returns a tuple with the Status field value
// and a boolean to check if the value has been set.
func (o *TaskJob) GetStatusOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Status, true
}

// SetStatus sets field value
func (o *TaskJob) SetStatus(v string) {
	o.Status = v
}

// GetAfter returns the After field value if set, zero value otherwise.
func (o *TaskJob) GetAfter() []string {
	if o == nil || IsNil(o.After) {
		var ret []string
		return ret
	}
	return o.After
}

// GetAfterOk returns a tuple with the After field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *TaskJob) GetAfterOk() ([]string, bool) {
	if o == nil || IsNil(o.After) {
		return nil, false
	}
	return o.After, true
}

// HasAfter returns a boolean if a field has been set.
func (o *TaskJob) HasAfter() bool {
	if o != nil && !IsNil(o.After) {
		return true
	}

	return false
}

// SetAfter gets a reference to the given []string and assigns it to the After field.
func (o *TaskJob) SetAfter(v []string) {
	o.After = v
}

// GetTimeout returns the Timeout field value
func (o *TaskJob) GetTimeout() int32 {
	if o == nil {
		var ret int32
		return ret
	}

	return o.Timeout
}

// GetTimeoutOk returns a tuple with the Timeout field value
// and a boolean to check if the value has been set.
func (o *TaskJob) GetTimeoutOk() (*int32, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Timeout, true
}

// SetTimeout sets field value
func (o *TaskJob) SetTimeout(v int32) {
	o.Timeout = v
}

// GetIsSystem returns the IsSystem field value
func (o *TaskJob) GetIsSystem() bool {
	if o == nil {
		var ret bool
		return ret
	}

	return o.IsSystem
}

// GetIsSystemOk returns a tuple with the IsSystem field value
// and a boolean to check if the value has been set.
func (o *TaskJob) GetIsSystemOk() (*bool, bool) {
	if o == nil {
		return nil, false
	}
	return &o.IsSystem, true
}

// SetIsSystem sets field value
func (o *TaskJob) SetIsSystem(v bool) {
	o.IsSystem = v
}

// GetStatusTitle returns the StatusTitle field value
func (o *TaskJob) GetStatusTitle() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.StatusTitle
}

// GetStatusTitleOk returns a tuple with the StatusTitle field value
// and a boolean to check if the value has been set.
func (o *TaskJob) GetStatusTitleOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.StatusTitle, true
}

// SetStatusTitle sets field value
func (o *TaskJob) SetStatusTitle(v string) {
	o.StatusTitle = v
}

// GetSteps returns the Steps field value
func (o *TaskJob) GetSteps() []TaskStep {
	if o == nil {
		var ret []TaskStep
		return ret
	}

	return o.Steps
}

// GetStepsOk returns a tuple with the Steps field value
// and a boolean to check if the value has been set.
func (o *TaskJob) GetStepsOk() ([]TaskStep, bool) {
	if o == nil {
		return nil, false
	}
	return o.Steps, true
}

// SetSteps sets field value
func (o *TaskJob) SetSteps(v []TaskStep) {
	o.Steps = v
}

// GetCreatedAt returns the CreatedAt field value
func (o *TaskJob) GetCreatedAt() time.Time {
	if o == nil {
		var ret time.Time
		return ret
	}

	return o.CreatedAt
}

// GetCreatedAtOk returns a tuple with the CreatedAt field value
// and a boolean to check if the value has been set.
func (o *TaskJob) GetCreatedAtOk() (*time.Time, bool) {
	if o == nil {
		return nil, false
	}
	return &o.CreatedAt, true
}

// SetCreatedAt sets field value
func (o *TaskJob) SetCreatedAt(v time.Time) {
	o.CreatedAt = v
}

// GetUpdatedAt returns the UpdatedAt field value
func (o *TaskJob) GetUpdatedAt() time.Time {
	if o == nil {
		var ret time.Time
		return ret
	}

	return o.UpdatedAt
}

// GetUpdatedAtOk returns a tuple with the UpdatedAt field value
// and a boolean to check if the value has been set.
func (o *TaskJob) GetUpdatedAtOk() (*time.Time, bool) {
	if o == nil {
		return nil, false
	}
	return &o.UpdatedAt, true
}

// SetUpdatedAt sets field value
func (o *TaskJob) SetUpdatedAt(v time.Time) {
	o.UpdatedAt = v
}

// GetStartedAt returns the StartedAt field value if set, zero value otherwise (both if not set or set to explicit null).
func (o *TaskJob) GetStartedAt() time.Time {
	if o == nil || IsNil(o.StartedAt.Get()) {
		var ret time.Time
		return ret
	}
	return *o.StartedAt.Get()
}

// GetStartedAtOk returns a tuple with the StartedAt field value if set, nil otherwise
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *TaskJob) GetStartedAtOk() (*time.Time, bool) {
	if o == nil {
		return nil, false
	}
	return o.StartedAt.Get(), o.StartedAt.IsSet()
}

// HasStartedAt returns a boolean if a field has been set.
func (o *TaskJob) HasStartedAt() bool {
	if o != nil && o.StartedAt.IsSet() {
		return true
	}

	return false
}

// SetStartedAt gets a reference to the given NullableTime and assigns it to the StartedAt field.
func (o *TaskJob) SetStartedAt(v time.Time) {
	o.StartedAt.Set(&v)
}
// SetStartedAtNil sets the value for StartedAt to be an explicit nil
func (o *TaskJob) SetStartedAtNil() {
	o.StartedAt.Set(nil)
}

// UnsetStartedAt ensures that no value is present for StartedAt, not even an explicit nil
func (o *TaskJob) UnsetStartedAt() {
	o.StartedAt.Unset()
}

// GetEndedAt returns the EndedAt field value if set, zero value otherwise (both if not set or set to explicit null).
func (o *TaskJob) GetEndedAt() time.Time {
	if o == nil || IsNil(o.EndedAt.Get()) {
		var ret time.Time
		return ret
	}
	return *o.EndedAt.Get()
}

// GetEndedAtOk returns a tuple with the EndedAt field value if set, nil otherwise
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *TaskJob) GetEndedAtOk() (*time.Time, bool) {
	if o == nil {
		return nil, false
	}
	return o.EndedAt.Get(), o.EndedAt.IsSet()
}

// HasEndedAt returns a boolean if a field has been set.
func (o *TaskJob) HasEndedAt() bool {
	if o != nil && o.EndedAt.IsSet() {
		return true
	}

	return false
}

// SetEndedAt gets a reference to the given NullableTime and assigns it to the EndedAt field.
func (o *TaskJob) SetEndedAt(v time.Time) {
	o.EndedAt.Set(&v)
}
// SetEndedAtNil sets the value for EndedAt to be an explicit nil
func (o *TaskJob) SetEndedAtNil() {
	o.EndedAt.Set(nil)
}

// UnsetEndedAt ensures that no value is present for EndedAt, not even an explicit nil
func (o *TaskJob) UnsetEndedAt() {
	o.EndedAt.Unset()
}

func (o TaskJob) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o TaskJob) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["id"] = o.Id
	toSerialize["name"] = o.Name
	toSerialize["title"] = o.Title
	toSerialize["status"] = o.Status
	if !IsNil(o.After) {
		toSerialize["after"] = o.After
	}
	toSerialize["timeout"] = o.Timeout
	toSerialize["isSystem"] = o.IsSystem
	toSerialize["statusTitle"] = o.StatusTitle
	toSerialize["steps"] = o.Steps
	toSerialize["createdAt"] = o.CreatedAt
	toSerialize["updatedAt"] = o.UpdatedAt
	if o.StartedAt.IsSet() {
		toSerialize["startedAt"] = o.StartedAt.Get()
	}
	if o.EndedAt.IsSet() {
		toSerialize["endedAt"] = o.EndedAt.Get()
	}
	return toSerialize, nil
}

func (o *TaskJob) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"id",
		"name",
		"title",
		"status",
		"timeout",
		"isSystem",
		"statusTitle",
		"steps",
		"createdAt",
		"updatedAt",
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err;
	}

	for _, requiredProperty := range(requiredProperties) {
		if _, exists := allProperties[requiredProperty]; !exists {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varTaskJob := _TaskJob{}

	decoder := json.NewDecoder(bytes.NewReader(data))
	decoder.DisallowUnknownFields()
	err = decoder.Decode(&varTaskJob)

	if err != nil {
		return err
	}

	*o = TaskJob(varTaskJob)

	return err
}

type NullableTaskJob struct {
	value *TaskJob
	isSet bool
}

func (v NullableTaskJob) Get() *TaskJob {
	return v.value
}

func (v *NullableTaskJob) Set(val *TaskJob) {
	v.value = val
	v.isSet = true
}

func (v NullableTaskJob) IsSet() bool {
	return v.isSet
}

func (v *NullableTaskJob) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableTaskJob(val *TaskJob) *NullableTaskJob {
	return &NullableTaskJob{value: val, isSet: true}
}

func (v NullableTaskJob) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableTaskJob) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


