/*
Wodby 2 Public API

Public REST API for customer SDKs and code integrations. GraphQL remains internal for the dashboard. This contract is the versioned public surface. 

API version: 1.0.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package client

import (
	"encoding/json"
	"bytes"
	"fmt"
)

// checks if the HelmChartStackScaffoldResponse type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &HelmChartStackScaffoldResponse{}

// HelmChartStackScaffoldResponse struct for HelmChartStackScaffoldResponse
type HelmChartStackScaffoldResponse struct {
	Analysis HelmChartAnalysis `json:"analysis"`
	ServiceManifestYaml string `json:"serviceManifestYaml"`
	ServiceManifest map[string]interface{} `json:"serviceManifest"`
	StackManifestYaml string `json:"stackManifestYaml"`
	StackManifest map[string]interface{} `json:"stackManifest"`
	Warnings []string `json:"warnings,omitempty"`
}

type _HelmChartStackScaffoldResponse HelmChartStackScaffoldResponse

// NewHelmChartStackScaffoldResponse instantiates a new HelmChartStackScaffoldResponse object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewHelmChartStackScaffoldResponse(analysis HelmChartAnalysis, serviceManifestYaml string, serviceManifest map[string]interface{}, stackManifestYaml string, stackManifest map[string]interface{}) *HelmChartStackScaffoldResponse {
	this := HelmChartStackScaffoldResponse{}
	this.Analysis = analysis
	this.ServiceManifestYaml = serviceManifestYaml
	this.ServiceManifest = serviceManifest
	this.StackManifestYaml = stackManifestYaml
	this.StackManifest = stackManifest
	return &this
}

// NewHelmChartStackScaffoldResponseWithDefaults instantiates a new HelmChartStackScaffoldResponse object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewHelmChartStackScaffoldResponseWithDefaults() *HelmChartStackScaffoldResponse {
	this := HelmChartStackScaffoldResponse{}
	return &this
}

// GetAnalysis returns the Analysis field value
func (o *HelmChartStackScaffoldResponse) GetAnalysis() HelmChartAnalysis {
	if o == nil {
		var ret HelmChartAnalysis
		return ret
	}

	return o.Analysis
}

// GetAnalysisOk returns a tuple with the Analysis field value
// and a boolean to check if the value has been set.
func (o *HelmChartStackScaffoldResponse) GetAnalysisOk() (*HelmChartAnalysis, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Analysis, true
}

// SetAnalysis sets field value
func (o *HelmChartStackScaffoldResponse) SetAnalysis(v HelmChartAnalysis) {
	o.Analysis = v
}

// GetServiceManifestYaml returns the ServiceManifestYaml field value
func (o *HelmChartStackScaffoldResponse) GetServiceManifestYaml() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.ServiceManifestYaml
}

// GetServiceManifestYamlOk returns a tuple with the ServiceManifestYaml field value
// and a boolean to check if the value has been set.
func (o *HelmChartStackScaffoldResponse) GetServiceManifestYamlOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.ServiceManifestYaml, true
}

// SetServiceManifestYaml sets field value
func (o *HelmChartStackScaffoldResponse) SetServiceManifestYaml(v string) {
	o.ServiceManifestYaml = v
}

// GetServiceManifest returns the ServiceManifest field value
func (o *HelmChartStackScaffoldResponse) GetServiceManifest() map[string]interface{} {
	if o == nil {
		var ret map[string]interface{}
		return ret
	}

	return o.ServiceManifest
}

// GetServiceManifestOk returns a tuple with the ServiceManifest field value
// and a boolean to check if the value has been set.
func (o *HelmChartStackScaffoldResponse) GetServiceManifestOk() (map[string]interface{}, bool) {
	if o == nil {
		return map[string]interface{}{}, false
	}
	return o.ServiceManifest, true
}

// SetServiceManifest sets field value
func (o *HelmChartStackScaffoldResponse) SetServiceManifest(v map[string]interface{}) {
	o.ServiceManifest = v
}

// GetStackManifestYaml returns the StackManifestYaml field value
func (o *HelmChartStackScaffoldResponse) GetStackManifestYaml() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.StackManifestYaml
}

// GetStackManifestYamlOk returns a tuple with the StackManifestYaml field value
// and a boolean to check if the value has been set.
func (o *HelmChartStackScaffoldResponse) GetStackManifestYamlOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.StackManifestYaml, true
}

// SetStackManifestYaml sets field value
func (o *HelmChartStackScaffoldResponse) SetStackManifestYaml(v string) {
	o.StackManifestYaml = v
}

// GetStackManifest returns the StackManifest field value
func (o *HelmChartStackScaffoldResponse) GetStackManifest() map[string]interface{} {
	if o == nil {
		var ret map[string]interface{}
		return ret
	}

	return o.StackManifest
}

// GetStackManifestOk returns a tuple with the StackManifest field value
// and a boolean to check if the value has been set.
func (o *HelmChartStackScaffoldResponse) GetStackManifestOk() (map[string]interface{}, bool) {
	if o == nil {
		return map[string]interface{}{}, false
	}
	return o.StackManifest, true
}

// SetStackManifest sets field value
func (o *HelmChartStackScaffoldResponse) SetStackManifest(v map[string]interface{}) {
	o.StackManifest = v
}

// GetWarnings returns the Warnings field value if set, zero value otherwise.
func (o *HelmChartStackScaffoldResponse) GetWarnings() []string {
	if o == nil || IsNil(o.Warnings) {
		var ret []string
		return ret
	}
	return o.Warnings
}

// GetWarningsOk returns a tuple with the Warnings field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *HelmChartStackScaffoldResponse) GetWarningsOk() ([]string, bool) {
	if o == nil || IsNil(o.Warnings) {
		return nil, false
	}
	return o.Warnings, true
}

// HasWarnings returns a boolean if a field has been set.
func (o *HelmChartStackScaffoldResponse) HasWarnings() bool {
	if o != nil && !IsNil(o.Warnings) {
		return true
	}

	return false
}

// SetWarnings gets a reference to the given []string and assigns it to the Warnings field.
func (o *HelmChartStackScaffoldResponse) SetWarnings(v []string) {
	o.Warnings = v
}

func (o HelmChartStackScaffoldResponse) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o HelmChartStackScaffoldResponse) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["analysis"] = o.Analysis
	toSerialize["serviceManifestYaml"] = o.ServiceManifestYaml
	toSerialize["serviceManifest"] = o.ServiceManifest
	toSerialize["stackManifestYaml"] = o.StackManifestYaml
	toSerialize["stackManifest"] = o.StackManifest
	if !IsNil(o.Warnings) {
		toSerialize["warnings"] = o.Warnings
	}
	return toSerialize, nil
}

func (o *HelmChartStackScaffoldResponse) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"analysis",
		"serviceManifestYaml",
		"serviceManifest",
		"stackManifestYaml",
		"stackManifest",
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err;
	}

	for _, requiredProperty := range(requiredProperties) {
		if _, exists := allProperties[requiredProperty]; !exists {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varHelmChartStackScaffoldResponse := _HelmChartStackScaffoldResponse{}

	decoder := json.NewDecoder(bytes.NewReader(data))
	decoder.DisallowUnknownFields()
	err = decoder.Decode(&varHelmChartStackScaffoldResponse)

	if err != nil {
		return err
	}

	*o = HelmChartStackScaffoldResponse(varHelmChartStackScaffoldResponse)

	return err
}

type NullableHelmChartStackScaffoldResponse struct {
	value *HelmChartStackScaffoldResponse
	isSet bool
}

func (v NullableHelmChartStackScaffoldResponse) Get() *HelmChartStackScaffoldResponse {
	return v.value
}

func (v *NullableHelmChartStackScaffoldResponse) Set(val *HelmChartStackScaffoldResponse) {
	v.value = val
	v.isSet = true
}

func (v NullableHelmChartStackScaffoldResponse) IsSet() bool {
	return v.isSet
}

func (v *NullableHelmChartStackScaffoldResponse) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableHelmChartStackScaffoldResponse(val *HelmChartStackScaffoldResponse) *NullableHelmChartStackScaffoldResponse {
	return &NullableHelmChartStackScaffoldResponse{value: val, isSet: true}
}

func (v NullableHelmChartStackScaffoldResponse) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableHelmChartStackScaffoldResponse) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


