/*
Wodby 2 Public API

Public REST API for customer SDKs and code integrations. GraphQL remains internal for the dashboard. This contract is the versioned public surface. 

API version: 1.0.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package client

import (
	"encoding/json"
	"bytes"
	"fmt"
)

// checks if the AppServiceScalability type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &AppServiceScalability{}

// AppServiceScalability struct for AppServiceScalability
type AppServiceScalability struct {
	AverageCPU int32 `json:"averageCPU"`
	MinReplicas int32 `json:"minReplicas"`
	MaxReplicas int32 `json:"maxReplicas"`
}

type _AppServiceScalability AppServiceScalability

// NewAppServiceScalability instantiates a new AppServiceScalability object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewAppServiceScalability(averageCPU int32, minReplicas int32, maxReplicas int32) *AppServiceScalability {
	this := AppServiceScalability{}
	this.AverageCPU = averageCPU
	this.MinReplicas = minReplicas
	this.MaxReplicas = maxReplicas
	return &this
}

// NewAppServiceScalabilityWithDefaults instantiates a new AppServiceScalability object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewAppServiceScalabilityWithDefaults() *AppServiceScalability {
	this := AppServiceScalability{}
	return &this
}

// GetAverageCPU returns the AverageCPU field value
func (o *AppServiceScalability) GetAverageCPU() int32 {
	if o == nil {
		var ret int32
		return ret
	}

	return o.AverageCPU
}

// GetAverageCPUOk returns a tuple with the AverageCPU field value
// and a boolean to check if the value has been set.
func (o *AppServiceScalability) GetAverageCPUOk() (*int32, bool) {
	if o == nil {
		return nil, false
	}
	return &o.AverageCPU, true
}

// SetAverageCPU sets field value
func (o *AppServiceScalability) SetAverageCPU(v int32) {
	o.AverageCPU = v
}

// GetMinReplicas returns the MinReplicas field value
func (o *AppServiceScalability) GetMinReplicas() int32 {
	if o == nil {
		var ret int32
		return ret
	}

	return o.MinReplicas
}

// GetMinReplicasOk returns a tuple with the MinReplicas field value
// and a boolean to check if the value has been set.
func (o *AppServiceScalability) GetMinReplicasOk() (*int32, bool) {
	if o == nil {
		return nil, false
	}
	return &o.MinReplicas, true
}

// SetMinReplicas sets field value
func (o *AppServiceScalability) SetMinReplicas(v int32) {
	o.MinReplicas = v
}

// GetMaxReplicas returns the MaxReplicas field value
func (o *AppServiceScalability) GetMaxReplicas() int32 {
	if o == nil {
		var ret int32
		return ret
	}

	return o.MaxReplicas
}

// GetMaxReplicasOk returns a tuple with the MaxReplicas field value
// and a boolean to check if the value has been set.
func (o *AppServiceScalability) GetMaxReplicasOk() (*int32, bool) {
	if o == nil {
		return nil, false
	}
	return &o.MaxReplicas, true
}

// SetMaxReplicas sets field value
func (o *AppServiceScalability) SetMaxReplicas(v int32) {
	o.MaxReplicas = v
}

func (o AppServiceScalability) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o AppServiceScalability) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["averageCPU"] = o.AverageCPU
	toSerialize["minReplicas"] = o.MinReplicas
	toSerialize["maxReplicas"] = o.MaxReplicas
	return toSerialize, nil
}

func (o *AppServiceScalability) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"averageCPU",
		"minReplicas",
		"maxReplicas",
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err;
	}

	for _, requiredProperty := range(requiredProperties) {
		if _, exists := allProperties[requiredProperty]; !exists {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varAppServiceScalability := _AppServiceScalability{}

	decoder := json.NewDecoder(bytes.NewReader(data))
	decoder.DisallowUnknownFields()
	err = decoder.Decode(&varAppServiceScalability)

	if err != nil {
		return err
	}

	*o = AppServiceScalability(varAppServiceScalability)

	return err
}

type NullableAppServiceScalability struct {
	value *AppServiceScalability
	isSet bool
}

func (v NullableAppServiceScalability) Get() *AppServiceScalability {
	return v.value
}

func (v *NullableAppServiceScalability) Set(val *AppServiceScalability) {
	v.value = val
	v.isSet = true
}

func (v NullableAppServiceScalability) IsSet() bool {
	return v.isSet
}

func (v *NullableAppServiceScalability) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableAppServiceScalability(val *AppServiceScalability) *NullableAppServiceScalability {
	return &NullableAppServiceScalability{value: val, isSet: true}
}

func (v NullableAppServiceScalability) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableAppServiceScalability) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


