/*
Wodby 2 Public API

Public REST API for customer SDKs and code integrations. GraphQL remains internal for the dashboard. This contract is the versioned public surface. 

API version: 1.0.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package client

import (
	"encoding/json"
	"bytes"
	"fmt"
)

// checks if the NewDatabaseInput type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &NewDatabaseInput{}

// NewDatabaseInput envType is required for the canonical contract. The legacy envId alternative remains accepted, but the two fields cannot be combined.
type NewDatabaseInput struct {
	// Optional for API-key requests; defaults to the API key's organization.
	OrgId *int32 `json:"orgId,omitempty"`
	ProjectId NullableInt32 `json:"projectId,omitempty"`
	// Deprecated
	EnvId *int32 `json:"envId,omitempty"`
	EnvType *string `json:"envType,omitempty"`
	Name string `json:"name"`
	Title string `json:"title"`
	IntegrationKindId int32 `json:"integrationKindId"`
	Type string `json:"type"`
	Version string `json:"version"`
	MachineType string `json:"machineType"`
	StorageSize NullableInt32 `json:"storageSize,omitempty"`
	Password NullableString `json:"password,omitempty"`
	StorageAutoscaling NullableBool `json:"storageAutoscaling,omitempty"`
	HighAvailability NullableBool `json:"highAvailability,omitempty"`
	Region NullableString `json:"region,omitempty"`
	Zone NullableString `json:"zone,omitempty"`
	ResidedClusterId NullableInt32 `json:"residedClusterId,omitempty"`
	Iops NullableInt32 `json:"iops,omitempty"`
}

type _NewDatabaseInput NewDatabaseInput

// NewNewDatabaseInput instantiates a new NewDatabaseInput object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewNewDatabaseInput(name string, title string, integrationKindId int32, type_ string, version string, machineType string) *NewDatabaseInput {
	this := NewDatabaseInput{}
	this.Name = name
	this.Title = title
	this.IntegrationKindId = integrationKindId
	this.Type = type_
	this.Version = version
	this.MachineType = machineType
	return &this
}

// NewNewDatabaseInputWithDefaults instantiates a new NewDatabaseInput object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewNewDatabaseInputWithDefaults() *NewDatabaseInput {
	this := NewDatabaseInput{}
	return &this
}

// GetOrgId returns the OrgId field value if set, zero value otherwise.
func (o *NewDatabaseInput) GetOrgId() int32 {
	if o == nil || IsNil(o.OrgId) {
		var ret int32
		return ret
	}
	return *o.OrgId
}

// GetOrgIdOk returns a tuple with the OrgId field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *NewDatabaseInput) GetOrgIdOk() (*int32, bool) {
	if o == nil || IsNil(o.OrgId) {
		return nil, false
	}
	return o.OrgId, true
}

// HasOrgId returns a boolean if a field has been set.
func (o *NewDatabaseInput) HasOrgId() bool {
	if o != nil && !IsNil(o.OrgId) {
		return true
	}

	return false
}

// SetOrgId gets a reference to the given int32 and assigns it to the OrgId field.
func (o *NewDatabaseInput) SetOrgId(v int32) {
	o.OrgId = &v
}

// GetProjectId returns the ProjectId field value if set, zero value otherwise (both if not set or set to explicit null).
func (o *NewDatabaseInput) GetProjectId() int32 {
	if o == nil || IsNil(o.ProjectId.Get()) {
		var ret int32
		return ret
	}
	return *o.ProjectId.Get()
}

// GetProjectIdOk returns a tuple with the ProjectId field value if set, nil otherwise
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *NewDatabaseInput) GetProjectIdOk() (*int32, bool) {
	if o == nil {
		return nil, false
	}
	return o.ProjectId.Get(), o.ProjectId.IsSet()
}

// HasProjectId returns a boolean if a field has been set.
func (o *NewDatabaseInput) HasProjectId() bool {
	if o != nil && o.ProjectId.IsSet() {
		return true
	}

	return false
}

// SetProjectId gets a reference to the given NullableInt32 and assigns it to the ProjectId field.
func (o *NewDatabaseInput) SetProjectId(v int32) {
	o.ProjectId.Set(&v)
}
// SetProjectIdNil sets the value for ProjectId to be an explicit nil
func (o *NewDatabaseInput) SetProjectIdNil() {
	o.ProjectId.Set(nil)
}

// UnsetProjectId ensures that no value is present for ProjectId, not even an explicit nil
func (o *NewDatabaseInput) UnsetProjectId() {
	o.ProjectId.Unset()
}

// GetEnvId returns the EnvId field value if set, zero value otherwise.
// Deprecated
func (o *NewDatabaseInput) GetEnvId() int32 {
	if o == nil || IsNil(o.EnvId) {
		var ret int32
		return ret
	}
	return *o.EnvId
}

// GetEnvIdOk returns a tuple with the EnvId field value if set, nil otherwise
// and a boolean to check if the value has been set.
// Deprecated
func (o *NewDatabaseInput) GetEnvIdOk() (*int32, bool) {
	if o == nil || IsNil(o.EnvId) {
		return nil, false
	}
	return o.EnvId, true
}

// HasEnvId returns a boolean if a field has been set.
func (o *NewDatabaseInput) HasEnvId() bool {
	if o != nil && !IsNil(o.EnvId) {
		return true
	}

	return false
}

// SetEnvId gets a reference to the given int32 and assigns it to the EnvId field.
// Deprecated
func (o *NewDatabaseInput) SetEnvId(v int32) {
	o.EnvId = &v
}

// GetEnvType returns the EnvType field value if set, zero value otherwise.
func (o *NewDatabaseInput) GetEnvType() string {
	if o == nil || IsNil(o.EnvType) {
		var ret string
		return ret
	}
	return *o.EnvType
}

// GetEnvTypeOk returns a tuple with the EnvType field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *NewDatabaseInput) GetEnvTypeOk() (*string, bool) {
	if o == nil || IsNil(o.EnvType) {
		return nil, false
	}
	return o.EnvType, true
}

// HasEnvType returns a boolean if a field has been set.
func (o *NewDatabaseInput) HasEnvType() bool {
	if o != nil && !IsNil(o.EnvType) {
		return true
	}

	return false
}

// SetEnvType gets a reference to the given string and assigns it to the EnvType field.
func (o *NewDatabaseInput) SetEnvType(v string) {
	o.EnvType = &v
}

// GetName returns the Name field value
func (o *NewDatabaseInput) GetName() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Name
}

// GetNameOk returns a tuple with the Name field value
// and a boolean to check if the value has been set.
func (o *NewDatabaseInput) GetNameOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Name, true
}

// SetName sets field value
func (o *NewDatabaseInput) SetName(v string) {
	o.Name = v
}

// GetTitle returns the Title field value
func (o *NewDatabaseInput) GetTitle() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Title
}

// GetTitleOk returns a tuple with the Title field value
// and a boolean to check if the value has been set.
func (o *NewDatabaseInput) GetTitleOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Title, true
}

// SetTitle sets field value
func (o *NewDatabaseInput) SetTitle(v string) {
	o.Title = v
}

// GetIntegrationKindId returns the IntegrationKindId field value
func (o *NewDatabaseInput) GetIntegrationKindId() int32 {
	if o == nil {
		var ret int32
		return ret
	}

	return o.IntegrationKindId
}

// GetIntegrationKindIdOk returns a tuple with the IntegrationKindId field value
// and a boolean to check if the value has been set.
func (o *NewDatabaseInput) GetIntegrationKindIdOk() (*int32, bool) {
	if o == nil {
		return nil, false
	}
	return &o.IntegrationKindId, true
}

// SetIntegrationKindId sets field value
func (o *NewDatabaseInput) SetIntegrationKindId(v int32) {
	o.IntegrationKindId = v
}

// GetType returns the Type field value
func (o *NewDatabaseInput) GetType() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Type
}

// GetTypeOk returns a tuple with the Type field value
// and a boolean to check if the value has been set.
func (o *NewDatabaseInput) GetTypeOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Type, true
}

// SetType sets field value
func (o *NewDatabaseInput) SetType(v string) {
	o.Type = v
}

// GetVersion returns the Version field value
func (o *NewDatabaseInput) GetVersion() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Version
}

// GetVersionOk returns a tuple with the Version field value
// and a boolean to check if the value has been set.
func (o *NewDatabaseInput) GetVersionOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Version, true
}

// SetVersion sets field value
func (o *NewDatabaseInput) SetVersion(v string) {
	o.Version = v
}

// GetMachineType returns the MachineType field value
func (o *NewDatabaseInput) GetMachineType() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.MachineType
}

// GetMachineTypeOk returns a tuple with the MachineType field value
// and a boolean to check if the value has been set.
func (o *NewDatabaseInput) GetMachineTypeOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.MachineType, true
}

// SetMachineType sets field value
func (o *NewDatabaseInput) SetMachineType(v string) {
	o.MachineType = v
}

// GetStorageSize returns the StorageSize field value if set, zero value otherwise (both if not set or set to explicit null).
func (o *NewDatabaseInput) GetStorageSize() int32 {
	if o == nil || IsNil(o.StorageSize.Get()) {
		var ret int32
		return ret
	}
	return *o.StorageSize.Get()
}

// GetStorageSizeOk returns a tuple with the StorageSize field value if set, nil otherwise
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *NewDatabaseInput) GetStorageSizeOk() (*int32, bool) {
	if o == nil {
		return nil, false
	}
	return o.StorageSize.Get(), o.StorageSize.IsSet()
}

// HasStorageSize returns a boolean if a field has been set.
func (o *NewDatabaseInput) HasStorageSize() bool {
	if o != nil && o.StorageSize.IsSet() {
		return true
	}

	return false
}

// SetStorageSize gets a reference to the given NullableInt32 and assigns it to the StorageSize field.
func (o *NewDatabaseInput) SetStorageSize(v int32) {
	o.StorageSize.Set(&v)
}
// SetStorageSizeNil sets the value for StorageSize to be an explicit nil
func (o *NewDatabaseInput) SetStorageSizeNil() {
	o.StorageSize.Set(nil)
}

// UnsetStorageSize ensures that no value is present for StorageSize, not even an explicit nil
func (o *NewDatabaseInput) UnsetStorageSize() {
	o.StorageSize.Unset()
}

// GetPassword returns the Password field value if set, zero value otherwise (both if not set or set to explicit null).
func (o *NewDatabaseInput) GetPassword() string {
	if o == nil || IsNil(o.Password.Get()) {
		var ret string
		return ret
	}
	return *o.Password.Get()
}

// GetPasswordOk returns a tuple with the Password field value if set, nil otherwise
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *NewDatabaseInput) GetPasswordOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return o.Password.Get(), o.Password.IsSet()
}

// HasPassword returns a boolean if a field has been set.
func (o *NewDatabaseInput) HasPassword() bool {
	if o != nil && o.Password.IsSet() {
		return true
	}

	return false
}

// SetPassword gets a reference to the given NullableString and assigns it to the Password field.
func (o *NewDatabaseInput) SetPassword(v string) {
	o.Password.Set(&v)
}
// SetPasswordNil sets the value for Password to be an explicit nil
func (o *NewDatabaseInput) SetPasswordNil() {
	o.Password.Set(nil)
}

// UnsetPassword ensures that no value is present for Password, not even an explicit nil
func (o *NewDatabaseInput) UnsetPassword() {
	o.Password.Unset()
}

// GetStorageAutoscaling returns the StorageAutoscaling field value if set, zero value otherwise (both if not set or set to explicit null).
func (o *NewDatabaseInput) GetStorageAutoscaling() bool {
	if o == nil || IsNil(o.StorageAutoscaling.Get()) {
		var ret bool
		return ret
	}
	return *o.StorageAutoscaling.Get()
}

// GetStorageAutoscalingOk returns a tuple with the StorageAutoscaling field value if set, nil otherwise
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *NewDatabaseInput) GetStorageAutoscalingOk() (*bool, bool) {
	if o == nil {
		return nil, false
	}
	return o.StorageAutoscaling.Get(), o.StorageAutoscaling.IsSet()
}

// HasStorageAutoscaling returns a boolean if a field has been set.
func (o *NewDatabaseInput) HasStorageAutoscaling() bool {
	if o != nil && o.StorageAutoscaling.IsSet() {
		return true
	}

	return false
}

// SetStorageAutoscaling gets a reference to the given NullableBool and assigns it to the StorageAutoscaling field.
func (o *NewDatabaseInput) SetStorageAutoscaling(v bool) {
	o.StorageAutoscaling.Set(&v)
}
// SetStorageAutoscalingNil sets the value for StorageAutoscaling to be an explicit nil
func (o *NewDatabaseInput) SetStorageAutoscalingNil() {
	o.StorageAutoscaling.Set(nil)
}

// UnsetStorageAutoscaling ensures that no value is present for StorageAutoscaling, not even an explicit nil
func (o *NewDatabaseInput) UnsetStorageAutoscaling() {
	o.StorageAutoscaling.Unset()
}

// GetHighAvailability returns the HighAvailability field value if set, zero value otherwise (both if not set or set to explicit null).
func (o *NewDatabaseInput) GetHighAvailability() bool {
	if o == nil || IsNil(o.HighAvailability.Get()) {
		var ret bool
		return ret
	}
	return *o.HighAvailability.Get()
}

// GetHighAvailabilityOk returns a tuple with the HighAvailability field value if set, nil otherwise
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *NewDatabaseInput) GetHighAvailabilityOk() (*bool, bool) {
	if o == nil {
		return nil, false
	}
	return o.HighAvailability.Get(), o.HighAvailability.IsSet()
}

// HasHighAvailability returns a boolean if a field has been set.
func (o *NewDatabaseInput) HasHighAvailability() bool {
	if o != nil && o.HighAvailability.IsSet() {
		return true
	}

	return false
}

// SetHighAvailability gets a reference to the given NullableBool and assigns it to the HighAvailability field.
func (o *NewDatabaseInput) SetHighAvailability(v bool) {
	o.HighAvailability.Set(&v)
}
// SetHighAvailabilityNil sets the value for HighAvailability to be an explicit nil
func (o *NewDatabaseInput) SetHighAvailabilityNil() {
	o.HighAvailability.Set(nil)
}

// UnsetHighAvailability ensures that no value is present for HighAvailability, not even an explicit nil
func (o *NewDatabaseInput) UnsetHighAvailability() {
	o.HighAvailability.Unset()
}

// GetRegion returns the Region field value if set, zero value otherwise (both if not set or set to explicit null).
func (o *NewDatabaseInput) GetRegion() string {
	if o == nil || IsNil(o.Region.Get()) {
		var ret string
		return ret
	}
	return *o.Region.Get()
}

// GetRegionOk returns a tuple with the Region field value if set, nil otherwise
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *NewDatabaseInput) GetRegionOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return o.Region.Get(), o.Region.IsSet()
}

// HasRegion returns a boolean if a field has been set.
func (o *NewDatabaseInput) HasRegion() bool {
	if o != nil && o.Region.IsSet() {
		return true
	}

	return false
}

// SetRegion gets a reference to the given NullableString and assigns it to the Region field.
func (o *NewDatabaseInput) SetRegion(v string) {
	o.Region.Set(&v)
}
// SetRegionNil sets the value for Region to be an explicit nil
func (o *NewDatabaseInput) SetRegionNil() {
	o.Region.Set(nil)
}

// UnsetRegion ensures that no value is present for Region, not even an explicit nil
func (o *NewDatabaseInput) UnsetRegion() {
	o.Region.Unset()
}

// GetZone returns the Zone field value if set, zero value otherwise (both if not set or set to explicit null).
func (o *NewDatabaseInput) GetZone() string {
	if o == nil || IsNil(o.Zone.Get()) {
		var ret string
		return ret
	}
	return *o.Zone.Get()
}

// GetZoneOk returns a tuple with the Zone field value if set, nil otherwise
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *NewDatabaseInput) GetZoneOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return o.Zone.Get(), o.Zone.IsSet()
}

// HasZone returns a boolean if a field has been set.
func (o *NewDatabaseInput) HasZone() bool {
	if o != nil && o.Zone.IsSet() {
		return true
	}

	return false
}

// SetZone gets a reference to the given NullableString and assigns it to the Zone field.
func (o *NewDatabaseInput) SetZone(v string) {
	o.Zone.Set(&v)
}
// SetZoneNil sets the value for Zone to be an explicit nil
func (o *NewDatabaseInput) SetZoneNil() {
	o.Zone.Set(nil)
}

// UnsetZone ensures that no value is present for Zone, not even an explicit nil
func (o *NewDatabaseInput) UnsetZone() {
	o.Zone.Unset()
}

// GetResidedClusterId returns the ResidedClusterId field value if set, zero value otherwise (both if not set or set to explicit null).
func (o *NewDatabaseInput) GetResidedClusterId() int32 {
	if o == nil || IsNil(o.ResidedClusterId.Get()) {
		var ret int32
		return ret
	}
	return *o.ResidedClusterId.Get()
}

// GetResidedClusterIdOk returns a tuple with the ResidedClusterId field value if set, nil otherwise
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *NewDatabaseInput) GetResidedClusterIdOk() (*int32, bool) {
	if o == nil {
		return nil, false
	}
	return o.ResidedClusterId.Get(), o.ResidedClusterId.IsSet()
}

// HasResidedClusterId returns a boolean if a field has been set.
func (o *NewDatabaseInput) HasResidedClusterId() bool {
	if o != nil && o.ResidedClusterId.IsSet() {
		return true
	}

	return false
}

// SetResidedClusterId gets a reference to the given NullableInt32 and assigns it to the ResidedClusterId field.
func (o *NewDatabaseInput) SetResidedClusterId(v int32) {
	o.ResidedClusterId.Set(&v)
}
// SetResidedClusterIdNil sets the value for ResidedClusterId to be an explicit nil
func (o *NewDatabaseInput) SetResidedClusterIdNil() {
	o.ResidedClusterId.Set(nil)
}

// UnsetResidedClusterId ensures that no value is present for ResidedClusterId, not even an explicit nil
func (o *NewDatabaseInput) UnsetResidedClusterId() {
	o.ResidedClusterId.Unset()
}

// GetIops returns the Iops field value if set, zero value otherwise (both if not set or set to explicit null).
func (o *NewDatabaseInput) GetIops() int32 {
	if o == nil || IsNil(o.Iops.Get()) {
		var ret int32
		return ret
	}
	return *o.Iops.Get()
}

// GetIopsOk returns a tuple with the Iops field value if set, nil otherwise
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *NewDatabaseInput) GetIopsOk() (*int32, bool) {
	if o == nil {
		return nil, false
	}
	return o.Iops.Get(), o.Iops.IsSet()
}

// HasIops returns a boolean if a field has been set.
func (o *NewDatabaseInput) HasIops() bool {
	if o != nil && o.Iops.IsSet() {
		return true
	}

	return false
}

// SetIops gets a reference to the given NullableInt32 and assigns it to the Iops field.
func (o *NewDatabaseInput) SetIops(v int32) {
	o.Iops.Set(&v)
}
// SetIopsNil sets the value for Iops to be an explicit nil
func (o *NewDatabaseInput) SetIopsNil() {
	o.Iops.Set(nil)
}

// UnsetIops ensures that no value is present for Iops, not even an explicit nil
func (o *NewDatabaseInput) UnsetIops() {
	o.Iops.Unset()
}

func (o NewDatabaseInput) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o NewDatabaseInput) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if !IsNil(o.OrgId) {
		toSerialize["orgId"] = o.OrgId
	}
	if o.ProjectId.IsSet() {
		toSerialize["projectId"] = o.ProjectId.Get()
	}
	if !IsNil(o.EnvId) {
		toSerialize["envId"] = o.EnvId
	}
	if !IsNil(o.EnvType) {
		toSerialize["envType"] = o.EnvType
	}
	toSerialize["name"] = o.Name
	toSerialize["title"] = o.Title
	toSerialize["integrationKindId"] = o.IntegrationKindId
	toSerialize["type"] = o.Type
	toSerialize["version"] = o.Version
	toSerialize["machineType"] = o.MachineType
	if o.StorageSize.IsSet() {
		toSerialize["storageSize"] = o.StorageSize.Get()
	}
	if o.Password.IsSet() {
		toSerialize["password"] = o.Password.Get()
	}
	if o.StorageAutoscaling.IsSet() {
		toSerialize["storageAutoscaling"] = o.StorageAutoscaling.Get()
	}
	if o.HighAvailability.IsSet() {
		toSerialize["highAvailability"] = o.HighAvailability.Get()
	}
	if o.Region.IsSet() {
		toSerialize["region"] = o.Region.Get()
	}
	if o.Zone.IsSet() {
		toSerialize["zone"] = o.Zone.Get()
	}
	if o.ResidedClusterId.IsSet() {
		toSerialize["residedClusterId"] = o.ResidedClusterId.Get()
	}
	if o.Iops.IsSet() {
		toSerialize["iops"] = o.Iops.Get()
	}
	return toSerialize, nil
}

func (o *NewDatabaseInput) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"name",
		"title",
		"integrationKindId",
		"type",
		"version",
		"machineType",
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err;
	}

	for _, requiredProperty := range(requiredProperties) {
		if _, exists := allProperties[requiredProperty]; !exists {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varNewDatabaseInput := _NewDatabaseInput{}

	decoder := json.NewDecoder(bytes.NewReader(data))
	decoder.DisallowUnknownFields()
	err = decoder.Decode(&varNewDatabaseInput)

	if err != nil {
		return err
	}

	*o = NewDatabaseInput(varNewDatabaseInput)

	return err
}

type NullableNewDatabaseInput struct {
	value *NewDatabaseInput
	isSet bool
}

func (v NullableNewDatabaseInput) Get() *NewDatabaseInput {
	return v.value
}

func (v *NullableNewDatabaseInput) Set(val *NewDatabaseInput) {
	v.value = val
	v.isSet = true
}

func (v NullableNewDatabaseInput) IsSet() bool {
	return v.isSet
}

func (v *NullableNewDatabaseInput) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableNewDatabaseInput(val *NewDatabaseInput) *NullableNewDatabaseInput {
	return &NullableNewDatabaseInput{value: val, isSet: true}
}

func (v NullableNewDatabaseInput) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableNewDatabaseInput) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


