/*
Wodby 2 Public API

Public REST API for customer SDKs and code integrations. GraphQL remains internal for the dashboard. This contract is the versioned public surface. 

API version: 1.0.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package client

import (
	"encoding/json"
	"time"
	"bytes"
	"fmt"
)

// checks if the Stack type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &Stack{}

// Stack struct for Stack
type Stack struct {
	Id int32 `json:"id"`
	Name string `json:"name"`
	Title string `json:"title"`
	Icon string `json:"icon"`
	Status string `json:"status"`
	Outdated bool `json:"outdated"`
	Public bool `json:"public"`
	RevId int32 `json:"revId"`
	DraftRevId NullableInt32 `json:"draftRevId,omitempty"`
	LatestRevNumber int32 `json:"latestRevNumber"`
	GitRepoId NullableInt32 `json:"gitRepoId,omitempty"`
	GitRepoRemoteId NullableString `json:"gitRepoRemoteId,omitempty"`
	GitRepoRef NullableString `json:"gitRepoRef,omitempty"`
	GitRepoRefType NullableString `json:"gitRepoRefType,omitempty"`
	OriginStackRevId NullableInt32 `json:"originStackRevId,omitempty"`
	OriginStackRevStackId NullableInt32 `json:"originStackRevStackId,omitempty"`
	OriginStackRevName NullableString `json:"originStackRevName,omitempty"`
	OriginStackRevNumber NullableInt32 `json:"originStackRevNumber,omitempty"`
	OriginStackRevVersion NullableString `json:"originStackRevVersion,omitempty"`
	OriginStackRevCreatedAt NullableTime `json:"originStackRevCreatedAt,omitempty"`
	OrgId int32 `json:"orgId"`
	Settings *StackSettings `json:"settings,omitempty"`
	CreatedAt time.Time `json:"createdAt"`
	UpdatedAt time.Time `json:"updatedAt"`
}

type _Stack Stack

// NewStack instantiates a new Stack object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewStack(id int32, name string, title string, icon string, status string, outdated bool, public bool, revId int32, latestRevNumber int32, orgId int32, createdAt time.Time, updatedAt time.Time) *Stack {
	this := Stack{}
	this.Id = id
	this.Name = name
	this.Title = title
	this.Icon = icon
	this.Status = status
	this.Outdated = outdated
	this.Public = public
	this.RevId = revId
	this.LatestRevNumber = latestRevNumber
	this.OrgId = orgId
	this.CreatedAt = createdAt
	this.UpdatedAt = updatedAt
	return &this
}

// NewStackWithDefaults instantiates a new Stack object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewStackWithDefaults() *Stack {
	this := Stack{}
	return &this
}

// GetId returns the Id field value
func (o *Stack) GetId() int32 {
	if o == nil {
		var ret int32
		return ret
	}

	return o.Id
}

// GetIdOk returns a tuple with the Id field value
// and a boolean to check if the value has been set.
func (o *Stack) GetIdOk() (*int32, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Id, true
}

// SetId sets field value
func (o *Stack) SetId(v int32) {
	o.Id = v
}

// GetName returns the Name field value
func (o *Stack) GetName() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Name
}

// GetNameOk returns a tuple with the Name field value
// and a boolean to check if the value has been set.
func (o *Stack) GetNameOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Name, true
}

// SetName sets field value
func (o *Stack) SetName(v string) {
	o.Name = v
}

// GetTitle returns the Title field value
func (o *Stack) GetTitle() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Title
}

// GetTitleOk returns a tuple with the Title field value
// and a boolean to check if the value has been set.
func (o *Stack) GetTitleOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Title, true
}

// SetTitle sets field value
func (o *Stack) SetTitle(v string) {
	o.Title = v
}

// GetIcon returns the Icon field value
func (o *Stack) GetIcon() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Icon
}

// GetIconOk returns a tuple with the Icon field value
// and a boolean to check if the value has been set.
func (o *Stack) GetIconOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Icon, true
}

// SetIcon sets field value
func (o *Stack) SetIcon(v string) {
	o.Icon = v
}

// GetStatus returns the Status field value
func (o *Stack) GetStatus() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Status
}

// GetStatusOk returns a tuple with the Status field value
// and a boolean to check if the value has been set.
func (o *Stack) GetStatusOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Status, true
}

// SetStatus sets field value
func (o *Stack) SetStatus(v string) {
	o.Status = v
}

// GetOutdated returns the Outdated field value
func (o *Stack) GetOutdated() bool {
	if o == nil {
		var ret bool
		return ret
	}

	return o.Outdated
}

// GetOutdatedOk returns a tuple with the Outdated field value
// and a boolean to check if the value has been set.
func (o *Stack) GetOutdatedOk() (*bool, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Outdated, true
}

// SetOutdated sets field value
func (o *Stack) SetOutdated(v bool) {
	o.Outdated = v
}

// GetPublic returns the Public field value
func (o *Stack) GetPublic() bool {
	if o == nil {
		var ret bool
		return ret
	}

	return o.Public
}

// GetPublicOk returns a tuple with the Public field value
// and a boolean to check if the value has been set.
func (o *Stack) GetPublicOk() (*bool, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Public, true
}

// SetPublic sets field value
func (o *Stack) SetPublic(v bool) {
	o.Public = v
}

// GetRevId returns the RevId field value
func (o *Stack) GetRevId() int32 {
	if o == nil {
		var ret int32
		return ret
	}

	return o.RevId
}

// GetRevIdOk returns a tuple with the RevId field value
// and a boolean to check if the value has been set.
func (o *Stack) GetRevIdOk() (*int32, bool) {
	if o == nil {
		return nil, false
	}
	return &o.RevId, true
}

// SetRevId sets field value
func (o *Stack) SetRevId(v int32) {
	o.RevId = v
}

// GetDraftRevId returns the DraftRevId field value if set, zero value otherwise (both if not set or set to explicit null).
func (o *Stack) GetDraftRevId() int32 {
	if o == nil || IsNil(o.DraftRevId.Get()) {
		var ret int32
		return ret
	}
	return *o.DraftRevId.Get()
}

// GetDraftRevIdOk returns a tuple with the DraftRevId field value if set, nil otherwise
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *Stack) GetDraftRevIdOk() (*int32, bool) {
	if o == nil {
		return nil, false
	}
	return o.DraftRevId.Get(), o.DraftRevId.IsSet()
}

// HasDraftRevId returns a boolean if a field has been set.
func (o *Stack) HasDraftRevId() bool {
	if o != nil && o.DraftRevId.IsSet() {
		return true
	}

	return false
}

// SetDraftRevId gets a reference to the given NullableInt32 and assigns it to the DraftRevId field.
func (o *Stack) SetDraftRevId(v int32) {
	o.DraftRevId.Set(&v)
}
// SetDraftRevIdNil sets the value for DraftRevId to be an explicit nil
func (o *Stack) SetDraftRevIdNil() {
	o.DraftRevId.Set(nil)
}

// UnsetDraftRevId ensures that no value is present for DraftRevId, not even an explicit nil
func (o *Stack) UnsetDraftRevId() {
	o.DraftRevId.Unset()
}

// GetLatestRevNumber returns the LatestRevNumber field value
func (o *Stack) GetLatestRevNumber() int32 {
	if o == nil {
		var ret int32
		return ret
	}

	return o.LatestRevNumber
}

// GetLatestRevNumberOk returns a tuple with the LatestRevNumber field value
// and a boolean to check if the value has been set.
func (o *Stack) GetLatestRevNumberOk() (*int32, bool) {
	if o == nil {
		return nil, false
	}
	return &o.LatestRevNumber, true
}

// SetLatestRevNumber sets field value
func (o *Stack) SetLatestRevNumber(v int32) {
	o.LatestRevNumber = v
}

// GetGitRepoId returns the GitRepoId field value if set, zero value otherwise (both if not set or set to explicit null).
func (o *Stack) GetGitRepoId() int32 {
	if o == nil || IsNil(o.GitRepoId.Get()) {
		var ret int32
		return ret
	}
	return *o.GitRepoId.Get()
}

// GetGitRepoIdOk returns a tuple with the GitRepoId field value if set, nil otherwise
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *Stack) GetGitRepoIdOk() (*int32, bool) {
	if o == nil {
		return nil, false
	}
	return o.GitRepoId.Get(), o.GitRepoId.IsSet()
}

// HasGitRepoId returns a boolean if a field has been set.
func (o *Stack) HasGitRepoId() bool {
	if o != nil && o.GitRepoId.IsSet() {
		return true
	}

	return false
}

// SetGitRepoId gets a reference to the given NullableInt32 and assigns it to the GitRepoId field.
func (o *Stack) SetGitRepoId(v int32) {
	o.GitRepoId.Set(&v)
}
// SetGitRepoIdNil sets the value for GitRepoId to be an explicit nil
func (o *Stack) SetGitRepoIdNil() {
	o.GitRepoId.Set(nil)
}

// UnsetGitRepoId ensures that no value is present for GitRepoId, not even an explicit nil
func (o *Stack) UnsetGitRepoId() {
	o.GitRepoId.Unset()
}

// GetGitRepoRemoteId returns the GitRepoRemoteId field value if set, zero value otherwise (both if not set or set to explicit null).
func (o *Stack) GetGitRepoRemoteId() string {
	if o == nil || IsNil(o.GitRepoRemoteId.Get()) {
		var ret string
		return ret
	}
	return *o.GitRepoRemoteId.Get()
}

// GetGitRepoRemoteIdOk returns a tuple with the GitRepoRemoteId field value if set, nil otherwise
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *Stack) GetGitRepoRemoteIdOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return o.GitRepoRemoteId.Get(), o.GitRepoRemoteId.IsSet()
}

// HasGitRepoRemoteId returns a boolean if a field has been set.
func (o *Stack) HasGitRepoRemoteId() bool {
	if o != nil && o.GitRepoRemoteId.IsSet() {
		return true
	}

	return false
}

// SetGitRepoRemoteId gets a reference to the given NullableString and assigns it to the GitRepoRemoteId field.
func (o *Stack) SetGitRepoRemoteId(v string) {
	o.GitRepoRemoteId.Set(&v)
}
// SetGitRepoRemoteIdNil sets the value for GitRepoRemoteId to be an explicit nil
func (o *Stack) SetGitRepoRemoteIdNil() {
	o.GitRepoRemoteId.Set(nil)
}

// UnsetGitRepoRemoteId ensures that no value is present for GitRepoRemoteId, not even an explicit nil
func (o *Stack) UnsetGitRepoRemoteId() {
	o.GitRepoRemoteId.Unset()
}

// GetGitRepoRef returns the GitRepoRef field value if set, zero value otherwise (both if not set or set to explicit null).
func (o *Stack) GetGitRepoRef() string {
	if o == nil || IsNil(o.GitRepoRef.Get()) {
		var ret string
		return ret
	}
	return *o.GitRepoRef.Get()
}

// GetGitRepoRefOk returns a tuple with the GitRepoRef field value if set, nil otherwise
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *Stack) GetGitRepoRefOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return o.GitRepoRef.Get(), o.GitRepoRef.IsSet()
}

// HasGitRepoRef returns a boolean if a field has been set.
func (o *Stack) HasGitRepoRef() bool {
	if o != nil && o.GitRepoRef.IsSet() {
		return true
	}

	return false
}

// SetGitRepoRef gets a reference to the given NullableString and assigns it to the GitRepoRef field.
func (o *Stack) SetGitRepoRef(v string) {
	o.GitRepoRef.Set(&v)
}
// SetGitRepoRefNil sets the value for GitRepoRef to be an explicit nil
func (o *Stack) SetGitRepoRefNil() {
	o.GitRepoRef.Set(nil)
}

// UnsetGitRepoRef ensures that no value is present for GitRepoRef, not even an explicit nil
func (o *Stack) UnsetGitRepoRef() {
	o.GitRepoRef.Unset()
}

// GetGitRepoRefType returns the GitRepoRefType field value if set, zero value otherwise (both if not set or set to explicit null).
func (o *Stack) GetGitRepoRefType() string {
	if o == nil || IsNil(o.GitRepoRefType.Get()) {
		var ret string
		return ret
	}
	return *o.GitRepoRefType.Get()
}

// GetGitRepoRefTypeOk returns a tuple with the GitRepoRefType field value if set, nil otherwise
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *Stack) GetGitRepoRefTypeOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return o.GitRepoRefType.Get(), o.GitRepoRefType.IsSet()
}

// HasGitRepoRefType returns a boolean if a field has been set.
func (o *Stack) HasGitRepoRefType() bool {
	if o != nil && o.GitRepoRefType.IsSet() {
		return true
	}

	return false
}

// SetGitRepoRefType gets a reference to the given NullableString and assigns it to the GitRepoRefType field.
func (o *Stack) SetGitRepoRefType(v string) {
	o.GitRepoRefType.Set(&v)
}
// SetGitRepoRefTypeNil sets the value for GitRepoRefType to be an explicit nil
func (o *Stack) SetGitRepoRefTypeNil() {
	o.GitRepoRefType.Set(nil)
}

// UnsetGitRepoRefType ensures that no value is present for GitRepoRefType, not even an explicit nil
func (o *Stack) UnsetGitRepoRefType() {
	o.GitRepoRefType.Unset()
}

// GetOriginStackRevId returns the OriginStackRevId field value if set, zero value otherwise (both if not set or set to explicit null).
func (o *Stack) GetOriginStackRevId() int32 {
	if o == nil || IsNil(o.OriginStackRevId.Get()) {
		var ret int32
		return ret
	}
	return *o.OriginStackRevId.Get()
}

// GetOriginStackRevIdOk returns a tuple with the OriginStackRevId field value if set, nil otherwise
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *Stack) GetOriginStackRevIdOk() (*int32, bool) {
	if o == nil {
		return nil, false
	}
	return o.OriginStackRevId.Get(), o.OriginStackRevId.IsSet()
}

// HasOriginStackRevId returns a boolean if a field has been set.
func (o *Stack) HasOriginStackRevId() bool {
	if o != nil && o.OriginStackRevId.IsSet() {
		return true
	}

	return false
}

// SetOriginStackRevId gets a reference to the given NullableInt32 and assigns it to the OriginStackRevId field.
func (o *Stack) SetOriginStackRevId(v int32) {
	o.OriginStackRevId.Set(&v)
}
// SetOriginStackRevIdNil sets the value for OriginStackRevId to be an explicit nil
func (o *Stack) SetOriginStackRevIdNil() {
	o.OriginStackRevId.Set(nil)
}

// UnsetOriginStackRevId ensures that no value is present for OriginStackRevId, not even an explicit nil
func (o *Stack) UnsetOriginStackRevId() {
	o.OriginStackRevId.Unset()
}

// GetOriginStackRevStackId returns the OriginStackRevStackId field value if set, zero value otherwise (both if not set or set to explicit null).
func (o *Stack) GetOriginStackRevStackId() int32 {
	if o == nil || IsNil(o.OriginStackRevStackId.Get()) {
		var ret int32
		return ret
	}
	return *o.OriginStackRevStackId.Get()
}

// GetOriginStackRevStackIdOk returns a tuple with the OriginStackRevStackId field value if set, nil otherwise
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *Stack) GetOriginStackRevStackIdOk() (*int32, bool) {
	if o == nil {
		return nil, false
	}
	return o.OriginStackRevStackId.Get(), o.OriginStackRevStackId.IsSet()
}

// HasOriginStackRevStackId returns a boolean if a field has been set.
func (o *Stack) HasOriginStackRevStackId() bool {
	if o != nil && o.OriginStackRevStackId.IsSet() {
		return true
	}

	return false
}

// SetOriginStackRevStackId gets a reference to the given NullableInt32 and assigns it to the OriginStackRevStackId field.
func (o *Stack) SetOriginStackRevStackId(v int32) {
	o.OriginStackRevStackId.Set(&v)
}
// SetOriginStackRevStackIdNil sets the value for OriginStackRevStackId to be an explicit nil
func (o *Stack) SetOriginStackRevStackIdNil() {
	o.OriginStackRevStackId.Set(nil)
}

// UnsetOriginStackRevStackId ensures that no value is present for OriginStackRevStackId, not even an explicit nil
func (o *Stack) UnsetOriginStackRevStackId() {
	o.OriginStackRevStackId.Unset()
}

// GetOriginStackRevName returns the OriginStackRevName field value if set, zero value otherwise (both if not set or set to explicit null).
func (o *Stack) GetOriginStackRevName() string {
	if o == nil || IsNil(o.OriginStackRevName.Get()) {
		var ret string
		return ret
	}
	return *o.OriginStackRevName.Get()
}

// GetOriginStackRevNameOk returns a tuple with the OriginStackRevName field value if set, nil otherwise
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *Stack) GetOriginStackRevNameOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return o.OriginStackRevName.Get(), o.OriginStackRevName.IsSet()
}

// HasOriginStackRevName returns a boolean if a field has been set.
func (o *Stack) HasOriginStackRevName() bool {
	if o != nil && o.OriginStackRevName.IsSet() {
		return true
	}

	return false
}

// SetOriginStackRevName gets a reference to the given NullableString and assigns it to the OriginStackRevName field.
func (o *Stack) SetOriginStackRevName(v string) {
	o.OriginStackRevName.Set(&v)
}
// SetOriginStackRevNameNil sets the value for OriginStackRevName to be an explicit nil
func (o *Stack) SetOriginStackRevNameNil() {
	o.OriginStackRevName.Set(nil)
}

// UnsetOriginStackRevName ensures that no value is present for OriginStackRevName, not even an explicit nil
func (o *Stack) UnsetOriginStackRevName() {
	o.OriginStackRevName.Unset()
}

// GetOriginStackRevNumber returns the OriginStackRevNumber field value if set, zero value otherwise (both if not set or set to explicit null).
func (o *Stack) GetOriginStackRevNumber() int32 {
	if o == nil || IsNil(o.OriginStackRevNumber.Get()) {
		var ret int32
		return ret
	}
	return *o.OriginStackRevNumber.Get()
}

// GetOriginStackRevNumberOk returns a tuple with the OriginStackRevNumber field value if set, nil otherwise
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *Stack) GetOriginStackRevNumberOk() (*int32, bool) {
	if o == nil {
		return nil, false
	}
	return o.OriginStackRevNumber.Get(), o.OriginStackRevNumber.IsSet()
}

// HasOriginStackRevNumber returns a boolean if a field has been set.
func (o *Stack) HasOriginStackRevNumber() bool {
	if o != nil && o.OriginStackRevNumber.IsSet() {
		return true
	}

	return false
}

// SetOriginStackRevNumber gets a reference to the given NullableInt32 and assigns it to the OriginStackRevNumber field.
func (o *Stack) SetOriginStackRevNumber(v int32) {
	o.OriginStackRevNumber.Set(&v)
}
// SetOriginStackRevNumberNil sets the value for OriginStackRevNumber to be an explicit nil
func (o *Stack) SetOriginStackRevNumberNil() {
	o.OriginStackRevNumber.Set(nil)
}

// UnsetOriginStackRevNumber ensures that no value is present for OriginStackRevNumber, not even an explicit nil
func (o *Stack) UnsetOriginStackRevNumber() {
	o.OriginStackRevNumber.Unset()
}

// GetOriginStackRevVersion returns the OriginStackRevVersion field value if set, zero value otherwise (both if not set or set to explicit null).
func (o *Stack) GetOriginStackRevVersion() string {
	if o == nil || IsNil(o.OriginStackRevVersion.Get()) {
		var ret string
		return ret
	}
	return *o.OriginStackRevVersion.Get()
}

// GetOriginStackRevVersionOk returns a tuple with the OriginStackRevVersion field value if set, nil otherwise
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *Stack) GetOriginStackRevVersionOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return o.OriginStackRevVersion.Get(), o.OriginStackRevVersion.IsSet()
}

// HasOriginStackRevVersion returns a boolean if a field has been set.
func (o *Stack) HasOriginStackRevVersion() bool {
	if o != nil && o.OriginStackRevVersion.IsSet() {
		return true
	}

	return false
}

// SetOriginStackRevVersion gets a reference to the given NullableString and assigns it to the OriginStackRevVersion field.
func (o *Stack) SetOriginStackRevVersion(v string) {
	o.OriginStackRevVersion.Set(&v)
}
// SetOriginStackRevVersionNil sets the value for OriginStackRevVersion to be an explicit nil
func (o *Stack) SetOriginStackRevVersionNil() {
	o.OriginStackRevVersion.Set(nil)
}

// UnsetOriginStackRevVersion ensures that no value is present for OriginStackRevVersion, not even an explicit nil
func (o *Stack) UnsetOriginStackRevVersion() {
	o.OriginStackRevVersion.Unset()
}

// GetOriginStackRevCreatedAt returns the OriginStackRevCreatedAt field value if set, zero value otherwise (both if not set or set to explicit null).
func (o *Stack) GetOriginStackRevCreatedAt() time.Time {
	if o == nil || IsNil(o.OriginStackRevCreatedAt.Get()) {
		var ret time.Time
		return ret
	}
	return *o.OriginStackRevCreatedAt.Get()
}

// GetOriginStackRevCreatedAtOk returns a tuple with the OriginStackRevCreatedAt field value if set, nil otherwise
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *Stack) GetOriginStackRevCreatedAtOk() (*time.Time, bool) {
	if o == nil {
		return nil, false
	}
	return o.OriginStackRevCreatedAt.Get(), o.OriginStackRevCreatedAt.IsSet()
}

// HasOriginStackRevCreatedAt returns a boolean if a field has been set.
func (o *Stack) HasOriginStackRevCreatedAt() bool {
	if o != nil && o.OriginStackRevCreatedAt.IsSet() {
		return true
	}

	return false
}

// SetOriginStackRevCreatedAt gets a reference to the given NullableTime and assigns it to the OriginStackRevCreatedAt field.
func (o *Stack) SetOriginStackRevCreatedAt(v time.Time) {
	o.OriginStackRevCreatedAt.Set(&v)
}
// SetOriginStackRevCreatedAtNil sets the value for OriginStackRevCreatedAt to be an explicit nil
func (o *Stack) SetOriginStackRevCreatedAtNil() {
	o.OriginStackRevCreatedAt.Set(nil)
}

// UnsetOriginStackRevCreatedAt ensures that no value is present for OriginStackRevCreatedAt, not even an explicit nil
func (o *Stack) UnsetOriginStackRevCreatedAt() {
	o.OriginStackRevCreatedAt.Unset()
}

// GetOrgId returns the OrgId field value
func (o *Stack) GetOrgId() int32 {
	if o == nil {
		var ret int32
		return ret
	}

	return o.OrgId
}

// GetOrgIdOk returns a tuple with the OrgId field value
// and a boolean to check if the value has been set.
func (o *Stack) GetOrgIdOk() (*int32, bool) {
	if o == nil {
		return nil, false
	}
	return &o.OrgId, true
}

// SetOrgId sets field value
func (o *Stack) SetOrgId(v int32) {
	o.OrgId = v
}

// GetSettings returns the Settings field value if set, zero value otherwise.
func (o *Stack) GetSettings() StackSettings {
	if o == nil || IsNil(o.Settings) {
		var ret StackSettings
		return ret
	}
	return *o.Settings
}

// GetSettingsOk returns a tuple with the Settings field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *Stack) GetSettingsOk() (*StackSettings, bool) {
	if o == nil || IsNil(o.Settings) {
		return nil, false
	}
	return o.Settings, true
}

// HasSettings returns a boolean if a field has been set.
func (o *Stack) HasSettings() bool {
	if o != nil && !IsNil(o.Settings) {
		return true
	}

	return false
}

// SetSettings gets a reference to the given StackSettings and assigns it to the Settings field.
func (o *Stack) SetSettings(v StackSettings) {
	o.Settings = &v
}

// GetCreatedAt returns the CreatedAt field value
func (o *Stack) GetCreatedAt() time.Time {
	if o == nil {
		var ret time.Time
		return ret
	}

	return o.CreatedAt
}

// GetCreatedAtOk returns a tuple with the CreatedAt field value
// and a boolean to check if the value has been set.
func (o *Stack) GetCreatedAtOk() (*time.Time, bool) {
	if o == nil {
		return nil, false
	}
	return &o.CreatedAt, true
}

// SetCreatedAt sets field value
func (o *Stack) SetCreatedAt(v time.Time) {
	o.CreatedAt = v
}

// GetUpdatedAt returns the UpdatedAt field value
func (o *Stack) GetUpdatedAt() time.Time {
	if o == nil {
		var ret time.Time
		return ret
	}

	return o.UpdatedAt
}

// GetUpdatedAtOk returns a tuple with the UpdatedAt field value
// and a boolean to check if the value has been set.
func (o *Stack) GetUpdatedAtOk() (*time.Time, bool) {
	if o == nil {
		return nil, false
	}
	return &o.UpdatedAt, true
}

// SetUpdatedAt sets field value
func (o *Stack) SetUpdatedAt(v time.Time) {
	o.UpdatedAt = v
}

func (o Stack) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o Stack) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["id"] = o.Id
	toSerialize["name"] = o.Name
	toSerialize["title"] = o.Title
	toSerialize["icon"] = o.Icon
	toSerialize["status"] = o.Status
	toSerialize["outdated"] = o.Outdated
	toSerialize["public"] = o.Public
	toSerialize["revId"] = o.RevId
	if o.DraftRevId.IsSet() {
		toSerialize["draftRevId"] = o.DraftRevId.Get()
	}
	toSerialize["latestRevNumber"] = o.LatestRevNumber
	if o.GitRepoId.IsSet() {
		toSerialize["gitRepoId"] = o.GitRepoId.Get()
	}
	if o.GitRepoRemoteId.IsSet() {
		toSerialize["gitRepoRemoteId"] = o.GitRepoRemoteId.Get()
	}
	if o.GitRepoRef.IsSet() {
		toSerialize["gitRepoRef"] = o.GitRepoRef.Get()
	}
	if o.GitRepoRefType.IsSet() {
		toSerialize["gitRepoRefType"] = o.GitRepoRefType.Get()
	}
	if o.OriginStackRevId.IsSet() {
		toSerialize["originStackRevId"] = o.OriginStackRevId.Get()
	}
	if o.OriginStackRevStackId.IsSet() {
		toSerialize["originStackRevStackId"] = o.OriginStackRevStackId.Get()
	}
	if o.OriginStackRevName.IsSet() {
		toSerialize["originStackRevName"] = o.OriginStackRevName.Get()
	}
	if o.OriginStackRevNumber.IsSet() {
		toSerialize["originStackRevNumber"] = o.OriginStackRevNumber.Get()
	}
	if o.OriginStackRevVersion.IsSet() {
		toSerialize["originStackRevVersion"] = o.OriginStackRevVersion.Get()
	}
	if o.OriginStackRevCreatedAt.IsSet() {
		toSerialize["originStackRevCreatedAt"] = o.OriginStackRevCreatedAt.Get()
	}
	toSerialize["orgId"] = o.OrgId
	if !IsNil(o.Settings) {
		toSerialize["settings"] = o.Settings
	}
	toSerialize["createdAt"] = o.CreatedAt
	toSerialize["updatedAt"] = o.UpdatedAt
	return toSerialize, nil
}

func (o *Stack) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"id",
		"name",
		"title",
		"icon",
		"status",
		"outdated",
		"public",
		"revId",
		"latestRevNumber",
		"orgId",
		"createdAt",
		"updatedAt",
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err;
	}

	for _, requiredProperty := range(requiredProperties) {
		if _, exists := allProperties[requiredProperty]; !exists {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varStack := _Stack{}

	decoder := json.NewDecoder(bytes.NewReader(data))
	decoder.DisallowUnknownFields()
	err = decoder.Decode(&varStack)

	if err != nil {
		return err
	}

	*o = Stack(varStack)

	return err
}

type NullableStack struct {
	value *Stack
	isSet bool
}

func (v NullableStack) Get() *Stack {
	return v.value
}

func (v *NullableStack) Set(val *Stack) {
	v.value = val
	v.isSet = true
}

func (v NullableStack) IsSet() bool {
	return v.isSet
}

func (v *NullableStack) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableStack(val *Stack) *NullableStack {
	return &NullableStack{value: val, isSet: true}
}

func (v NullableStack) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableStack) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


