/*
Wodby 2 Public API

Public REST API for customer SDKs and code integrations. GraphQL remains internal for the dashboard. This contract is the versioned public surface. 

API version: 1.0.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package client

import (
	"encoding/json"
)

// checks if the SetNullableStringValueInput type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &SetNullableStringValueInput{}

// SetNullableStringValueInput struct for SetNullableStringValueInput
type SetNullableStringValueInput struct {
	Value NullableString `json:"value,omitempty"`
}

// NewSetNullableStringValueInput instantiates a new SetNullableStringValueInput object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewSetNullableStringValueInput() *SetNullableStringValueInput {
	this := SetNullableStringValueInput{}
	return &this
}

// NewSetNullableStringValueInputWithDefaults instantiates a new SetNullableStringValueInput object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewSetNullableStringValueInputWithDefaults() *SetNullableStringValueInput {
	this := SetNullableStringValueInput{}
	return &this
}

// GetValue returns the Value field value if set, zero value otherwise (both if not set or set to explicit null).
func (o *SetNullableStringValueInput) GetValue() string {
	if o == nil || IsNil(o.Value.Get()) {
		var ret string
		return ret
	}
	return *o.Value.Get()
}

// GetValueOk returns a tuple with the Value field value if set, nil otherwise
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *SetNullableStringValueInput) GetValueOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return o.Value.Get(), o.Value.IsSet()
}

// HasValue returns a boolean if a field has been set.
func (o *SetNullableStringValueInput) HasValue() bool {
	if o != nil && o.Value.IsSet() {
		return true
	}

	return false
}

// SetValue gets a reference to the given NullableString and assigns it to the Value field.
func (o *SetNullableStringValueInput) SetValue(v string) {
	o.Value.Set(&v)
}
// SetValueNil sets the value for Value to be an explicit nil
func (o *SetNullableStringValueInput) SetValueNil() {
	o.Value.Set(nil)
}

// UnsetValue ensures that no value is present for Value, not even an explicit nil
func (o *SetNullableStringValueInput) UnsetValue() {
	o.Value.Unset()
}

func (o SetNullableStringValueInput) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o SetNullableStringValueInput) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if o.Value.IsSet() {
		toSerialize["value"] = o.Value.Get()
	}
	return toSerialize, nil
}

type NullableSetNullableStringValueInput struct {
	value *SetNullableStringValueInput
	isSet bool
}

func (v NullableSetNullableStringValueInput) Get() *SetNullableStringValueInput {
	return v.value
}

func (v *NullableSetNullableStringValueInput) Set(val *SetNullableStringValueInput) {
	v.value = val
	v.isSet = true
}

func (v NullableSetNullableStringValueInput) IsSet() bool {
	return v.isSet
}

func (v *NullableSetNullableStringValueInput) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableSetNullableStringValueInput(val *SetNullableStringValueInput) *NullableSetNullableStringValueInput {
	return &NullableSetNullableStringValueInput{value: val, isSet: true}
}

func (v NullableSetNullableStringValueInput) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableSetNullableStringValueInput) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


