/*
Wodby 2.0 Public API

Public REST API for customer SDKs and code integrations. GraphQL remains internal for the dashboard. This contract is the versioned public surface. 

API version: 1.0.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package client

import (
	"encoding/json"
	"bytes"
	"fmt"
)

// checks if the AppDeploymentsResponse type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &AppDeploymentsResponse{}

// AppDeploymentsResponse struct for AppDeploymentsResponse
type AppDeploymentsResponse struct {
	Items []AppDeployment `json:"items"`
	TotalCount int32 `json:"totalCount"`
	NextPage NullableInt32 `json:"nextPage,omitempty"`
}

type _AppDeploymentsResponse AppDeploymentsResponse

// NewAppDeploymentsResponse instantiates a new AppDeploymentsResponse object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewAppDeploymentsResponse(items []AppDeployment, totalCount int32) *AppDeploymentsResponse {
	this := AppDeploymentsResponse{}
	this.Items = items
	this.TotalCount = totalCount
	return &this
}

// NewAppDeploymentsResponseWithDefaults instantiates a new AppDeploymentsResponse object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewAppDeploymentsResponseWithDefaults() *AppDeploymentsResponse {
	this := AppDeploymentsResponse{}
	return &this
}

// GetItems returns the Items field value
func (o *AppDeploymentsResponse) GetItems() []AppDeployment {
	if o == nil {
		var ret []AppDeployment
		return ret
	}

	return o.Items
}

// GetItemsOk returns a tuple with the Items field value
// and a boolean to check if the value has been set.
func (o *AppDeploymentsResponse) GetItemsOk() ([]AppDeployment, bool) {
	if o == nil {
		return nil, false
	}
	return o.Items, true
}

// SetItems sets field value
func (o *AppDeploymentsResponse) SetItems(v []AppDeployment) {
	o.Items = v
}

// GetTotalCount returns the TotalCount field value
func (o *AppDeploymentsResponse) GetTotalCount() int32 {
	if o == nil {
		var ret int32
		return ret
	}

	return o.TotalCount
}

// GetTotalCountOk returns a tuple with the TotalCount field value
// and a boolean to check if the value has been set.
func (o *AppDeploymentsResponse) GetTotalCountOk() (*int32, bool) {
	if o == nil {
		return nil, false
	}
	return &o.TotalCount, true
}

// SetTotalCount sets field value
func (o *AppDeploymentsResponse) SetTotalCount(v int32) {
	o.TotalCount = v
}

// GetNextPage returns the NextPage field value if set, zero value otherwise (both if not set or set to explicit null).
func (o *AppDeploymentsResponse) GetNextPage() int32 {
	if o == nil || IsNil(o.NextPage.Get()) {
		var ret int32
		return ret
	}
	return *o.NextPage.Get()
}

// GetNextPageOk returns a tuple with the NextPage field value if set, nil otherwise
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *AppDeploymentsResponse) GetNextPageOk() (*int32, bool) {
	if o == nil {
		return nil, false
	}
	return o.NextPage.Get(), o.NextPage.IsSet()
}

// HasNextPage returns a boolean if a field has been set.
func (o *AppDeploymentsResponse) HasNextPage() bool {
	if o != nil && o.NextPage.IsSet() {
		return true
	}

	return false
}

// SetNextPage gets a reference to the given NullableInt32 and assigns it to the NextPage field.
func (o *AppDeploymentsResponse) SetNextPage(v int32) {
	o.NextPage.Set(&v)
}
// SetNextPageNil sets the value for NextPage to be an explicit nil
func (o *AppDeploymentsResponse) SetNextPageNil() {
	o.NextPage.Set(nil)
}

// UnsetNextPage ensures that no value is present for NextPage, not even an explicit nil
func (o *AppDeploymentsResponse) UnsetNextPage() {
	o.NextPage.Unset()
}

func (o AppDeploymentsResponse) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o AppDeploymentsResponse) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["items"] = o.Items
	toSerialize["totalCount"] = o.TotalCount
	if o.NextPage.IsSet() {
		toSerialize["nextPage"] = o.NextPage.Get()
	}
	return toSerialize, nil
}

func (o *AppDeploymentsResponse) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"items",
		"totalCount",
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err;
	}

	for _, requiredProperty := range(requiredProperties) {
		if _, exists := allProperties[requiredProperty]; !exists {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varAppDeploymentsResponse := _AppDeploymentsResponse{}

	decoder := json.NewDecoder(bytes.NewReader(data))
	decoder.DisallowUnknownFields()
	err = decoder.Decode(&varAppDeploymentsResponse)

	if err != nil {
		return err
	}

	*o = AppDeploymentsResponse(varAppDeploymentsResponse)

	return err
}

type NullableAppDeploymentsResponse struct {
	value *AppDeploymentsResponse
	isSet bool
}

func (v NullableAppDeploymentsResponse) Get() *AppDeploymentsResponse {
	return v.value
}

func (v *NullableAppDeploymentsResponse) Set(val *AppDeploymentsResponse) {
	v.value = val
	v.isSet = true
}

func (v NullableAppDeploymentsResponse) IsSet() bool {
	return v.isSet
}

func (v *NullableAppDeploymentsResponse) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableAppDeploymentsResponse(val *AppDeploymentsResponse) *NullableAppDeploymentsResponse {
	return &NullableAppDeploymentsResponse{value: val, isSet: true}
}

func (v NullableAppDeploymentsResponse) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableAppDeploymentsResponse) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


