/*
Wodby 2 Public API

Public REST API for customer SDKs and code integrations. GraphQL remains internal for the dashboard. This contract is the versioned public surface. 

API version: 1.0.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package client

import (
	"encoding/json"
	"bytes"
	"fmt"
)

// checks if the UpdateBackupPresetInput type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &UpdateBackupPresetInput{}

// UpdateBackupPresetInput struct for UpdateBackupPresetInput
type UpdateBackupPresetInput struct {
	// Use 0 for Wodby Blob Storage. Enabling the preset requires a paid subscription.
	IntegrationId int32 `json:"integrationId"`
	// Must be empty for Wodby Blob Storage.
	Bucket string `json:"bucket"`
	StorageClass NullableString `json:"storageClass,omitempty"`
	Options []BackupOption `json:"options,omitempty"`
	Disabled bool `json:"disabled"`
	Override bool `json:"override"`
	Auto bool `json:"auto"`
	Crontab NullableString `json:"crontab,omitempty"`
	TimeWindow *AutomationTimeWindowInput `json:"timeWindow,omitempty"`
	Duration NullableInt32 `json:"duration,omitempty"`
}

type _UpdateBackupPresetInput UpdateBackupPresetInput

// NewUpdateBackupPresetInput instantiates a new UpdateBackupPresetInput object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewUpdateBackupPresetInput(integrationId int32, bucket string, disabled bool, override bool, auto bool) *UpdateBackupPresetInput {
	this := UpdateBackupPresetInput{}
	this.IntegrationId = integrationId
	this.Bucket = bucket
	this.Disabled = disabled
	this.Override = override
	this.Auto = auto
	return &this
}

// NewUpdateBackupPresetInputWithDefaults instantiates a new UpdateBackupPresetInput object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewUpdateBackupPresetInputWithDefaults() *UpdateBackupPresetInput {
	this := UpdateBackupPresetInput{}
	return &this
}

// GetIntegrationId returns the IntegrationId field value
func (o *UpdateBackupPresetInput) GetIntegrationId() int32 {
	if o == nil {
		var ret int32
		return ret
	}

	return o.IntegrationId
}

// GetIntegrationIdOk returns a tuple with the IntegrationId field value
// and a boolean to check if the value has been set.
func (o *UpdateBackupPresetInput) GetIntegrationIdOk() (*int32, bool) {
	if o == nil {
		return nil, false
	}
	return &o.IntegrationId, true
}

// SetIntegrationId sets field value
func (o *UpdateBackupPresetInput) SetIntegrationId(v int32) {
	o.IntegrationId = v
}

// GetBucket returns the Bucket field value
func (o *UpdateBackupPresetInput) GetBucket() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Bucket
}

// GetBucketOk returns a tuple with the Bucket field value
// and a boolean to check if the value has been set.
func (o *UpdateBackupPresetInput) GetBucketOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Bucket, true
}

// SetBucket sets field value
func (o *UpdateBackupPresetInput) SetBucket(v string) {
	o.Bucket = v
}

// GetStorageClass returns the StorageClass field value if set, zero value otherwise (both if not set or set to explicit null).
func (o *UpdateBackupPresetInput) GetStorageClass() string {
	if o == nil || IsNil(o.StorageClass.Get()) {
		var ret string
		return ret
	}
	return *o.StorageClass.Get()
}

// GetStorageClassOk returns a tuple with the StorageClass field value if set, nil otherwise
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *UpdateBackupPresetInput) GetStorageClassOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return o.StorageClass.Get(), o.StorageClass.IsSet()
}

// HasStorageClass returns a boolean if a field has been set.
func (o *UpdateBackupPresetInput) HasStorageClass() bool {
	if o != nil && o.StorageClass.IsSet() {
		return true
	}

	return false
}

// SetStorageClass gets a reference to the given NullableString and assigns it to the StorageClass field.
func (o *UpdateBackupPresetInput) SetStorageClass(v string) {
	o.StorageClass.Set(&v)
}
// SetStorageClassNil sets the value for StorageClass to be an explicit nil
func (o *UpdateBackupPresetInput) SetStorageClassNil() {
	o.StorageClass.Set(nil)
}

// UnsetStorageClass ensures that no value is present for StorageClass, not even an explicit nil
func (o *UpdateBackupPresetInput) UnsetStorageClass() {
	o.StorageClass.Unset()
}

// GetOptions returns the Options field value if set, zero value otherwise (both if not set or set to explicit null).
func (o *UpdateBackupPresetInput) GetOptions() []BackupOption {
	if o == nil {
		var ret []BackupOption
		return ret
	}
	return o.Options
}

// GetOptionsOk returns a tuple with the Options field value if set, nil otherwise
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *UpdateBackupPresetInput) GetOptionsOk() ([]BackupOption, bool) {
	if o == nil || IsNil(o.Options) {
		return nil, false
	}
	return o.Options, true
}

// HasOptions returns a boolean if a field has been set.
func (o *UpdateBackupPresetInput) HasOptions() bool {
	if o != nil && !IsNil(o.Options) {
		return true
	}

	return false
}

// SetOptions gets a reference to the given []BackupOption and assigns it to the Options field.
func (o *UpdateBackupPresetInput) SetOptions(v []BackupOption) {
	o.Options = v
}

// GetDisabled returns the Disabled field value
func (o *UpdateBackupPresetInput) GetDisabled() bool {
	if o == nil {
		var ret bool
		return ret
	}

	return o.Disabled
}

// GetDisabledOk returns a tuple with the Disabled field value
// and a boolean to check if the value has been set.
func (o *UpdateBackupPresetInput) GetDisabledOk() (*bool, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Disabled, true
}

// SetDisabled sets field value
func (o *UpdateBackupPresetInput) SetDisabled(v bool) {
	o.Disabled = v
}

// GetOverride returns the Override field value
func (o *UpdateBackupPresetInput) GetOverride() bool {
	if o == nil {
		var ret bool
		return ret
	}

	return o.Override
}

// GetOverrideOk returns a tuple with the Override field value
// and a boolean to check if the value has been set.
func (o *UpdateBackupPresetInput) GetOverrideOk() (*bool, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Override, true
}

// SetOverride sets field value
func (o *UpdateBackupPresetInput) SetOverride(v bool) {
	o.Override = v
}

// GetAuto returns the Auto field value
func (o *UpdateBackupPresetInput) GetAuto() bool {
	if o == nil {
		var ret bool
		return ret
	}

	return o.Auto
}

// GetAutoOk returns a tuple with the Auto field value
// and a boolean to check if the value has been set.
func (o *UpdateBackupPresetInput) GetAutoOk() (*bool, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Auto, true
}

// SetAuto sets field value
func (o *UpdateBackupPresetInput) SetAuto(v bool) {
	o.Auto = v
}

// GetCrontab returns the Crontab field value if set, zero value otherwise (both if not set or set to explicit null).
func (o *UpdateBackupPresetInput) GetCrontab() string {
	if o == nil || IsNil(o.Crontab.Get()) {
		var ret string
		return ret
	}
	return *o.Crontab.Get()
}

// GetCrontabOk returns a tuple with the Crontab field value if set, nil otherwise
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *UpdateBackupPresetInput) GetCrontabOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return o.Crontab.Get(), o.Crontab.IsSet()
}

// HasCrontab returns a boolean if a field has been set.
func (o *UpdateBackupPresetInput) HasCrontab() bool {
	if o != nil && o.Crontab.IsSet() {
		return true
	}

	return false
}

// SetCrontab gets a reference to the given NullableString and assigns it to the Crontab field.
func (o *UpdateBackupPresetInput) SetCrontab(v string) {
	o.Crontab.Set(&v)
}
// SetCrontabNil sets the value for Crontab to be an explicit nil
func (o *UpdateBackupPresetInput) SetCrontabNil() {
	o.Crontab.Set(nil)
}

// UnsetCrontab ensures that no value is present for Crontab, not even an explicit nil
func (o *UpdateBackupPresetInput) UnsetCrontab() {
	o.Crontab.Unset()
}

// GetTimeWindow returns the TimeWindow field value if set, zero value otherwise.
func (o *UpdateBackupPresetInput) GetTimeWindow() AutomationTimeWindowInput {
	if o == nil || IsNil(o.TimeWindow) {
		var ret AutomationTimeWindowInput
		return ret
	}
	return *o.TimeWindow
}

// GetTimeWindowOk returns a tuple with the TimeWindow field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *UpdateBackupPresetInput) GetTimeWindowOk() (*AutomationTimeWindowInput, bool) {
	if o == nil || IsNil(o.TimeWindow) {
		return nil, false
	}
	return o.TimeWindow, true
}

// HasTimeWindow returns a boolean if a field has been set.
func (o *UpdateBackupPresetInput) HasTimeWindow() bool {
	if o != nil && !IsNil(o.TimeWindow) {
		return true
	}

	return false
}

// SetTimeWindow gets a reference to the given AutomationTimeWindowInput and assigns it to the TimeWindow field.
func (o *UpdateBackupPresetInput) SetTimeWindow(v AutomationTimeWindowInput) {
	o.TimeWindow = &v
}

// GetDuration returns the Duration field value if set, zero value otherwise (both if not set or set to explicit null).
func (o *UpdateBackupPresetInput) GetDuration() int32 {
	if o == nil || IsNil(o.Duration.Get()) {
		var ret int32
		return ret
	}
	return *o.Duration.Get()
}

// GetDurationOk returns a tuple with the Duration field value if set, nil otherwise
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *UpdateBackupPresetInput) GetDurationOk() (*int32, bool) {
	if o == nil {
		return nil, false
	}
	return o.Duration.Get(), o.Duration.IsSet()
}

// HasDuration returns a boolean if a field has been set.
func (o *UpdateBackupPresetInput) HasDuration() bool {
	if o != nil && o.Duration.IsSet() {
		return true
	}

	return false
}

// SetDuration gets a reference to the given NullableInt32 and assigns it to the Duration field.
func (o *UpdateBackupPresetInput) SetDuration(v int32) {
	o.Duration.Set(&v)
}
// SetDurationNil sets the value for Duration to be an explicit nil
func (o *UpdateBackupPresetInput) SetDurationNil() {
	o.Duration.Set(nil)
}

// UnsetDuration ensures that no value is present for Duration, not even an explicit nil
func (o *UpdateBackupPresetInput) UnsetDuration() {
	o.Duration.Unset()
}

func (o UpdateBackupPresetInput) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o UpdateBackupPresetInput) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["integrationId"] = o.IntegrationId
	toSerialize["bucket"] = o.Bucket
	if o.StorageClass.IsSet() {
		toSerialize["storageClass"] = o.StorageClass.Get()
	}
	if o.Options != nil {
		toSerialize["options"] = o.Options
	}
	toSerialize["disabled"] = o.Disabled
	toSerialize["override"] = o.Override
	toSerialize["auto"] = o.Auto
	if o.Crontab.IsSet() {
		toSerialize["crontab"] = o.Crontab.Get()
	}
	if !IsNil(o.TimeWindow) {
		toSerialize["timeWindow"] = o.TimeWindow
	}
	if o.Duration.IsSet() {
		toSerialize["duration"] = o.Duration.Get()
	}
	return toSerialize, nil
}

func (o *UpdateBackupPresetInput) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"integrationId",
		"bucket",
		"disabled",
		"override",
		"auto",
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err;
	}

	for _, requiredProperty := range(requiredProperties) {
		if _, exists := allProperties[requiredProperty]; !exists {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varUpdateBackupPresetInput := _UpdateBackupPresetInput{}

	decoder := json.NewDecoder(bytes.NewReader(data))
	decoder.DisallowUnknownFields()
	err = decoder.Decode(&varUpdateBackupPresetInput)

	if err != nil {
		return err
	}

	*o = UpdateBackupPresetInput(varUpdateBackupPresetInput)

	return err
}

type NullableUpdateBackupPresetInput struct {
	value *UpdateBackupPresetInput
	isSet bool
}

func (v NullableUpdateBackupPresetInput) Get() *UpdateBackupPresetInput {
	return v.value
}

func (v *NullableUpdateBackupPresetInput) Set(val *UpdateBackupPresetInput) {
	v.value = val
	v.isSet = true
}

func (v NullableUpdateBackupPresetInput) IsSet() bool {
	return v.isSet
}

func (v *NullableUpdateBackupPresetInput) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableUpdateBackupPresetInput(val *UpdateBackupPresetInput) *NullableUpdateBackupPresetInput {
	return &NullableUpdateBackupPresetInput{value: val, isSet: true}
}

func (v NullableUpdateBackupPresetInput) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableUpdateBackupPresetInput) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


