/*
Wodby 2 Public API

Public REST API for customer SDKs and code integrations. GraphQL remains internal for the dashboard. This contract is the versioned public surface. 

API version: 1.0.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package client

import (
	"encoding/json"
	"bytes"
	"fmt"
)

// checks if the CreateAppServiceInput type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &CreateAppServiceInput{}

// CreateAppServiceInput struct for CreateAppServiceInput
type CreateAppServiceInput struct {
	Id int32 `json:"id"`
	Disabled bool `json:"disabled"`
	Version NullableString `json:"version,omitempty"`
	BuildSource *BuildSourceInput `json:"buildSource,omitempty"`
	Imports []ImportInput `json:"imports,omitempty"`
	Volumes []VolumeSizeInput `json:"volumes,omitempty"`
	Integrations []AppServiceIntegrationInput `json:"integrations,omitempty"`
	Settings []AppServiceSettingInput `json:"settings,omitempty"`
	Database *AppServiceDatabaseInput `json:"database,omitempty"`
	Resources *ResourcesInput `json:"resources,omitempty"`
	Scalability *ScalabilityInput `json:"scalability,omitempty"`
}

type _CreateAppServiceInput CreateAppServiceInput

// NewCreateAppServiceInput instantiates a new CreateAppServiceInput object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewCreateAppServiceInput(id int32, disabled bool) *CreateAppServiceInput {
	this := CreateAppServiceInput{}
	this.Id = id
	this.Disabled = disabled
	return &this
}

// NewCreateAppServiceInputWithDefaults instantiates a new CreateAppServiceInput object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewCreateAppServiceInputWithDefaults() *CreateAppServiceInput {
	this := CreateAppServiceInput{}
	return &this
}

// GetId returns the Id field value
func (o *CreateAppServiceInput) GetId() int32 {
	if o == nil {
		var ret int32
		return ret
	}

	return o.Id
}

// GetIdOk returns a tuple with the Id field value
// and a boolean to check if the value has been set.
func (o *CreateAppServiceInput) GetIdOk() (*int32, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Id, true
}

// SetId sets field value
func (o *CreateAppServiceInput) SetId(v int32) {
	o.Id = v
}

// GetDisabled returns the Disabled field value
func (o *CreateAppServiceInput) GetDisabled() bool {
	if o == nil {
		var ret bool
		return ret
	}

	return o.Disabled
}

// GetDisabledOk returns a tuple with the Disabled field value
// and a boolean to check if the value has been set.
func (o *CreateAppServiceInput) GetDisabledOk() (*bool, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Disabled, true
}

// SetDisabled sets field value
func (o *CreateAppServiceInput) SetDisabled(v bool) {
	o.Disabled = v
}

// GetVersion returns the Version field value if set, zero value otherwise (both if not set or set to explicit null).
func (o *CreateAppServiceInput) GetVersion() string {
	if o == nil || IsNil(o.Version.Get()) {
		var ret string
		return ret
	}
	return *o.Version.Get()
}

// GetVersionOk returns a tuple with the Version field value if set, nil otherwise
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *CreateAppServiceInput) GetVersionOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return o.Version.Get(), o.Version.IsSet()
}

// HasVersion returns a boolean if a field has been set.
func (o *CreateAppServiceInput) HasVersion() bool {
	if o != nil && o.Version.IsSet() {
		return true
	}

	return false
}

// SetVersion gets a reference to the given NullableString and assigns it to the Version field.
func (o *CreateAppServiceInput) SetVersion(v string) {
	o.Version.Set(&v)
}
// SetVersionNil sets the value for Version to be an explicit nil
func (o *CreateAppServiceInput) SetVersionNil() {
	o.Version.Set(nil)
}

// UnsetVersion ensures that no value is present for Version, not even an explicit nil
func (o *CreateAppServiceInput) UnsetVersion() {
	o.Version.Unset()
}

// GetBuildSource returns the BuildSource field value if set, zero value otherwise.
func (o *CreateAppServiceInput) GetBuildSource() BuildSourceInput {
	if o == nil || IsNil(o.BuildSource) {
		var ret BuildSourceInput
		return ret
	}
	return *o.BuildSource
}

// GetBuildSourceOk returns a tuple with the BuildSource field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *CreateAppServiceInput) GetBuildSourceOk() (*BuildSourceInput, bool) {
	if o == nil || IsNil(o.BuildSource) {
		return nil, false
	}
	return o.BuildSource, true
}

// HasBuildSource returns a boolean if a field has been set.
func (o *CreateAppServiceInput) HasBuildSource() bool {
	if o != nil && !IsNil(o.BuildSource) {
		return true
	}

	return false
}

// SetBuildSource gets a reference to the given BuildSourceInput and assigns it to the BuildSource field.
func (o *CreateAppServiceInput) SetBuildSource(v BuildSourceInput) {
	o.BuildSource = &v
}

// GetImports returns the Imports field value if set, zero value otherwise.
func (o *CreateAppServiceInput) GetImports() []ImportInput {
	if o == nil || IsNil(o.Imports) {
		var ret []ImportInput
		return ret
	}
	return o.Imports
}

// GetImportsOk returns a tuple with the Imports field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *CreateAppServiceInput) GetImportsOk() ([]ImportInput, bool) {
	if o == nil || IsNil(o.Imports) {
		return nil, false
	}
	return o.Imports, true
}

// HasImports returns a boolean if a field has been set.
func (o *CreateAppServiceInput) HasImports() bool {
	if o != nil && !IsNil(o.Imports) {
		return true
	}

	return false
}

// SetImports gets a reference to the given []ImportInput and assigns it to the Imports field.
func (o *CreateAppServiceInput) SetImports(v []ImportInput) {
	o.Imports = v
}

// GetVolumes returns the Volumes field value if set, zero value otherwise.
func (o *CreateAppServiceInput) GetVolumes() []VolumeSizeInput {
	if o == nil || IsNil(o.Volumes) {
		var ret []VolumeSizeInput
		return ret
	}
	return o.Volumes
}

// GetVolumesOk returns a tuple with the Volumes field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *CreateAppServiceInput) GetVolumesOk() ([]VolumeSizeInput, bool) {
	if o == nil || IsNil(o.Volumes) {
		return nil, false
	}
	return o.Volumes, true
}

// HasVolumes returns a boolean if a field has been set.
func (o *CreateAppServiceInput) HasVolumes() bool {
	if o != nil && !IsNil(o.Volumes) {
		return true
	}

	return false
}

// SetVolumes gets a reference to the given []VolumeSizeInput and assigns it to the Volumes field.
func (o *CreateAppServiceInput) SetVolumes(v []VolumeSizeInput) {
	o.Volumes = v
}

// GetIntegrations returns the Integrations field value if set, zero value otherwise.
func (o *CreateAppServiceInput) GetIntegrations() []AppServiceIntegrationInput {
	if o == nil || IsNil(o.Integrations) {
		var ret []AppServiceIntegrationInput
		return ret
	}
	return o.Integrations
}

// GetIntegrationsOk returns a tuple with the Integrations field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *CreateAppServiceInput) GetIntegrationsOk() ([]AppServiceIntegrationInput, bool) {
	if o == nil || IsNil(o.Integrations) {
		return nil, false
	}
	return o.Integrations, true
}

// HasIntegrations returns a boolean if a field has been set.
func (o *CreateAppServiceInput) HasIntegrations() bool {
	if o != nil && !IsNil(o.Integrations) {
		return true
	}

	return false
}

// SetIntegrations gets a reference to the given []AppServiceIntegrationInput and assigns it to the Integrations field.
func (o *CreateAppServiceInput) SetIntegrations(v []AppServiceIntegrationInput) {
	o.Integrations = v
}

// GetSettings returns the Settings field value if set, zero value otherwise.
func (o *CreateAppServiceInput) GetSettings() []AppServiceSettingInput {
	if o == nil || IsNil(o.Settings) {
		var ret []AppServiceSettingInput
		return ret
	}
	return o.Settings
}

// GetSettingsOk returns a tuple with the Settings field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *CreateAppServiceInput) GetSettingsOk() ([]AppServiceSettingInput, bool) {
	if o == nil || IsNil(o.Settings) {
		return nil, false
	}
	return o.Settings, true
}

// HasSettings returns a boolean if a field has been set.
func (o *CreateAppServiceInput) HasSettings() bool {
	if o != nil && !IsNil(o.Settings) {
		return true
	}

	return false
}

// SetSettings gets a reference to the given []AppServiceSettingInput and assigns it to the Settings field.
func (o *CreateAppServiceInput) SetSettings(v []AppServiceSettingInput) {
	o.Settings = v
}

// GetDatabase returns the Database field value if set, zero value otherwise.
func (o *CreateAppServiceInput) GetDatabase() AppServiceDatabaseInput {
	if o == nil || IsNil(o.Database) {
		var ret AppServiceDatabaseInput
		return ret
	}
	return *o.Database
}

// GetDatabaseOk returns a tuple with the Database field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *CreateAppServiceInput) GetDatabaseOk() (*AppServiceDatabaseInput, bool) {
	if o == nil || IsNil(o.Database) {
		return nil, false
	}
	return o.Database, true
}

// HasDatabase returns a boolean if a field has been set.
func (o *CreateAppServiceInput) HasDatabase() bool {
	if o != nil && !IsNil(o.Database) {
		return true
	}

	return false
}

// SetDatabase gets a reference to the given AppServiceDatabaseInput and assigns it to the Database field.
func (o *CreateAppServiceInput) SetDatabase(v AppServiceDatabaseInput) {
	o.Database = &v
}

// GetResources returns the Resources field value if set, zero value otherwise.
func (o *CreateAppServiceInput) GetResources() ResourcesInput {
	if o == nil || IsNil(o.Resources) {
		var ret ResourcesInput
		return ret
	}
	return *o.Resources
}

// GetResourcesOk returns a tuple with the Resources field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *CreateAppServiceInput) GetResourcesOk() (*ResourcesInput, bool) {
	if o == nil || IsNil(o.Resources) {
		return nil, false
	}
	return o.Resources, true
}

// HasResources returns a boolean if a field has been set.
func (o *CreateAppServiceInput) HasResources() bool {
	if o != nil && !IsNil(o.Resources) {
		return true
	}

	return false
}

// SetResources gets a reference to the given ResourcesInput and assigns it to the Resources field.
func (o *CreateAppServiceInput) SetResources(v ResourcesInput) {
	o.Resources = &v
}

// GetScalability returns the Scalability field value if set, zero value otherwise.
func (o *CreateAppServiceInput) GetScalability() ScalabilityInput {
	if o == nil || IsNil(o.Scalability) {
		var ret ScalabilityInput
		return ret
	}
	return *o.Scalability
}

// GetScalabilityOk returns a tuple with the Scalability field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *CreateAppServiceInput) GetScalabilityOk() (*ScalabilityInput, bool) {
	if o == nil || IsNil(o.Scalability) {
		return nil, false
	}
	return o.Scalability, true
}

// HasScalability returns a boolean if a field has been set.
func (o *CreateAppServiceInput) HasScalability() bool {
	if o != nil && !IsNil(o.Scalability) {
		return true
	}

	return false
}

// SetScalability gets a reference to the given ScalabilityInput and assigns it to the Scalability field.
func (o *CreateAppServiceInput) SetScalability(v ScalabilityInput) {
	o.Scalability = &v
}

func (o CreateAppServiceInput) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o CreateAppServiceInput) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["id"] = o.Id
	toSerialize["disabled"] = o.Disabled
	if o.Version.IsSet() {
		toSerialize["version"] = o.Version.Get()
	}
	if !IsNil(o.BuildSource) {
		toSerialize["buildSource"] = o.BuildSource
	}
	if !IsNil(o.Imports) {
		toSerialize["imports"] = o.Imports
	}
	if !IsNil(o.Volumes) {
		toSerialize["volumes"] = o.Volumes
	}
	if !IsNil(o.Integrations) {
		toSerialize["integrations"] = o.Integrations
	}
	if !IsNil(o.Settings) {
		toSerialize["settings"] = o.Settings
	}
	if !IsNil(o.Database) {
		toSerialize["database"] = o.Database
	}
	if !IsNil(o.Resources) {
		toSerialize["resources"] = o.Resources
	}
	if !IsNil(o.Scalability) {
		toSerialize["scalability"] = o.Scalability
	}
	return toSerialize, nil
}

func (o *CreateAppServiceInput) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"id",
		"disabled",
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err;
	}

	for _, requiredProperty := range(requiredProperties) {
		if _, exists := allProperties[requiredProperty]; !exists {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varCreateAppServiceInput := _CreateAppServiceInput{}

	decoder := json.NewDecoder(bytes.NewReader(data))
	decoder.DisallowUnknownFields()
	err = decoder.Decode(&varCreateAppServiceInput)

	if err != nil {
		return err
	}

	*o = CreateAppServiceInput(varCreateAppServiceInput)

	return err
}

type NullableCreateAppServiceInput struct {
	value *CreateAppServiceInput
	isSet bool
}

func (v NullableCreateAppServiceInput) Get() *CreateAppServiceInput {
	return v.value
}

func (v *NullableCreateAppServiceInput) Set(val *CreateAppServiceInput) {
	v.value = val
	v.isSet = true
}

func (v NullableCreateAppServiceInput) IsSet() bool {
	return v.isSet
}

func (v *NullableCreateAppServiceInput) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableCreateAppServiceInput(val *CreateAppServiceInput) *NullableCreateAppServiceInput {
	return &NullableCreateAppServiceInput{value: val, isSet: true}
}

func (v NullableCreateAppServiceInput) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableCreateAppServiceInput) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


