/*
Wodby 2 Public API

Public REST API for customer SDKs and code integrations. GraphQL remains internal for the dashboard. This contract is the versioned public surface. 

API version: 1.0.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package client

import (
	"encoding/json"
	"bytes"
	"fmt"
)

// checks if the AddAppServiceVolumeInput type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &AddAppServiceVolumeInput{}

// AddAppServiceVolumeInput struct for AddAppServiceVolumeInput
type AddAppServiceVolumeInput struct {
	Name string `json:"name"`
	Size NullableInt32 `json:"size,omitempty"`
	StorageClassName NullableString `json:"storageClassName,omitempty"`
}

type _AddAppServiceVolumeInput AddAppServiceVolumeInput

// NewAddAppServiceVolumeInput instantiates a new AddAppServiceVolumeInput object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewAddAppServiceVolumeInput(name string) *AddAppServiceVolumeInput {
	this := AddAppServiceVolumeInput{}
	this.Name = name
	return &this
}

// NewAddAppServiceVolumeInputWithDefaults instantiates a new AddAppServiceVolumeInput object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewAddAppServiceVolumeInputWithDefaults() *AddAppServiceVolumeInput {
	this := AddAppServiceVolumeInput{}
	return &this
}

// GetName returns the Name field value
func (o *AddAppServiceVolumeInput) GetName() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Name
}

// GetNameOk returns a tuple with the Name field value
// and a boolean to check if the value has been set.
func (o *AddAppServiceVolumeInput) GetNameOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Name, true
}

// SetName sets field value
func (o *AddAppServiceVolumeInput) SetName(v string) {
	o.Name = v
}

// GetSize returns the Size field value if set, zero value otherwise (both if not set or set to explicit null).
func (o *AddAppServiceVolumeInput) GetSize() int32 {
	if o == nil || IsNil(o.Size.Get()) {
		var ret int32
		return ret
	}
	return *o.Size.Get()
}

// GetSizeOk returns a tuple with the Size field value if set, nil otherwise
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *AddAppServiceVolumeInput) GetSizeOk() (*int32, bool) {
	if o == nil {
		return nil, false
	}
	return o.Size.Get(), o.Size.IsSet()
}

// HasSize returns a boolean if a field has been set.
func (o *AddAppServiceVolumeInput) HasSize() bool {
	if o != nil && o.Size.IsSet() {
		return true
	}

	return false
}

// SetSize gets a reference to the given NullableInt32 and assigns it to the Size field.
func (o *AddAppServiceVolumeInput) SetSize(v int32) {
	o.Size.Set(&v)
}
// SetSizeNil sets the value for Size to be an explicit nil
func (o *AddAppServiceVolumeInput) SetSizeNil() {
	o.Size.Set(nil)
}

// UnsetSize ensures that no value is present for Size, not even an explicit nil
func (o *AddAppServiceVolumeInput) UnsetSize() {
	o.Size.Unset()
}

// GetStorageClassName returns the StorageClassName field value if set, zero value otherwise (both if not set or set to explicit null).
func (o *AddAppServiceVolumeInput) GetStorageClassName() string {
	if o == nil || IsNil(o.StorageClassName.Get()) {
		var ret string
		return ret
	}
	return *o.StorageClassName.Get()
}

// GetStorageClassNameOk returns a tuple with the StorageClassName field value if set, nil otherwise
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *AddAppServiceVolumeInput) GetStorageClassNameOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return o.StorageClassName.Get(), o.StorageClassName.IsSet()
}

// HasStorageClassName returns a boolean if a field has been set.
func (o *AddAppServiceVolumeInput) HasStorageClassName() bool {
	if o != nil && o.StorageClassName.IsSet() {
		return true
	}

	return false
}

// SetStorageClassName gets a reference to the given NullableString and assigns it to the StorageClassName field.
func (o *AddAppServiceVolumeInput) SetStorageClassName(v string) {
	o.StorageClassName.Set(&v)
}
// SetStorageClassNameNil sets the value for StorageClassName to be an explicit nil
func (o *AddAppServiceVolumeInput) SetStorageClassNameNil() {
	o.StorageClassName.Set(nil)
}

// UnsetStorageClassName ensures that no value is present for StorageClassName, not even an explicit nil
func (o *AddAppServiceVolumeInput) UnsetStorageClassName() {
	o.StorageClassName.Unset()
}

func (o AddAppServiceVolumeInput) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o AddAppServiceVolumeInput) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["name"] = o.Name
	if o.Size.IsSet() {
		toSerialize["size"] = o.Size.Get()
	}
	if o.StorageClassName.IsSet() {
		toSerialize["storageClassName"] = o.StorageClassName.Get()
	}
	return toSerialize, nil
}

func (o *AddAppServiceVolumeInput) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"name",
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err;
	}

	for _, requiredProperty := range(requiredProperties) {
		if _, exists := allProperties[requiredProperty]; !exists {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varAddAppServiceVolumeInput := _AddAppServiceVolumeInput{}

	decoder := json.NewDecoder(bytes.NewReader(data))
	decoder.DisallowUnknownFields()
	err = decoder.Decode(&varAddAppServiceVolumeInput)

	if err != nil {
		return err
	}

	*o = AddAppServiceVolumeInput(varAddAppServiceVolumeInput)

	return err
}

type NullableAddAppServiceVolumeInput struct {
	value *AddAppServiceVolumeInput
	isSet bool
}

func (v NullableAddAppServiceVolumeInput) Get() *AddAppServiceVolumeInput {
	return v.value
}

func (v *NullableAddAppServiceVolumeInput) Set(val *AddAppServiceVolumeInput) {
	v.value = val
	v.isSet = true
}

func (v NullableAddAppServiceVolumeInput) IsSet() bool {
	return v.isSet
}

func (v *NullableAddAppServiceVolumeInput) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableAddAppServiceVolumeInput(val *AddAppServiceVolumeInput) *NullableAddAppServiceVolumeInput {
	return &NullableAddAppServiceVolumeInput{value: val, isSet: true}
}

func (v NullableAddAppServiceVolumeInput) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableAddAppServiceVolumeInput) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


