/*
Wodby 2 Public API

Public REST API for customer SDKs and code integrations. GraphQL remains internal for the dashboard. This contract is the versioned public surface. 

API version: 1.0.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package client

import (
	"encoding/json"
)

// checks if the UpdateStackServiceCronScheduleInput type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &UpdateStackServiceCronScheduleInput{}

// UpdateStackServiceCronScheduleInput struct for UpdateStackServiceCronScheduleInput
type UpdateStackServiceCronScheduleInput struct {
	Disabled NullableBool `json:"disabled,omitempty"`
	Title NullableString `json:"title,omitempty"`
	Crontab NullableString `json:"crontab,omitempty"`
	Command NullableString `json:"command,omitempty"`
	Workload NullableString `json:"workload,omitempty"`
	EnvType NullableString `json:"envType,omitempty"`
}

// NewUpdateStackServiceCronScheduleInput instantiates a new UpdateStackServiceCronScheduleInput object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewUpdateStackServiceCronScheduleInput() *UpdateStackServiceCronScheduleInput {
	this := UpdateStackServiceCronScheduleInput{}
	return &this
}

// NewUpdateStackServiceCronScheduleInputWithDefaults instantiates a new UpdateStackServiceCronScheduleInput object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewUpdateStackServiceCronScheduleInputWithDefaults() *UpdateStackServiceCronScheduleInput {
	this := UpdateStackServiceCronScheduleInput{}
	return &this
}

// GetDisabled returns the Disabled field value if set, zero value otherwise (both if not set or set to explicit null).
func (o *UpdateStackServiceCronScheduleInput) GetDisabled() bool {
	if o == nil || IsNil(o.Disabled.Get()) {
		var ret bool
		return ret
	}
	return *o.Disabled.Get()
}

// GetDisabledOk returns a tuple with the Disabled field value if set, nil otherwise
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *UpdateStackServiceCronScheduleInput) GetDisabledOk() (*bool, bool) {
	if o == nil {
		return nil, false
	}
	return o.Disabled.Get(), o.Disabled.IsSet()
}

// HasDisabled returns a boolean if a field has been set.
func (o *UpdateStackServiceCronScheduleInput) HasDisabled() bool {
	if o != nil && o.Disabled.IsSet() {
		return true
	}

	return false
}

// SetDisabled gets a reference to the given NullableBool and assigns it to the Disabled field.
func (o *UpdateStackServiceCronScheduleInput) SetDisabled(v bool) {
	o.Disabled.Set(&v)
}
// SetDisabledNil sets the value for Disabled to be an explicit nil
func (o *UpdateStackServiceCronScheduleInput) SetDisabledNil() {
	o.Disabled.Set(nil)
}

// UnsetDisabled ensures that no value is present for Disabled, not even an explicit nil
func (o *UpdateStackServiceCronScheduleInput) UnsetDisabled() {
	o.Disabled.Unset()
}

// GetTitle returns the Title field value if set, zero value otherwise (both if not set or set to explicit null).
func (o *UpdateStackServiceCronScheduleInput) GetTitle() string {
	if o == nil || IsNil(o.Title.Get()) {
		var ret string
		return ret
	}
	return *o.Title.Get()
}

// GetTitleOk returns a tuple with the Title field value if set, nil otherwise
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *UpdateStackServiceCronScheduleInput) GetTitleOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return o.Title.Get(), o.Title.IsSet()
}

// HasTitle returns a boolean if a field has been set.
func (o *UpdateStackServiceCronScheduleInput) HasTitle() bool {
	if o != nil && o.Title.IsSet() {
		return true
	}

	return false
}

// SetTitle gets a reference to the given NullableString and assigns it to the Title field.
func (o *UpdateStackServiceCronScheduleInput) SetTitle(v string) {
	o.Title.Set(&v)
}
// SetTitleNil sets the value for Title to be an explicit nil
func (o *UpdateStackServiceCronScheduleInput) SetTitleNil() {
	o.Title.Set(nil)
}

// UnsetTitle ensures that no value is present for Title, not even an explicit nil
func (o *UpdateStackServiceCronScheduleInput) UnsetTitle() {
	o.Title.Unset()
}

// GetCrontab returns the Crontab field value if set, zero value otherwise (both if not set or set to explicit null).
func (o *UpdateStackServiceCronScheduleInput) GetCrontab() string {
	if o == nil || IsNil(o.Crontab.Get()) {
		var ret string
		return ret
	}
	return *o.Crontab.Get()
}

// GetCrontabOk returns a tuple with the Crontab field value if set, nil otherwise
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *UpdateStackServiceCronScheduleInput) GetCrontabOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return o.Crontab.Get(), o.Crontab.IsSet()
}

// HasCrontab returns a boolean if a field has been set.
func (o *UpdateStackServiceCronScheduleInput) HasCrontab() bool {
	if o != nil && o.Crontab.IsSet() {
		return true
	}

	return false
}

// SetCrontab gets a reference to the given NullableString and assigns it to the Crontab field.
func (o *UpdateStackServiceCronScheduleInput) SetCrontab(v string) {
	o.Crontab.Set(&v)
}
// SetCrontabNil sets the value for Crontab to be an explicit nil
func (o *UpdateStackServiceCronScheduleInput) SetCrontabNil() {
	o.Crontab.Set(nil)
}

// UnsetCrontab ensures that no value is present for Crontab, not even an explicit nil
func (o *UpdateStackServiceCronScheduleInput) UnsetCrontab() {
	o.Crontab.Unset()
}

// GetCommand returns the Command field value if set, zero value otherwise (both if not set or set to explicit null).
func (o *UpdateStackServiceCronScheduleInput) GetCommand() string {
	if o == nil || IsNil(o.Command.Get()) {
		var ret string
		return ret
	}
	return *o.Command.Get()
}

// GetCommandOk returns a tuple with the Command field value if set, nil otherwise
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *UpdateStackServiceCronScheduleInput) GetCommandOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return o.Command.Get(), o.Command.IsSet()
}

// HasCommand returns a boolean if a field has been set.
func (o *UpdateStackServiceCronScheduleInput) HasCommand() bool {
	if o != nil && o.Command.IsSet() {
		return true
	}

	return false
}

// SetCommand gets a reference to the given NullableString and assigns it to the Command field.
func (o *UpdateStackServiceCronScheduleInput) SetCommand(v string) {
	o.Command.Set(&v)
}
// SetCommandNil sets the value for Command to be an explicit nil
func (o *UpdateStackServiceCronScheduleInput) SetCommandNil() {
	o.Command.Set(nil)
}

// UnsetCommand ensures that no value is present for Command, not even an explicit nil
func (o *UpdateStackServiceCronScheduleInput) UnsetCommand() {
	o.Command.Unset()
}

// GetWorkload returns the Workload field value if set, zero value otherwise (both if not set or set to explicit null).
func (o *UpdateStackServiceCronScheduleInput) GetWorkload() string {
	if o == nil || IsNil(o.Workload.Get()) {
		var ret string
		return ret
	}
	return *o.Workload.Get()
}

// GetWorkloadOk returns a tuple with the Workload field value if set, nil otherwise
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *UpdateStackServiceCronScheduleInput) GetWorkloadOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return o.Workload.Get(), o.Workload.IsSet()
}

// HasWorkload returns a boolean if a field has been set.
func (o *UpdateStackServiceCronScheduleInput) HasWorkload() bool {
	if o != nil && o.Workload.IsSet() {
		return true
	}

	return false
}

// SetWorkload gets a reference to the given NullableString and assigns it to the Workload field.
func (o *UpdateStackServiceCronScheduleInput) SetWorkload(v string) {
	o.Workload.Set(&v)
}
// SetWorkloadNil sets the value for Workload to be an explicit nil
func (o *UpdateStackServiceCronScheduleInput) SetWorkloadNil() {
	o.Workload.Set(nil)
}

// UnsetWorkload ensures that no value is present for Workload, not even an explicit nil
func (o *UpdateStackServiceCronScheduleInput) UnsetWorkload() {
	o.Workload.Unset()
}

// GetEnvType returns the EnvType field value if set, zero value otherwise (both if not set or set to explicit null).
func (o *UpdateStackServiceCronScheduleInput) GetEnvType() string {
	if o == nil || IsNil(o.EnvType.Get()) {
		var ret string
		return ret
	}
	return *o.EnvType.Get()
}

// GetEnvTypeOk returns a tuple with the EnvType field value if set, nil otherwise
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *UpdateStackServiceCronScheduleInput) GetEnvTypeOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return o.EnvType.Get(), o.EnvType.IsSet()
}

// HasEnvType returns a boolean if a field has been set.
func (o *UpdateStackServiceCronScheduleInput) HasEnvType() bool {
	if o != nil && o.EnvType.IsSet() {
		return true
	}

	return false
}

// SetEnvType gets a reference to the given NullableString and assigns it to the EnvType field.
func (o *UpdateStackServiceCronScheduleInput) SetEnvType(v string) {
	o.EnvType.Set(&v)
}
// SetEnvTypeNil sets the value for EnvType to be an explicit nil
func (o *UpdateStackServiceCronScheduleInput) SetEnvTypeNil() {
	o.EnvType.Set(nil)
}

// UnsetEnvType ensures that no value is present for EnvType, not even an explicit nil
func (o *UpdateStackServiceCronScheduleInput) UnsetEnvType() {
	o.EnvType.Unset()
}

func (o UpdateStackServiceCronScheduleInput) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o UpdateStackServiceCronScheduleInput) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if o.Disabled.IsSet() {
		toSerialize["disabled"] = o.Disabled.Get()
	}
	if o.Title.IsSet() {
		toSerialize["title"] = o.Title.Get()
	}
	if o.Crontab.IsSet() {
		toSerialize["crontab"] = o.Crontab.Get()
	}
	if o.Command.IsSet() {
		toSerialize["command"] = o.Command.Get()
	}
	if o.Workload.IsSet() {
		toSerialize["workload"] = o.Workload.Get()
	}
	if o.EnvType.IsSet() {
		toSerialize["envType"] = o.EnvType.Get()
	}
	return toSerialize, nil
}

type NullableUpdateStackServiceCronScheduleInput struct {
	value *UpdateStackServiceCronScheduleInput
	isSet bool
}

func (v NullableUpdateStackServiceCronScheduleInput) Get() *UpdateStackServiceCronScheduleInput {
	return v.value
}

func (v *NullableUpdateStackServiceCronScheduleInput) Set(val *UpdateStackServiceCronScheduleInput) {
	v.value = val
	v.isSet = true
}

func (v NullableUpdateStackServiceCronScheduleInput) IsSet() bool {
	return v.isSet
}

func (v *NullableUpdateStackServiceCronScheduleInput) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableUpdateStackServiceCronScheduleInput(val *UpdateStackServiceCronScheduleInput) *NullableUpdateStackServiceCronScheduleInput {
	return &NullableUpdateStackServiceCronScheduleInput{value: val, isSet: true}
}

func (v NullableUpdateStackServiceCronScheduleInput) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableUpdateStackServiceCronScheduleInput) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


