/*
Wodby 2 Public API

Public REST API for customer SDKs and code integrations. GraphQL remains internal for the dashboard. This contract is the versioned public surface. 

API version: 1.0.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package client

import (
	"encoding/json"
	"time"
	"bytes"
	"fmt"
)

// checks if the Cluster type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &Cluster{}

// Cluster struct for Cluster
type Cluster struct {
	Id int32 `json:"id"`
	Name string `json:"name"`
	Title string `json:"title"`
	Status string `json:"status"`
	Serverless bool `json:"serverless"`
	Demo bool `json:"demo"`
	Wodby bool `json:"wodby"`
	K3s bool `json:"k3s"`
	SingleNode bool `json:"singleNode"`
	Version NullableString `json:"version,omitempty"`
	InfraVersion string `json:"infraVersion"`
	MinNodeCount NullableInt32 `json:"minNodeCount,omitempty"`
	MaxNodeCount NullableInt32 `json:"maxNodeCount,omitempty"`
	LastNodeCount NullableInt32 `json:"lastNodeCount,omitempty"`
	Region NullableString `json:"region,omitempty"`
	Zone NullableString `json:"zone,omitempty"`
	Ips []string `json:"ips,omitempty"`
	Hostname NullableString `json:"hostname,omitempty"`
	IntegrationId NullableInt32 `json:"integrationId,omitempty"`
	OrgId int32 `json:"orgId"`
	Settings *ClusterSettings `json:"settings,omitempty"`
	CreatedAt time.Time `json:"createdAt"`
	UpdatedAt time.Time `json:"updatedAt"`
}

type _Cluster Cluster

// NewCluster instantiates a new Cluster object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewCluster(id int32, name string, title string, status string, serverless bool, demo bool, wodby bool, k3s bool, singleNode bool, infraVersion string, orgId int32, createdAt time.Time, updatedAt time.Time) *Cluster {
	this := Cluster{}
	this.Id = id
	this.Name = name
	this.Title = title
	this.Status = status
	this.Serverless = serverless
	this.Demo = demo
	this.Wodby = wodby
	this.K3s = k3s
	this.SingleNode = singleNode
	this.InfraVersion = infraVersion
	this.OrgId = orgId
	this.CreatedAt = createdAt
	this.UpdatedAt = updatedAt
	return &this
}

// NewClusterWithDefaults instantiates a new Cluster object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewClusterWithDefaults() *Cluster {
	this := Cluster{}
	return &this
}

// GetId returns the Id field value
func (o *Cluster) GetId() int32 {
	if o == nil {
		var ret int32
		return ret
	}

	return o.Id
}

// GetIdOk returns a tuple with the Id field value
// and a boolean to check if the value has been set.
func (o *Cluster) GetIdOk() (*int32, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Id, true
}

// SetId sets field value
func (o *Cluster) SetId(v int32) {
	o.Id = v
}

// GetName returns the Name field value
func (o *Cluster) GetName() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Name
}

// GetNameOk returns a tuple with the Name field value
// and a boolean to check if the value has been set.
func (o *Cluster) GetNameOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Name, true
}

// SetName sets field value
func (o *Cluster) SetName(v string) {
	o.Name = v
}

// GetTitle returns the Title field value
func (o *Cluster) GetTitle() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Title
}

// GetTitleOk returns a tuple with the Title field value
// and a boolean to check if the value has been set.
func (o *Cluster) GetTitleOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Title, true
}

// SetTitle sets field value
func (o *Cluster) SetTitle(v string) {
	o.Title = v
}

// GetStatus returns the Status field value
func (o *Cluster) GetStatus() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Status
}

// GetStatusOk returns a tuple with the Status field value
// and a boolean to check if the value has been set.
func (o *Cluster) GetStatusOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Status, true
}

// SetStatus sets field value
func (o *Cluster) SetStatus(v string) {
	o.Status = v
}

// GetServerless returns the Serverless field value
func (o *Cluster) GetServerless() bool {
	if o == nil {
		var ret bool
		return ret
	}

	return o.Serverless
}

// GetServerlessOk returns a tuple with the Serverless field value
// and a boolean to check if the value has been set.
func (o *Cluster) GetServerlessOk() (*bool, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Serverless, true
}

// SetServerless sets field value
func (o *Cluster) SetServerless(v bool) {
	o.Serverless = v
}

// GetDemo returns the Demo field value
func (o *Cluster) GetDemo() bool {
	if o == nil {
		var ret bool
		return ret
	}

	return o.Demo
}

// GetDemoOk returns a tuple with the Demo field value
// and a boolean to check if the value has been set.
func (o *Cluster) GetDemoOk() (*bool, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Demo, true
}

// SetDemo sets field value
func (o *Cluster) SetDemo(v bool) {
	o.Demo = v
}

// GetWodby returns the Wodby field value
func (o *Cluster) GetWodby() bool {
	if o == nil {
		var ret bool
		return ret
	}

	return o.Wodby
}

// GetWodbyOk returns a tuple with the Wodby field value
// and a boolean to check if the value has been set.
func (o *Cluster) GetWodbyOk() (*bool, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Wodby, true
}

// SetWodby sets field value
func (o *Cluster) SetWodby(v bool) {
	o.Wodby = v
}

// GetK3s returns the K3s field value
func (o *Cluster) GetK3s() bool {
	if o == nil {
		var ret bool
		return ret
	}

	return o.K3s
}

// GetK3sOk returns a tuple with the K3s field value
// and a boolean to check if the value has been set.
func (o *Cluster) GetK3sOk() (*bool, bool) {
	if o == nil {
		return nil, false
	}
	return &o.K3s, true
}

// SetK3s sets field value
func (o *Cluster) SetK3s(v bool) {
	o.K3s = v
}

// GetSingleNode returns the SingleNode field value
func (o *Cluster) GetSingleNode() bool {
	if o == nil {
		var ret bool
		return ret
	}

	return o.SingleNode
}

// GetSingleNodeOk returns a tuple with the SingleNode field value
// and a boolean to check if the value has been set.
func (o *Cluster) GetSingleNodeOk() (*bool, bool) {
	if o == nil {
		return nil, false
	}
	return &o.SingleNode, true
}

// SetSingleNode sets field value
func (o *Cluster) SetSingleNode(v bool) {
	o.SingleNode = v
}

// GetVersion returns the Version field value if set, zero value otherwise (both if not set or set to explicit null).
func (o *Cluster) GetVersion() string {
	if o == nil || IsNil(o.Version.Get()) {
		var ret string
		return ret
	}
	return *o.Version.Get()
}

// GetVersionOk returns a tuple with the Version field value if set, nil otherwise
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *Cluster) GetVersionOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return o.Version.Get(), o.Version.IsSet()
}

// HasVersion returns a boolean if a field has been set.
func (o *Cluster) HasVersion() bool {
	if o != nil && o.Version.IsSet() {
		return true
	}

	return false
}

// SetVersion gets a reference to the given NullableString and assigns it to the Version field.
func (o *Cluster) SetVersion(v string) {
	o.Version.Set(&v)
}
// SetVersionNil sets the value for Version to be an explicit nil
func (o *Cluster) SetVersionNil() {
	o.Version.Set(nil)
}

// UnsetVersion ensures that no value is present for Version, not even an explicit nil
func (o *Cluster) UnsetVersion() {
	o.Version.Unset()
}

// GetInfraVersion returns the InfraVersion field value
func (o *Cluster) GetInfraVersion() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.InfraVersion
}

// GetInfraVersionOk returns a tuple with the InfraVersion field value
// and a boolean to check if the value has been set.
func (o *Cluster) GetInfraVersionOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.InfraVersion, true
}

// SetInfraVersion sets field value
func (o *Cluster) SetInfraVersion(v string) {
	o.InfraVersion = v
}

// GetMinNodeCount returns the MinNodeCount field value if set, zero value otherwise (both if not set or set to explicit null).
func (o *Cluster) GetMinNodeCount() int32 {
	if o == nil || IsNil(o.MinNodeCount.Get()) {
		var ret int32
		return ret
	}
	return *o.MinNodeCount.Get()
}

// GetMinNodeCountOk returns a tuple with the MinNodeCount field value if set, nil otherwise
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *Cluster) GetMinNodeCountOk() (*int32, bool) {
	if o == nil {
		return nil, false
	}
	return o.MinNodeCount.Get(), o.MinNodeCount.IsSet()
}

// HasMinNodeCount returns a boolean if a field has been set.
func (o *Cluster) HasMinNodeCount() bool {
	if o != nil && o.MinNodeCount.IsSet() {
		return true
	}

	return false
}

// SetMinNodeCount gets a reference to the given NullableInt32 and assigns it to the MinNodeCount field.
func (o *Cluster) SetMinNodeCount(v int32) {
	o.MinNodeCount.Set(&v)
}
// SetMinNodeCountNil sets the value for MinNodeCount to be an explicit nil
func (o *Cluster) SetMinNodeCountNil() {
	o.MinNodeCount.Set(nil)
}

// UnsetMinNodeCount ensures that no value is present for MinNodeCount, not even an explicit nil
func (o *Cluster) UnsetMinNodeCount() {
	o.MinNodeCount.Unset()
}

// GetMaxNodeCount returns the MaxNodeCount field value if set, zero value otherwise (both if not set or set to explicit null).
func (o *Cluster) GetMaxNodeCount() int32 {
	if o == nil || IsNil(o.MaxNodeCount.Get()) {
		var ret int32
		return ret
	}
	return *o.MaxNodeCount.Get()
}

// GetMaxNodeCountOk returns a tuple with the MaxNodeCount field value if set, nil otherwise
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *Cluster) GetMaxNodeCountOk() (*int32, bool) {
	if o == nil {
		return nil, false
	}
	return o.MaxNodeCount.Get(), o.MaxNodeCount.IsSet()
}

// HasMaxNodeCount returns a boolean if a field has been set.
func (o *Cluster) HasMaxNodeCount() bool {
	if o != nil && o.MaxNodeCount.IsSet() {
		return true
	}

	return false
}

// SetMaxNodeCount gets a reference to the given NullableInt32 and assigns it to the MaxNodeCount field.
func (o *Cluster) SetMaxNodeCount(v int32) {
	o.MaxNodeCount.Set(&v)
}
// SetMaxNodeCountNil sets the value for MaxNodeCount to be an explicit nil
func (o *Cluster) SetMaxNodeCountNil() {
	o.MaxNodeCount.Set(nil)
}

// UnsetMaxNodeCount ensures that no value is present for MaxNodeCount, not even an explicit nil
func (o *Cluster) UnsetMaxNodeCount() {
	o.MaxNodeCount.Unset()
}

// GetLastNodeCount returns the LastNodeCount field value if set, zero value otherwise (both if not set or set to explicit null).
func (o *Cluster) GetLastNodeCount() int32 {
	if o == nil || IsNil(o.LastNodeCount.Get()) {
		var ret int32
		return ret
	}
	return *o.LastNodeCount.Get()
}

// GetLastNodeCountOk returns a tuple with the LastNodeCount field value if set, nil otherwise
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *Cluster) GetLastNodeCountOk() (*int32, bool) {
	if o == nil {
		return nil, false
	}
	return o.LastNodeCount.Get(), o.LastNodeCount.IsSet()
}

// HasLastNodeCount returns a boolean if a field has been set.
func (o *Cluster) HasLastNodeCount() bool {
	if o != nil && o.LastNodeCount.IsSet() {
		return true
	}

	return false
}

// SetLastNodeCount gets a reference to the given NullableInt32 and assigns it to the LastNodeCount field.
func (o *Cluster) SetLastNodeCount(v int32) {
	o.LastNodeCount.Set(&v)
}
// SetLastNodeCountNil sets the value for LastNodeCount to be an explicit nil
func (o *Cluster) SetLastNodeCountNil() {
	o.LastNodeCount.Set(nil)
}

// UnsetLastNodeCount ensures that no value is present for LastNodeCount, not even an explicit nil
func (o *Cluster) UnsetLastNodeCount() {
	o.LastNodeCount.Unset()
}

// GetRegion returns the Region field value if set, zero value otherwise (both if not set or set to explicit null).
func (o *Cluster) GetRegion() string {
	if o == nil || IsNil(o.Region.Get()) {
		var ret string
		return ret
	}
	return *o.Region.Get()
}

// GetRegionOk returns a tuple with the Region field value if set, nil otherwise
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *Cluster) GetRegionOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return o.Region.Get(), o.Region.IsSet()
}

// HasRegion returns a boolean if a field has been set.
func (o *Cluster) HasRegion() bool {
	if o != nil && o.Region.IsSet() {
		return true
	}

	return false
}

// SetRegion gets a reference to the given NullableString and assigns it to the Region field.
func (o *Cluster) SetRegion(v string) {
	o.Region.Set(&v)
}
// SetRegionNil sets the value for Region to be an explicit nil
func (o *Cluster) SetRegionNil() {
	o.Region.Set(nil)
}

// UnsetRegion ensures that no value is present for Region, not even an explicit nil
func (o *Cluster) UnsetRegion() {
	o.Region.Unset()
}

// GetZone returns the Zone field value if set, zero value otherwise (both if not set or set to explicit null).
func (o *Cluster) GetZone() string {
	if o == nil || IsNil(o.Zone.Get()) {
		var ret string
		return ret
	}
	return *o.Zone.Get()
}

// GetZoneOk returns a tuple with the Zone field value if set, nil otherwise
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *Cluster) GetZoneOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return o.Zone.Get(), o.Zone.IsSet()
}

// HasZone returns a boolean if a field has been set.
func (o *Cluster) HasZone() bool {
	if o != nil && o.Zone.IsSet() {
		return true
	}

	return false
}

// SetZone gets a reference to the given NullableString and assigns it to the Zone field.
func (o *Cluster) SetZone(v string) {
	o.Zone.Set(&v)
}
// SetZoneNil sets the value for Zone to be an explicit nil
func (o *Cluster) SetZoneNil() {
	o.Zone.Set(nil)
}

// UnsetZone ensures that no value is present for Zone, not even an explicit nil
func (o *Cluster) UnsetZone() {
	o.Zone.Unset()
}

// GetIps returns the Ips field value if set, zero value otherwise (both if not set or set to explicit null).
func (o *Cluster) GetIps() []string {
	if o == nil {
		var ret []string
		return ret
	}
	return o.Ips
}

// GetIpsOk returns a tuple with the Ips field value if set, nil otherwise
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *Cluster) GetIpsOk() ([]string, bool) {
	if o == nil || IsNil(o.Ips) {
		return nil, false
	}
	return o.Ips, true
}

// HasIps returns a boolean if a field has been set.
func (o *Cluster) HasIps() bool {
	if o != nil && !IsNil(o.Ips) {
		return true
	}

	return false
}

// SetIps gets a reference to the given []string and assigns it to the Ips field.
func (o *Cluster) SetIps(v []string) {
	o.Ips = v
}

// GetHostname returns the Hostname field value if set, zero value otherwise (both if not set or set to explicit null).
func (o *Cluster) GetHostname() string {
	if o == nil || IsNil(o.Hostname.Get()) {
		var ret string
		return ret
	}
	return *o.Hostname.Get()
}

// GetHostnameOk returns a tuple with the Hostname field value if set, nil otherwise
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *Cluster) GetHostnameOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return o.Hostname.Get(), o.Hostname.IsSet()
}

// HasHostname returns a boolean if a field has been set.
func (o *Cluster) HasHostname() bool {
	if o != nil && o.Hostname.IsSet() {
		return true
	}

	return false
}

// SetHostname gets a reference to the given NullableString and assigns it to the Hostname field.
func (o *Cluster) SetHostname(v string) {
	o.Hostname.Set(&v)
}
// SetHostnameNil sets the value for Hostname to be an explicit nil
func (o *Cluster) SetHostnameNil() {
	o.Hostname.Set(nil)
}

// UnsetHostname ensures that no value is present for Hostname, not even an explicit nil
func (o *Cluster) UnsetHostname() {
	o.Hostname.Unset()
}

// GetIntegrationId returns the IntegrationId field value if set, zero value otherwise (both if not set or set to explicit null).
func (o *Cluster) GetIntegrationId() int32 {
	if o == nil || IsNil(o.IntegrationId.Get()) {
		var ret int32
		return ret
	}
	return *o.IntegrationId.Get()
}

// GetIntegrationIdOk returns a tuple with the IntegrationId field value if set, nil otherwise
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *Cluster) GetIntegrationIdOk() (*int32, bool) {
	if o == nil {
		return nil, false
	}
	return o.IntegrationId.Get(), o.IntegrationId.IsSet()
}

// HasIntegrationId returns a boolean if a field has been set.
func (o *Cluster) HasIntegrationId() bool {
	if o != nil && o.IntegrationId.IsSet() {
		return true
	}

	return false
}

// SetIntegrationId gets a reference to the given NullableInt32 and assigns it to the IntegrationId field.
func (o *Cluster) SetIntegrationId(v int32) {
	o.IntegrationId.Set(&v)
}
// SetIntegrationIdNil sets the value for IntegrationId to be an explicit nil
func (o *Cluster) SetIntegrationIdNil() {
	o.IntegrationId.Set(nil)
}

// UnsetIntegrationId ensures that no value is present for IntegrationId, not even an explicit nil
func (o *Cluster) UnsetIntegrationId() {
	o.IntegrationId.Unset()
}

// GetOrgId returns the OrgId field value
func (o *Cluster) GetOrgId() int32 {
	if o == nil {
		var ret int32
		return ret
	}

	return o.OrgId
}

// GetOrgIdOk returns a tuple with the OrgId field value
// and a boolean to check if the value has been set.
func (o *Cluster) GetOrgIdOk() (*int32, bool) {
	if o == nil {
		return nil, false
	}
	return &o.OrgId, true
}

// SetOrgId sets field value
func (o *Cluster) SetOrgId(v int32) {
	o.OrgId = v
}

// GetSettings returns the Settings field value if set, zero value otherwise.
func (o *Cluster) GetSettings() ClusterSettings {
	if o == nil || IsNil(o.Settings) {
		var ret ClusterSettings
		return ret
	}
	return *o.Settings
}

// GetSettingsOk returns a tuple with the Settings field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *Cluster) GetSettingsOk() (*ClusterSettings, bool) {
	if o == nil || IsNil(o.Settings) {
		return nil, false
	}
	return o.Settings, true
}

// HasSettings returns a boolean if a field has been set.
func (o *Cluster) HasSettings() bool {
	if o != nil && !IsNil(o.Settings) {
		return true
	}

	return false
}

// SetSettings gets a reference to the given ClusterSettings and assigns it to the Settings field.
func (o *Cluster) SetSettings(v ClusterSettings) {
	o.Settings = &v
}

// GetCreatedAt returns the CreatedAt field value
func (o *Cluster) GetCreatedAt() time.Time {
	if o == nil {
		var ret time.Time
		return ret
	}

	return o.CreatedAt
}

// GetCreatedAtOk returns a tuple with the CreatedAt field value
// and a boolean to check if the value has been set.
func (o *Cluster) GetCreatedAtOk() (*time.Time, bool) {
	if o == nil {
		return nil, false
	}
	return &o.CreatedAt, true
}

// SetCreatedAt sets field value
func (o *Cluster) SetCreatedAt(v time.Time) {
	o.CreatedAt = v
}

// GetUpdatedAt returns the UpdatedAt field value
func (o *Cluster) GetUpdatedAt() time.Time {
	if o == nil {
		var ret time.Time
		return ret
	}

	return o.UpdatedAt
}

// GetUpdatedAtOk returns a tuple with the UpdatedAt field value
// and a boolean to check if the value has been set.
func (o *Cluster) GetUpdatedAtOk() (*time.Time, bool) {
	if o == nil {
		return nil, false
	}
	return &o.UpdatedAt, true
}

// SetUpdatedAt sets field value
func (o *Cluster) SetUpdatedAt(v time.Time) {
	o.UpdatedAt = v
}

func (o Cluster) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o Cluster) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["id"] = o.Id
	toSerialize["name"] = o.Name
	toSerialize["title"] = o.Title
	toSerialize["status"] = o.Status
	toSerialize["serverless"] = o.Serverless
	toSerialize["demo"] = o.Demo
	toSerialize["wodby"] = o.Wodby
	toSerialize["k3s"] = o.K3s
	toSerialize["singleNode"] = o.SingleNode
	if o.Version.IsSet() {
		toSerialize["version"] = o.Version.Get()
	}
	toSerialize["infraVersion"] = o.InfraVersion
	if o.MinNodeCount.IsSet() {
		toSerialize["minNodeCount"] = o.MinNodeCount.Get()
	}
	if o.MaxNodeCount.IsSet() {
		toSerialize["maxNodeCount"] = o.MaxNodeCount.Get()
	}
	if o.LastNodeCount.IsSet() {
		toSerialize["lastNodeCount"] = o.LastNodeCount.Get()
	}
	if o.Region.IsSet() {
		toSerialize["region"] = o.Region.Get()
	}
	if o.Zone.IsSet() {
		toSerialize["zone"] = o.Zone.Get()
	}
	if o.Ips != nil {
		toSerialize["ips"] = o.Ips
	}
	if o.Hostname.IsSet() {
		toSerialize["hostname"] = o.Hostname.Get()
	}
	if o.IntegrationId.IsSet() {
		toSerialize["integrationId"] = o.IntegrationId.Get()
	}
	toSerialize["orgId"] = o.OrgId
	if !IsNil(o.Settings) {
		toSerialize["settings"] = o.Settings
	}
	toSerialize["createdAt"] = o.CreatedAt
	toSerialize["updatedAt"] = o.UpdatedAt
	return toSerialize, nil
}

func (o *Cluster) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"id",
		"name",
		"title",
		"status",
		"serverless",
		"demo",
		"wodby",
		"k3s",
		"singleNode",
		"infraVersion",
		"orgId",
		"createdAt",
		"updatedAt",
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err;
	}

	for _, requiredProperty := range(requiredProperties) {
		if _, exists := allProperties[requiredProperty]; !exists {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varCluster := _Cluster{}

	decoder := json.NewDecoder(bytes.NewReader(data))
	decoder.DisallowUnknownFields()
	err = decoder.Decode(&varCluster)

	if err != nil {
		return err
	}

	*o = Cluster(varCluster)

	return err
}

type NullableCluster struct {
	value *Cluster
	isSet bool
}

func (v NullableCluster) Get() *Cluster {
	return v.value
}

func (v *NullableCluster) Set(val *Cluster) {
	v.value = val
	v.isSet = true
}

func (v NullableCluster) IsSet() bool {
	return v.isSet
}

func (v *NullableCluster) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableCluster(val *Cluster) *NullableCluster {
	return &NullableCluster{value: val, isSet: true}
}

func (v NullableCluster) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableCluster) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


