/*
Wodby 2 Public API

Public REST API for customer SDKs and code integrations. GraphQL remains internal for the dashboard. This contract is the versioned public surface. 

API version: 1.0.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package client

import (
	"encoding/json"
	"bytes"
	"fmt"
)

// checks if the UpgradeIntegrationProviderRevisionInput type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &UpgradeIntegrationProviderRevisionInput{}

// UpgradeIntegrationProviderRevisionInput struct for UpgradeIntegrationProviderRevisionInput
type UpgradeIntegrationProviderRevisionInput struct {
	// Permanently deletes fields absent from the target revision when the preview allows it.
	DropRemovedFields bool `json:"dropRemovedFields"`
}

type _UpgradeIntegrationProviderRevisionInput UpgradeIntegrationProviderRevisionInput

// NewUpgradeIntegrationProviderRevisionInput instantiates a new UpgradeIntegrationProviderRevisionInput object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewUpgradeIntegrationProviderRevisionInput(dropRemovedFields bool) *UpgradeIntegrationProviderRevisionInput {
	this := UpgradeIntegrationProviderRevisionInput{}
	this.DropRemovedFields = dropRemovedFields
	return &this
}

// NewUpgradeIntegrationProviderRevisionInputWithDefaults instantiates a new UpgradeIntegrationProviderRevisionInput object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewUpgradeIntegrationProviderRevisionInputWithDefaults() *UpgradeIntegrationProviderRevisionInput {
	this := UpgradeIntegrationProviderRevisionInput{}
	return &this
}

// GetDropRemovedFields returns the DropRemovedFields field value
func (o *UpgradeIntegrationProviderRevisionInput) GetDropRemovedFields() bool {
	if o == nil {
		var ret bool
		return ret
	}

	return o.DropRemovedFields
}

// GetDropRemovedFieldsOk returns a tuple with the DropRemovedFields field value
// and a boolean to check if the value has been set.
func (o *UpgradeIntegrationProviderRevisionInput) GetDropRemovedFieldsOk() (*bool, bool) {
	if o == nil {
		return nil, false
	}
	return &o.DropRemovedFields, true
}

// SetDropRemovedFields sets field value
func (o *UpgradeIntegrationProviderRevisionInput) SetDropRemovedFields(v bool) {
	o.DropRemovedFields = v
}

func (o UpgradeIntegrationProviderRevisionInput) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o UpgradeIntegrationProviderRevisionInput) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["dropRemovedFields"] = o.DropRemovedFields
	return toSerialize, nil
}

func (o *UpgradeIntegrationProviderRevisionInput) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"dropRemovedFields",
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err;
	}

	for _, requiredProperty := range(requiredProperties) {
		if _, exists := allProperties[requiredProperty]; !exists {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varUpgradeIntegrationProviderRevisionInput := _UpgradeIntegrationProviderRevisionInput{}

	decoder := json.NewDecoder(bytes.NewReader(data))
	decoder.DisallowUnknownFields()
	err = decoder.Decode(&varUpgradeIntegrationProviderRevisionInput)

	if err != nil {
		return err
	}

	*o = UpgradeIntegrationProviderRevisionInput(varUpgradeIntegrationProviderRevisionInput)

	return err
}

type NullableUpgradeIntegrationProviderRevisionInput struct {
	value *UpgradeIntegrationProviderRevisionInput
	isSet bool
}

func (v NullableUpgradeIntegrationProviderRevisionInput) Get() *UpgradeIntegrationProviderRevisionInput {
	return v.value
}

func (v *NullableUpgradeIntegrationProviderRevisionInput) Set(val *UpgradeIntegrationProviderRevisionInput) {
	v.value = val
	v.isSet = true
}

func (v NullableUpgradeIntegrationProviderRevisionInput) IsSet() bool {
	return v.isSet
}

func (v *NullableUpgradeIntegrationProviderRevisionInput) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableUpgradeIntegrationProviderRevisionInput(val *UpgradeIntegrationProviderRevisionInput) *NullableUpgradeIntegrationProviderRevisionInput {
	return &NullableUpgradeIntegrationProviderRevisionInput{value: val, isSet: true}
}

func (v NullableUpgradeIntegrationProviderRevisionInput) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableUpgradeIntegrationProviderRevisionInput) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


