/*
Wodby 2 Public API

Public REST API for customer SDKs and code integrations. GraphQL remains internal for the dashboard. This contract is the versioned public surface. 

API version: 1.0.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package client

import (
	"encoding/json"
	"bytes"
	"fmt"
)

// checks if the NewAppAuthInput type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &NewAppAuthInput{}

// NewAppAuthInput struct for NewAppAuthInput
type NewAppAuthInput struct {
	AppInstanceId int32 `json:"appInstanceId"`
	// Optional service scope. Required together with appRouteId for route scope.
	AppServiceId NullableInt32 `json:"appServiceId,omitempty"`
	// Optional route scope. Requires appServiceId and must belong to that service.
	AppRouteId NullableInt32 `json:"appRouteId,omitempty"`
	Login string `json:"login"`
	Password string `json:"password"`
	Realm string `json:"realm"`
}

type _NewAppAuthInput NewAppAuthInput

// NewNewAppAuthInput instantiates a new NewAppAuthInput object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewNewAppAuthInput(appInstanceId int32, login string, password string, realm string) *NewAppAuthInput {
	this := NewAppAuthInput{}
	this.AppInstanceId = appInstanceId
	this.Login = login
	this.Password = password
	this.Realm = realm
	return &this
}

// NewNewAppAuthInputWithDefaults instantiates a new NewAppAuthInput object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewNewAppAuthInputWithDefaults() *NewAppAuthInput {
	this := NewAppAuthInput{}
	return &this
}

// GetAppInstanceId returns the AppInstanceId field value
func (o *NewAppAuthInput) GetAppInstanceId() int32 {
	if o == nil {
		var ret int32
		return ret
	}

	return o.AppInstanceId
}

// GetAppInstanceIdOk returns a tuple with the AppInstanceId field value
// and a boolean to check if the value has been set.
func (o *NewAppAuthInput) GetAppInstanceIdOk() (*int32, bool) {
	if o == nil {
		return nil, false
	}
	return &o.AppInstanceId, true
}

// SetAppInstanceId sets field value
func (o *NewAppAuthInput) SetAppInstanceId(v int32) {
	o.AppInstanceId = v
}

// GetAppServiceId returns the AppServiceId field value if set, zero value otherwise (both if not set or set to explicit null).
func (o *NewAppAuthInput) GetAppServiceId() int32 {
	if o == nil || IsNil(o.AppServiceId.Get()) {
		var ret int32
		return ret
	}
	return *o.AppServiceId.Get()
}

// GetAppServiceIdOk returns a tuple with the AppServiceId field value if set, nil otherwise
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *NewAppAuthInput) GetAppServiceIdOk() (*int32, bool) {
	if o == nil {
		return nil, false
	}
	return o.AppServiceId.Get(), o.AppServiceId.IsSet()
}

// HasAppServiceId returns a boolean if a field has been set.
func (o *NewAppAuthInput) HasAppServiceId() bool {
	if o != nil && o.AppServiceId.IsSet() {
		return true
	}

	return false
}

// SetAppServiceId gets a reference to the given NullableInt32 and assigns it to the AppServiceId field.
func (o *NewAppAuthInput) SetAppServiceId(v int32) {
	o.AppServiceId.Set(&v)
}
// SetAppServiceIdNil sets the value for AppServiceId to be an explicit nil
func (o *NewAppAuthInput) SetAppServiceIdNil() {
	o.AppServiceId.Set(nil)
}

// UnsetAppServiceId ensures that no value is present for AppServiceId, not even an explicit nil
func (o *NewAppAuthInput) UnsetAppServiceId() {
	o.AppServiceId.Unset()
}

// GetAppRouteId returns the AppRouteId field value if set, zero value otherwise (both if not set or set to explicit null).
func (o *NewAppAuthInput) GetAppRouteId() int32 {
	if o == nil || IsNil(o.AppRouteId.Get()) {
		var ret int32
		return ret
	}
	return *o.AppRouteId.Get()
}

// GetAppRouteIdOk returns a tuple with the AppRouteId field value if set, nil otherwise
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *NewAppAuthInput) GetAppRouteIdOk() (*int32, bool) {
	if o == nil {
		return nil, false
	}
	return o.AppRouteId.Get(), o.AppRouteId.IsSet()
}

// HasAppRouteId returns a boolean if a field has been set.
func (o *NewAppAuthInput) HasAppRouteId() bool {
	if o != nil && o.AppRouteId.IsSet() {
		return true
	}

	return false
}

// SetAppRouteId gets a reference to the given NullableInt32 and assigns it to the AppRouteId field.
func (o *NewAppAuthInput) SetAppRouteId(v int32) {
	o.AppRouteId.Set(&v)
}
// SetAppRouteIdNil sets the value for AppRouteId to be an explicit nil
func (o *NewAppAuthInput) SetAppRouteIdNil() {
	o.AppRouteId.Set(nil)
}

// UnsetAppRouteId ensures that no value is present for AppRouteId, not even an explicit nil
func (o *NewAppAuthInput) UnsetAppRouteId() {
	o.AppRouteId.Unset()
}

// GetLogin returns the Login field value
func (o *NewAppAuthInput) GetLogin() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Login
}

// GetLoginOk returns a tuple with the Login field value
// and a boolean to check if the value has been set.
func (o *NewAppAuthInput) GetLoginOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Login, true
}

// SetLogin sets field value
func (o *NewAppAuthInput) SetLogin(v string) {
	o.Login = v
}

// GetPassword returns the Password field value
func (o *NewAppAuthInput) GetPassword() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Password
}

// GetPasswordOk returns a tuple with the Password field value
// and a boolean to check if the value has been set.
func (o *NewAppAuthInput) GetPasswordOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Password, true
}

// SetPassword sets field value
func (o *NewAppAuthInput) SetPassword(v string) {
	o.Password = v
}

// GetRealm returns the Realm field value
func (o *NewAppAuthInput) GetRealm() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Realm
}

// GetRealmOk returns a tuple with the Realm field value
// and a boolean to check if the value has been set.
func (o *NewAppAuthInput) GetRealmOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Realm, true
}

// SetRealm sets field value
func (o *NewAppAuthInput) SetRealm(v string) {
	o.Realm = v
}

func (o NewAppAuthInput) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o NewAppAuthInput) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["appInstanceId"] = o.AppInstanceId
	if o.AppServiceId.IsSet() {
		toSerialize["appServiceId"] = o.AppServiceId.Get()
	}
	if o.AppRouteId.IsSet() {
		toSerialize["appRouteId"] = o.AppRouteId.Get()
	}
	toSerialize["login"] = o.Login
	toSerialize["password"] = o.Password
	toSerialize["realm"] = o.Realm
	return toSerialize, nil
}

func (o *NewAppAuthInput) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"appInstanceId",
		"login",
		"password",
		"realm",
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err;
	}

	for _, requiredProperty := range(requiredProperties) {
		if _, exists := allProperties[requiredProperty]; !exists {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varNewAppAuthInput := _NewAppAuthInput{}

	decoder := json.NewDecoder(bytes.NewReader(data))
	decoder.DisallowUnknownFields()
	err = decoder.Decode(&varNewAppAuthInput)

	if err != nil {
		return err
	}

	*o = NewAppAuthInput(varNewAppAuthInput)

	return err
}

type NullableNewAppAuthInput struct {
	value *NewAppAuthInput
	isSet bool
}

func (v NullableNewAppAuthInput) Get() *NewAppAuthInput {
	return v.value
}

func (v *NullableNewAppAuthInput) Set(val *NewAppAuthInput) {
	v.value = val
	v.isSet = true
}

func (v NullableNewAppAuthInput) IsSet() bool {
	return v.isSet
}

func (v *NullableNewAppAuthInput) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableNewAppAuthInput(val *NewAppAuthInput) *NullableNewAppAuthInput {
	return &NullableNewAppAuthInput{value: val, isSet: true}
}

func (v NullableNewAppAuthInput) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableNewAppAuthInput) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


