/*
Wodby 2.0 Public API

Public REST API for customer SDKs and code integrations. GraphQL remains internal for the dashboard. This contract is the versioned public surface. 

API version: 1.0.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package client

import (
	"encoding/json"
	"bytes"
	"fmt"
)

// checks if the BuildSourceInput type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &BuildSourceInput{}

// BuildSourceInput struct for BuildSourceInput
type BuildSourceInput struct {
	BuildSourceType string `json:"buildSourceType"`
	Template NullableString `json:"template,omitempty"`
	NewRepoName NullableString `json:"newRepoName,omitempty"`
	IntegrationID NullableInt32 `json:"integrationID,omitempty"`
	RemoteGitRepoID NullableString `json:"remoteGitRepoID,omitempty"`
	GitRef NullableString `json:"gitRef,omitempty"`
	GitRefType NullableString `json:"gitRefType,omitempty"`
}

type _BuildSourceInput BuildSourceInput

// NewBuildSourceInput instantiates a new BuildSourceInput object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewBuildSourceInput(buildSourceType string) *BuildSourceInput {
	this := BuildSourceInput{}
	this.BuildSourceType = buildSourceType
	return &this
}

// NewBuildSourceInputWithDefaults instantiates a new BuildSourceInput object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewBuildSourceInputWithDefaults() *BuildSourceInput {
	this := BuildSourceInput{}
	return &this
}

// GetBuildSourceType returns the BuildSourceType field value
func (o *BuildSourceInput) GetBuildSourceType() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.BuildSourceType
}

// GetBuildSourceTypeOk returns a tuple with the BuildSourceType field value
// and a boolean to check if the value has been set.
func (o *BuildSourceInput) GetBuildSourceTypeOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.BuildSourceType, true
}

// SetBuildSourceType sets field value
func (o *BuildSourceInput) SetBuildSourceType(v string) {
	o.BuildSourceType = v
}

// GetTemplate returns the Template field value if set, zero value otherwise (both if not set or set to explicit null).
func (o *BuildSourceInput) GetTemplate() string {
	if o == nil || IsNil(o.Template.Get()) {
		var ret string
		return ret
	}
	return *o.Template.Get()
}

// GetTemplateOk returns a tuple with the Template field value if set, nil otherwise
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *BuildSourceInput) GetTemplateOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return o.Template.Get(), o.Template.IsSet()
}

// HasTemplate returns a boolean if a field has been set.
func (o *BuildSourceInput) HasTemplate() bool {
	if o != nil && o.Template.IsSet() {
		return true
	}

	return false
}

// SetTemplate gets a reference to the given NullableString and assigns it to the Template field.
func (o *BuildSourceInput) SetTemplate(v string) {
	o.Template.Set(&v)
}
// SetTemplateNil sets the value for Template to be an explicit nil
func (o *BuildSourceInput) SetTemplateNil() {
	o.Template.Set(nil)
}

// UnsetTemplate ensures that no value is present for Template, not even an explicit nil
func (o *BuildSourceInput) UnsetTemplate() {
	o.Template.Unset()
}

// GetNewRepoName returns the NewRepoName field value if set, zero value otherwise (both if not set or set to explicit null).
func (o *BuildSourceInput) GetNewRepoName() string {
	if o == nil || IsNil(o.NewRepoName.Get()) {
		var ret string
		return ret
	}
	return *o.NewRepoName.Get()
}

// GetNewRepoNameOk returns a tuple with the NewRepoName field value if set, nil otherwise
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *BuildSourceInput) GetNewRepoNameOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return o.NewRepoName.Get(), o.NewRepoName.IsSet()
}

// HasNewRepoName returns a boolean if a field has been set.
func (o *BuildSourceInput) HasNewRepoName() bool {
	if o != nil && o.NewRepoName.IsSet() {
		return true
	}

	return false
}

// SetNewRepoName gets a reference to the given NullableString and assigns it to the NewRepoName field.
func (o *BuildSourceInput) SetNewRepoName(v string) {
	o.NewRepoName.Set(&v)
}
// SetNewRepoNameNil sets the value for NewRepoName to be an explicit nil
func (o *BuildSourceInput) SetNewRepoNameNil() {
	o.NewRepoName.Set(nil)
}

// UnsetNewRepoName ensures that no value is present for NewRepoName, not even an explicit nil
func (o *BuildSourceInput) UnsetNewRepoName() {
	o.NewRepoName.Unset()
}

// GetIntegrationID returns the IntegrationID field value if set, zero value otherwise (both if not set or set to explicit null).
func (o *BuildSourceInput) GetIntegrationID() int32 {
	if o == nil || IsNil(o.IntegrationID.Get()) {
		var ret int32
		return ret
	}
	return *o.IntegrationID.Get()
}

// GetIntegrationIDOk returns a tuple with the IntegrationID field value if set, nil otherwise
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *BuildSourceInput) GetIntegrationIDOk() (*int32, bool) {
	if o == nil {
		return nil, false
	}
	return o.IntegrationID.Get(), o.IntegrationID.IsSet()
}

// HasIntegrationID returns a boolean if a field has been set.
func (o *BuildSourceInput) HasIntegrationID() bool {
	if o != nil && o.IntegrationID.IsSet() {
		return true
	}

	return false
}

// SetIntegrationID gets a reference to the given NullableInt32 and assigns it to the IntegrationID field.
func (o *BuildSourceInput) SetIntegrationID(v int32) {
	o.IntegrationID.Set(&v)
}
// SetIntegrationIDNil sets the value for IntegrationID to be an explicit nil
func (o *BuildSourceInput) SetIntegrationIDNil() {
	o.IntegrationID.Set(nil)
}

// UnsetIntegrationID ensures that no value is present for IntegrationID, not even an explicit nil
func (o *BuildSourceInput) UnsetIntegrationID() {
	o.IntegrationID.Unset()
}

// GetRemoteGitRepoID returns the RemoteGitRepoID field value if set, zero value otherwise (both if not set or set to explicit null).
func (o *BuildSourceInput) GetRemoteGitRepoID() string {
	if o == nil || IsNil(o.RemoteGitRepoID.Get()) {
		var ret string
		return ret
	}
	return *o.RemoteGitRepoID.Get()
}

// GetRemoteGitRepoIDOk returns a tuple with the RemoteGitRepoID field value if set, nil otherwise
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *BuildSourceInput) GetRemoteGitRepoIDOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return o.RemoteGitRepoID.Get(), o.RemoteGitRepoID.IsSet()
}

// HasRemoteGitRepoID returns a boolean if a field has been set.
func (o *BuildSourceInput) HasRemoteGitRepoID() bool {
	if o != nil && o.RemoteGitRepoID.IsSet() {
		return true
	}

	return false
}

// SetRemoteGitRepoID gets a reference to the given NullableString and assigns it to the RemoteGitRepoID field.
func (o *BuildSourceInput) SetRemoteGitRepoID(v string) {
	o.RemoteGitRepoID.Set(&v)
}
// SetRemoteGitRepoIDNil sets the value for RemoteGitRepoID to be an explicit nil
func (o *BuildSourceInput) SetRemoteGitRepoIDNil() {
	o.RemoteGitRepoID.Set(nil)
}

// UnsetRemoteGitRepoID ensures that no value is present for RemoteGitRepoID, not even an explicit nil
func (o *BuildSourceInput) UnsetRemoteGitRepoID() {
	o.RemoteGitRepoID.Unset()
}

// GetGitRef returns the GitRef field value if set, zero value otherwise (both if not set or set to explicit null).
func (o *BuildSourceInput) GetGitRef() string {
	if o == nil || IsNil(o.GitRef.Get()) {
		var ret string
		return ret
	}
	return *o.GitRef.Get()
}

// GetGitRefOk returns a tuple with the GitRef field value if set, nil otherwise
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *BuildSourceInput) GetGitRefOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return o.GitRef.Get(), o.GitRef.IsSet()
}

// HasGitRef returns a boolean if a field has been set.
func (o *BuildSourceInput) HasGitRef() bool {
	if o != nil && o.GitRef.IsSet() {
		return true
	}

	return false
}

// SetGitRef gets a reference to the given NullableString and assigns it to the GitRef field.
func (o *BuildSourceInput) SetGitRef(v string) {
	o.GitRef.Set(&v)
}
// SetGitRefNil sets the value for GitRef to be an explicit nil
func (o *BuildSourceInput) SetGitRefNil() {
	o.GitRef.Set(nil)
}

// UnsetGitRef ensures that no value is present for GitRef, not even an explicit nil
func (o *BuildSourceInput) UnsetGitRef() {
	o.GitRef.Unset()
}

// GetGitRefType returns the GitRefType field value if set, zero value otherwise (both if not set or set to explicit null).
func (o *BuildSourceInput) GetGitRefType() string {
	if o == nil || IsNil(o.GitRefType.Get()) {
		var ret string
		return ret
	}
	return *o.GitRefType.Get()
}

// GetGitRefTypeOk returns a tuple with the GitRefType field value if set, nil otherwise
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *BuildSourceInput) GetGitRefTypeOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return o.GitRefType.Get(), o.GitRefType.IsSet()
}

// HasGitRefType returns a boolean if a field has been set.
func (o *BuildSourceInput) HasGitRefType() bool {
	if o != nil && o.GitRefType.IsSet() {
		return true
	}

	return false
}

// SetGitRefType gets a reference to the given NullableString and assigns it to the GitRefType field.
func (o *BuildSourceInput) SetGitRefType(v string) {
	o.GitRefType.Set(&v)
}
// SetGitRefTypeNil sets the value for GitRefType to be an explicit nil
func (o *BuildSourceInput) SetGitRefTypeNil() {
	o.GitRefType.Set(nil)
}

// UnsetGitRefType ensures that no value is present for GitRefType, not even an explicit nil
func (o *BuildSourceInput) UnsetGitRefType() {
	o.GitRefType.Unset()
}

func (o BuildSourceInput) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o BuildSourceInput) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["buildSourceType"] = o.BuildSourceType
	if o.Template.IsSet() {
		toSerialize["template"] = o.Template.Get()
	}
	if o.NewRepoName.IsSet() {
		toSerialize["newRepoName"] = o.NewRepoName.Get()
	}
	if o.IntegrationID.IsSet() {
		toSerialize["integrationID"] = o.IntegrationID.Get()
	}
	if o.RemoteGitRepoID.IsSet() {
		toSerialize["remoteGitRepoID"] = o.RemoteGitRepoID.Get()
	}
	if o.GitRef.IsSet() {
		toSerialize["gitRef"] = o.GitRef.Get()
	}
	if o.GitRefType.IsSet() {
		toSerialize["gitRefType"] = o.GitRefType.Get()
	}
	return toSerialize, nil
}

func (o *BuildSourceInput) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"buildSourceType",
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err;
	}

	for _, requiredProperty := range(requiredProperties) {
		if _, exists := allProperties[requiredProperty]; !exists {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varBuildSourceInput := _BuildSourceInput{}

	decoder := json.NewDecoder(bytes.NewReader(data))
	decoder.DisallowUnknownFields()
	err = decoder.Decode(&varBuildSourceInput)

	if err != nil {
		return err
	}

	*o = BuildSourceInput(varBuildSourceInput)

	return err
}

type NullableBuildSourceInput struct {
	value *BuildSourceInput
	isSet bool
}

func (v NullableBuildSourceInput) Get() *BuildSourceInput {
	return v.value
}

func (v *NullableBuildSourceInput) Set(val *BuildSourceInput) {
	v.value = val
	v.isSet = true
}

func (v NullableBuildSourceInput) IsSet() bool {
	return v.isSet
}

func (v *NullableBuildSourceInput) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableBuildSourceInput(val *BuildSourceInput) *NullableBuildSourceInput {
	return &NullableBuildSourceInput{value: val, isSet: true}
}

func (v NullableBuildSourceInput) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableBuildSourceInput) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


