/*
Wodby 2 Public API

Public REST API for customer SDKs and code integrations. GraphQL remains internal for the dashboard. This contract is the versioned public surface. 

API version: 1.0.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package client

import (
	"encoding/json"
	"time"
	"bytes"
	"fmt"
)

// checks if the AppInstanceBackupHealth type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &AppInstanceBackupHealth{}

// AppInstanceBackupHealth struct for AppInstanceBackupHealth
type AppInstanceBackupHealth struct {
	FailingSchedulesCount int32 `json:"failingSchedulesCount"`
	LatestFailureAt NullableTime `json:"latestFailureAt,omitempty"`
}

type _AppInstanceBackupHealth AppInstanceBackupHealth

// NewAppInstanceBackupHealth instantiates a new AppInstanceBackupHealth object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewAppInstanceBackupHealth(failingSchedulesCount int32) *AppInstanceBackupHealth {
	this := AppInstanceBackupHealth{}
	this.FailingSchedulesCount = failingSchedulesCount
	return &this
}

// NewAppInstanceBackupHealthWithDefaults instantiates a new AppInstanceBackupHealth object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewAppInstanceBackupHealthWithDefaults() *AppInstanceBackupHealth {
	this := AppInstanceBackupHealth{}
	return &this
}

// GetFailingSchedulesCount returns the FailingSchedulesCount field value
func (o *AppInstanceBackupHealth) GetFailingSchedulesCount() int32 {
	if o == nil {
		var ret int32
		return ret
	}

	return o.FailingSchedulesCount
}

// GetFailingSchedulesCountOk returns a tuple with the FailingSchedulesCount field value
// and a boolean to check if the value has been set.
func (o *AppInstanceBackupHealth) GetFailingSchedulesCountOk() (*int32, bool) {
	if o == nil {
		return nil, false
	}
	return &o.FailingSchedulesCount, true
}

// SetFailingSchedulesCount sets field value
func (o *AppInstanceBackupHealth) SetFailingSchedulesCount(v int32) {
	o.FailingSchedulesCount = v
}

// GetLatestFailureAt returns the LatestFailureAt field value if set, zero value otherwise (both if not set or set to explicit null).
func (o *AppInstanceBackupHealth) GetLatestFailureAt() time.Time {
	if o == nil || IsNil(o.LatestFailureAt.Get()) {
		var ret time.Time
		return ret
	}
	return *o.LatestFailureAt.Get()
}

// GetLatestFailureAtOk returns a tuple with the LatestFailureAt field value if set, nil otherwise
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *AppInstanceBackupHealth) GetLatestFailureAtOk() (*time.Time, bool) {
	if o == nil {
		return nil, false
	}
	return o.LatestFailureAt.Get(), o.LatestFailureAt.IsSet()
}

// HasLatestFailureAt returns a boolean if a field has been set.
func (o *AppInstanceBackupHealth) HasLatestFailureAt() bool {
	if o != nil && o.LatestFailureAt.IsSet() {
		return true
	}

	return false
}

// SetLatestFailureAt gets a reference to the given NullableTime and assigns it to the LatestFailureAt field.
func (o *AppInstanceBackupHealth) SetLatestFailureAt(v time.Time) {
	o.LatestFailureAt.Set(&v)
}
// SetLatestFailureAtNil sets the value for LatestFailureAt to be an explicit nil
func (o *AppInstanceBackupHealth) SetLatestFailureAtNil() {
	o.LatestFailureAt.Set(nil)
}

// UnsetLatestFailureAt ensures that no value is present for LatestFailureAt, not even an explicit nil
func (o *AppInstanceBackupHealth) UnsetLatestFailureAt() {
	o.LatestFailureAt.Unset()
}

func (o AppInstanceBackupHealth) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o AppInstanceBackupHealth) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["failingSchedulesCount"] = o.FailingSchedulesCount
	if o.LatestFailureAt.IsSet() {
		toSerialize["latestFailureAt"] = o.LatestFailureAt.Get()
	}
	return toSerialize, nil
}

func (o *AppInstanceBackupHealth) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"failingSchedulesCount",
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err;
	}

	for _, requiredProperty := range(requiredProperties) {
		if _, exists := allProperties[requiredProperty]; !exists {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varAppInstanceBackupHealth := _AppInstanceBackupHealth{}

	decoder := json.NewDecoder(bytes.NewReader(data))
	decoder.DisallowUnknownFields()
	err = decoder.Decode(&varAppInstanceBackupHealth)

	if err != nil {
		return err
	}

	*o = AppInstanceBackupHealth(varAppInstanceBackupHealth)

	return err
}

type NullableAppInstanceBackupHealth struct {
	value *AppInstanceBackupHealth
	isSet bool
}

func (v NullableAppInstanceBackupHealth) Get() *AppInstanceBackupHealth {
	return v.value
}

func (v *NullableAppInstanceBackupHealth) Set(val *AppInstanceBackupHealth) {
	v.value = val
	v.isSet = true
}

func (v NullableAppInstanceBackupHealth) IsSet() bool {
	return v.isSet
}

func (v *NullableAppInstanceBackupHealth) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableAppInstanceBackupHealth(val *AppInstanceBackupHealth) *NullableAppInstanceBackupHealth {
	return &NullableAppInstanceBackupHealth{value: val, isSet: true}
}

func (v NullableAppInstanceBackupHealth) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableAppInstanceBackupHealth) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


