/*
Wodby 2 Public API

Public REST API for customer SDKs and code integrations. GraphQL remains internal for the dashboard. This contract is the versioned public surface. 

API version: 1.0.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package client

import (
	"encoding/json"
	"time"
	"bytes"
	"fmt"
)

// checks if the AppAccessResource type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &AppAccessResource{}

// AppAccessResource struct for AppAccessResource
type AppAccessResource struct {
	Id int32 `json:"id"`
	Type string `json:"type"`
	Name string `json:"name"`
	ExternalId string `json:"externalId"`
	Status string `json:"status"`
	CreatedAt time.Time `json:"createdAt"`
	UpdatedAt time.Time `json:"updatedAt"`
}

type _AppAccessResource AppAccessResource

// NewAppAccessResource instantiates a new AppAccessResource object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewAppAccessResource(id int32, type_ string, name string, externalId string, status string, createdAt time.Time, updatedAt time.Time) *AppAccessResource {
	this := AppAccessResource{}
	this.Id = id
	this.Type = type_
	this.Name = name
	this.ExternalId = externalId
	this.Status = status
	this.CreatedAt = createdAt
	this.UpdatedAt = updatedAt
	return &this
}

// NewAppAccessResourceWithDefaults instantiates a new AppAccessResource object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewAppAccessResourceWithDefaults() *AppAccessResource {
	this := AppAccessResource{}
	return &this
}

// GetId returns the Id field value
func (o *AppAccessResource) GetId() int32 {
	if o == nil {
		var ret int32
		return ret
	}

	return o.Id
}

// GetIdOk returns a tuple with the Id field value
// and a boolean to check if the value has been set.
func (o *AppAccessResource) GetIdOk() (*int32, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Id, true
}

// SetId sets field value
func (o *AppAccessResource) SetId(v int32) {
	o.Id = v
}

// GetType returns the Type field value
func (o *AppAccessResource) GetType() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Type
}

// GetTypeOk returns a tuple with the Type field value
// and a boolean to check if the value has been set.
func (o *AppAccessResource) GetTypeOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Type, true
}

// SetType sets field value
func (o *AppAccessResource) SetType(v string) {
	o.Type = v
}

// GetName returns the Name field value
func (o *AppAccessResource) GetName() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Name
}

// GetNameOk returns a tuple with the Name field value
// and a boolean to check if the value has been set.
func (o *AppAccessResource) GetNameOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Name, true
}

// SetName sets field value
func (o *AppAccessResource) SetName(v string) {
	o.Name = v
}

// GetExternalId returns the ExternalId field value
func (o *AppAccessResource) GetExternalId() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.ExternalId
}

// GetExternalIdOk returns a tuple with the ExternalId field value
// and a boolean to check if the value has been set.
func (o *AppAccessResource) GetExternalIdOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.ExternalId, true
}

// SetExternalId sets field value
func (o *AppAccessResource) SetExternalId(v string) {
	o.ExternalId = v
}

// GetStatus returns the Status field value
func (o *AppAccessResource) GetStatus() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Status
}

// GetStatusOk returns a tuple with the Status field value
// and a boolean to check if the value has been set.
func (o *AppAccessResource) GetStatusOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Status, true
}

// SetStatus sets field value
func (o *AppAccessResource) SetStatus(v string) {
	o.Status = v
}

// GetCreatedAt returns the CreatedAt field value
func (o *AppAccessResource) GetCreatedAt() time.Time {
	if o == nil {
		var ret time.Time
		return ret
	}

	return o.CreatedAt
}

// GetCreatedAtOk returns a tuple with the CreatedAt field value
// and a boolean to check if the value has been set.
func (o *AppAccessResource) GetCreatedAtOk() (*time.Time, bool) {
	if o == nil {
		return nil, false
	}
	return &o.CreatedAt, true
}

// SetCreatedAt sets field value
func (o *AppAccessResource) SetCreatedAt(v time.Time) {
	o.CreatedAt = v
}

// GetUpdatedAt returns the UpdatedAt field value
func (o *AppAccessResource) GetUpdatedAt() time.Time {
	if o == nil {
		var ret time.Time
		return ret
	}

	return o.UpdatedAt
}

// GetUpdatedAtOk returns a tuple with the UpdatedAt field value
// and a boolean to check if the value has been set.
func (o *AppAccessResource) GetUpdatedAtOk() (*time.Time, bool) {
	if o == nil {
		return nil, false
	}
	return &o.UpdatedAt, true
}

// SetUpdatedAt sets field value
func (o *AppAccessResource) SetUpdatedAt(v time.Time) {
	o.UpdatedAt = v
}

func (o AppAccessResource) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o AppAccessResource) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["id"] = o.Id
	toSerialize["type"] = o.Type
	toSerialize["name"] = o.Name
	toSerialize["externalId"] = o.ExternalId
	toSerialize["status"] = o.Status
	toSerialize["createdAt"] = o.CreatedAt
	toSerialize["updatedAt"] = o.UpdatedAt
	return toSerialize, nil
}

func (o *AppAccessResource) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"id",
		"type",
		"name",
		"externalId",
		"status",
		"createdAt",
		"updatedAt",
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err;
	}

	for _, requiredProperty := range(requiredProperties) {
		if _, exists := allProperties[requiredProperty]; !exists {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varAppAccessResource := _AppAccessResource{}

	decoder := json.NewDecoder(bytes.NewReader(data))
	decoder.DisallowUnknownFields()
	err = decoder.Decode(&varAppAccessResource)

	if err != nil {
		return err
	}

	*o = AppAccessResource(varAppAccessResource)

	return err
}

type NullableAppAccessResource struct {
	value *AppAccessResource
	isSet bool
}

func (v NullableAppAccessResource) Get() *AppAccessResource {
	return v.value
}

func (v *NullableAppAccessResource) Set(val *AppAccessResource) {
	v.value = val
	v.isSet = true
}

func (v NullableAppAccessResource) IsSet() bool {
	return v.isSet
}

func (v *NullableAppAccessResource) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableAppAccessResource(val *AppAccessResource) *NullableAppAccessResource {
	return &NullableAppAccessResource{value: val, isSet: true}
}

func (v NullableAppAccessResource) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableAppAccessResource) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


