/*
Wodby 2.0 Public API

Public REST API for customer SDKs and code integrations. GraphQL remains internal for the dashboard. This contract is the versioned public surface. 

API version: 1.0.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package client

import (
	"encoding/json"
	"time"
	"bytes"
	"fmt"
)

// checks if the Service type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &Service{}

// Service struct for Service
type Service struct {
	Id int32 `json:"id"`
	Name string `json:"name"`
	Title string `json:"title"`
	Type string `json:"type"`
	Status string `json:"status"`
	External bool `json:"external"`
	Public bool `json:"public"`
	RevId int32 `json:"revId"`
	LatestRevNumber int32 `json:"latestRevNumber"`
	OrgId int32 `json:"orgId"`
	CreatedAt time.Time `json:"createdAt"`
	UpdatedAt time.Time `json:"updatedAt"`
}

type _Service Service

// NewService instantiates a new Service object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewService(id int32, name string, title string, type_ string, status string, external bool, public bool, revId int32, latestRevNumber int32, orgId int32, createdAt time.Time, updatedAt time.Time) *Service {
	this := Service{}
	this.Id = id
	this.Name = name
	this.Title = title
	this.Type = type_
	this.Status = status
	this.External = external
	this.Public = public
	this.RevId = revId
	this.LatestRevNumber = latestRevNumber
	this.OrgId = orgId
	this.CreatedAt = createdAt
	this.UpdatedAt = updatedAt
	return &this
}

// NewServiceWithDefaults instantiates a new Service object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewServiceWithDefaults() *Service {
	this := Service{}
	return &this
}

// GetId returns the Id field value
func (o *Service) GetId() int32 {
	if o == nil {
		var ret int32
		return ret
	}

	return o.Id
}

// GetIdOk returns a tuple with the Id field value
// and a boolean to check if the value has been set.
func (o *Service) GetIdOk() (*int32, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Id, true
}

// SetId sets field value
func (o *Service) SetId(v int32) {
	o.Id = v
}

// GetName returns the Name field value
func (o *Service) GetName() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Name
}

// GetNameOk returns a tuple with the Name field value
// and a boolean to check if the value has been set.
func (o *Service) GetNameOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Name, true
}

// SetName sets field value
func (o *Service) SetName(v string) {
	o.Name = v
}

// GetTitle returns the Title field value
func (o *Service) GetTitle() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Title
}

// GetTitleOk returns a tuple with the Title field value
// and a boolean to check if the value has been set.
func (o *Service) GetTitleOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Title, true
}

// SetTitle sets field value
func (o *Service) SetTitle(v string) {
	o.Title = v
}

// GetType returns the Type field value
func (o *Service) GetType() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Type
}

// GetTypeOk returns a tuple with the Type field value
// and a boolean to check if the value has been set.
func (o *Service) GetTypeOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Type, true
}

// SetType sets field value
func (o *Service) SetType(v string) {
	o.Type = v
}

// GetStatus returns the Status field value
func (o *Service) GetStatus() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Status
}

// GetStatusOk returns a tuple with the Status field value
// and a boolean to check if the value has been set.
func (o *Service) GetStatusOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Status, true
}

// SetStatus sets field value
func (o *Service) SetStatus(v string) {
	o.Status = v
}

// GetExternal returns the External field value
func (o *Service) GetExternal() bool {
	if o == nil {
		var ret bool
		return ret
	}

	return o.External
}

// GetExternalOk returns a tuple with the External field value
// and a boolean to check if the value has been set.
func (o *Service) GetExternalOk() (*bool, bool) {
	if o == nil {
		return nil, false
	}
	return &o.External, true
}

// SetExternal sets field value
func (o *Service) SetExternal(v bool) {
	o.External = v
}

// GetPublic returns the Public field value
func (o *Service) GetPublic() bool {
	if o == nil {
		var ret bool
		return ret
	}

	return o.Public
}

// GetPublicOk returns a tuple with the Public field value
// and a boolean to check if the value has been set.
func (o *Service) GetPublicOk() (*bool, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Public, true
}

// SetPublic sets field value
func (o *Service) SetPublic(v bool) {
	o.Public = v
}

// GetRevId returns the RevId field value
func (o *Service) GetRevId() int32 {
	if o == nil {
		var ret int32
		return ret
	}

	return o.RevId
}

// GetRevIdOk returns a tuple with the RevId field value
// and a boolean to check if the value has been set.
func (o *Service) GetRevIdOk() (*int32, bool) {
	if o == nil {
		return nil, false
	}
	return &o.RevId, true
}

// SetRevId sets field value
func (o *Service) SetRevId(v int32) {
	o.RevId = v
}

// GetLatestRevNumber returns the LatestRevNumber field value
func (o *Service) GetLatestRevNumber() int32 {
	if o == nil {
		var ret int32
		return ret
	}

	return o.LatestRevNumber
}

// GetLatestRevNumberOk returns a tuple with the LatestRevNumber field value
// and a boolean to check if the value has been set.
func (o *Service) GetLatestRevNumberOk() (*int32, bool) {
	if o == nil {
		return nil, false
	}
	return &o.LatestRevNumber, true
}

// SetLatestRevNumber sets field value
func (o *Service) SetLatestRevNumber(v int32) {
	o.LatestRevNumber = v
}

// GetOrgId returns the OrgId field value
func (o *Service) GetOrgId() int32 {
	if o == nil {
		var ret int32
		return ret
	}

	return o.OrgId
}

// GetOrgIdOk returns a tuple with the OrgId field value
// and a boolean to check if the value has been set.
func (o *Service) GetOrgIdOk() (*int32, bool) {
	if o == nil {
		return nil, false
	}
	return &o.OrgId, true
}

// SetOrgId sets field value
func (o *Service) SetOrgId(v int32) {
	o.OrgId = v
}

// GetCreatedAt returns the CreatedAt field value
func (o *Service) GetCreatedAt() time.Time {
	if o == nil {
		var ret time.Time
		return ret
	}

	return o.CreatedAt
}

// GetCreatedAtOk returns a tuple with the CreatedAt field value
// and a boolean to check if the value has been set.
func (o *Service) GetCreatedAtOk() (*time.Time, bool) {
	if o == nil {
		return nil, false
	}
	return &o.CreatedAt, true
}

// SetCreatedAt sets field value
func (o *Service) SetCreatedAt(v time.Time) {
	o.CreatedAt = v
}

// GetUpdatedAt returns the UpdatedAt field value
func (o *Service) GetUpdatedAt() time.Time {
	if o == nil {
		var ret time.Time
		return ret
	}

	return o.UpdatedAt
}

// GetUpdatedAtOk returns a tuple with the UpdatedAt field value
// and a boolean to check if the value has been set.
func (o *Service) GetUpdatedAtOk() (*time.Time, bool) {
	if o == nil {
		return nil, false
	}
	return &o.UpdatedAt, true
}

// SetUpdatedAt sets field value
func (o *Service) SetUpdatedAt(v time.Time) {
	o.UpdatedAt = v
}

func (o Service) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o Service) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["id"] = o.Id
	toSerialize["name"] = o.Name
	toSerialize["title"] = o.Title
	toSerialize["type"] = o.Type
	toSerialize["status"] = o.Status
	toSerialize["external"] = o.External
	toSerialize["public"] = o.Public
	toSerialize["revId"] = o.RevId
	toSerialize["latestRevNumber"] = o.LatestRevNumber
	toSerialize["orgId"] = o.OrgId
	toSerialize["createdAt"] = o.CreatedAt
	toSerialize["updatedAt"] = o.UpdatedAt
	return toSerialize, nil
}

func (o *Service) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"id",
		"name",
		"title",
		"type",
		"status",
		"external",
		"public",
		"revId",
		"latestRevNumber",
		"orgId",
		"createdAt",
		"updatedAt",
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err;
	}

	for _, requiredProperty := range(requiredProperties) {
		if _, exists := allProperties[requiredProperty]; !exists {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varService := _Service{}

	decoder := json.NewDecoder(bytes.NewReader(data))
	decoder.DisallowUnknownFields()
	err = decoder.Decode(&varService)

	if err != nil {
		return err
	}

	*o = Service(varService)

	return err
}

type NullableService struct {
	value *Service
	isSet bool
}

func (v NullableService) Get() *Service {
	return v.value
}

func (v *NullableService) Set(val *Service) {
	v.value = val
	v.isSet = true
}

func (v NullableService) IsSet() bool {
	return v.isSet
}

func (v *NullableService) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableService(val *Service) *NullableService {
	return &NullableService{value: val, isSet: true}
}

func (v NullableService) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableService) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


