/*
Wodby 2 Public API

Public REST API for customer SDKs and code integrations. GraphQL remains internal for the dashboard. This contract is the versioned public surface. 

API version: 1.0.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package client

import (
	"encoding/json"
	"time"
	"bytes"
	"fmt"
)

// checks if the AppServiceToken type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &AppServiceToken{}

// AppServiceToken struct for AppServiceToken
type AppServiceToken struct {
	Id int32 `json:"id"`
	AppServiceId int32 `json:"appServiceId"`
	Name string `json:"name"`
	Value string `json:"value"`
	ValueSecretId NullableInt32 `json:"valueSecretId,omitempty"`
	EnvType NullableString `json:"envType,omitempty"`
	CreatedAt time.Time `json:"createdAt"`
}

type _AppServiceToken AppServiceToken

// NewAppServiceToken instantiates a new AppServiceToken object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewAppServiceToken(id int32, appServiceId int32, name string, value string, createdAt time.Time) *AppServiceToken {
	this := AppServiceToken{}
	this.Id = id
	this.AppServiceId = appServiceId
	this.Name = name
	this.Value = value
	this.CreatedAt = createdAt
	return &this
}

// NewAppServiceTokenWithDefaults instantiates a new AppServiceToken object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewAppServiceTokenWithDefaults() *AppServiceToken {
	this := AppServiceToken{}
	return &this
}

// GetId returns the Id field value
func (o *AppServiceToken) GetId() int32 {
	if o == nil {
		var ret int32
		return ret
	}

	return o.Id
}

// GetIdOk returns a tuple with the Id field value
// and a boolean to check if the value has been set.
func (o *AppServiceToken) GetIdOk() (*int32, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Id, true
}

// SetId sets field value
func (o *AppServiceToken) SetId(v int32) {
	o.Id = v
}

// GetAppServiceId returns the AppServiceId field value
func (o *AppServiceToken) GetAppServiceId() int32 {
	if o == nil {
		var ret int32
		return ret
	}

	return o.AppServiceId
}

// GetAppServiceIdOk returns a tuple with the AppServiceId field value
// and a boolean to check if the value has been set.
func (o *AppServiceToken) GetAppServiceIdOk() (*int32, bool) {
	if o == nil {
		return nil, false
	}
	return &o.AppServiceId, true
}

// SetAppServiceId sets field value
func (o *AppServiceToken) SetAppServiceId(v int32) {
	o.AppServiceId = v
}

// GetName returns the Name field value
func (o *AppServiceToken) GetName() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Name
}

// GetNameOk returns a tuple with the Name field value
// and a boolean to check if the value has been set.
func (o *AppServiceToken) GetNameOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Name, true
}

// SetName sets field value
func (o *AppServiceToken) SetName(v string) {
	o.Name = v
}

// GetValue returns the Value field value
func (o *AppServiceToken) GetValue() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Value
}

// GetValueOk returns a tuple with the Value field value
// and a boolean to check if the value has been set.
func (o *AppServiceToken) GetValueOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Value, true
}

// SetValue sets field value
func (o *AppServiceToken) SetValue(v string) {
	o.Value = v
}

// GetValueSecretId returns the ValueSecretId field value if set, zero value otherwise (both if not set or set to explicit null).
func (o *AppServiceToken) GetValueSecretId() int32 {
	if o == nil || IsNil(o.ValueSecretId.Get()) {
		var ret int32
		return ret
	}
	return *o.ValueSecretId.Get()
}

// GetValueSecretIdOk returns a tuple with the ValueSecretId field value if set, nil otherwise
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *AppServiceToken) GetValueSecretIdOk() (*int32, bool) {
	if o == nil {
		return nil, false
	}
	return o.ValueSecretId.Get(), o.ValueSecretId.IsSet()
}

// HasValueSecretId returns a boolean if a field has been set.
func (o *AppServiceToken) HasValueSecretId() bool {
	if o != nil && o.ValueSecretId.IsSet() {
		return true
	}

	return false
}

// SetValueSecretId gets a reference to the given NullableInt32 and assigns it to the ValueSecretId field.
func (o *AppServiceToken) SetValueSecretId(v int32) {
	o.ValueSecretId.Set(&v)
}
// SetValueSecretIdNil sets the value for ValueSecretId to be an explicit nil
func (o *AppServiceToken) SetValueSecretIdNil() {
	o.ValueSecretId.Set(nil)
}

// UnsetValueSecretId ensures that no value is present for ValueSecretId, not even an explicit nil
func (o *AppServiceToken) UnsetValueSecretId() {
	o.ValueSecretId.Unset()
}

// GetEnvType returns the EnvType field value if set, zero value otherwise (both if not set or set to explicit null).
func (o *AppServiceToken) GetEnvType() string {
	if o == nil || IsNil(o.EnvType.Get()) {
		var ret string
		return ret
	}
	return *o.EnvType.Get()
}

// GetEnvTypeOk returns a tuple with the EnvType field value if set, nil otherwise
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *AppServiceToken) GetEnvTypeOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return o.EnvType.Get(), o.EnvType.IsSet()
}

// HasEnvType returns a boolean if a field has been set.
func (o *AppServiceToken) HasEnvType() bool {
	if o != nil && o.EnvType.IsSet() {
		return true
	}

	return false
}

// SetEnvType gets a reference to the given NullableString and assigns it to the EnvType field.
func (o *AppServiceToken) SetEnvType(v string) {
	o.EnvType.Set(&v)
}
// SetEnvTypeNil sets the value for EnvType to be an explicit nil
func (o *AppServiceToken) SetEnvTypeNil() {
	o.EnvType.Set(nil)
}

// UnsetEnvType ensures that no value is present for EnvType, not even an explicit nil
func (o *AppServiceToken) UnsetEnvType() {
	o.EnvType.Unset()
}

// GetCreatedAt returns the CreatedAt field value
func (o *AppServiceToken) GetCreatedAt() time.Time {
	if o == nil {
		var ret time.Time
		return ret
	}

	return o.CreatedAt
}

// GetCreatedAtOk returns a tuple with the CreatedAt field value
// and a boolean to check if the value has been set.
func (o *AppServiceToken) GetCreatedAtOk() (*time.Time, bool) {
	if o == nil {
		return nil, false
	}
	return &o.CreatedAt, true
}

// SetCreatedAt sets field value
func (o *AppServiceToken) SetCreatedAt(v time.Time) {
	o.CreatedAt = v
}

func (o AppServiceToken) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o AppServiceToken) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["id"] = o.Id
	toSerialize["appServiceId"] = o.AppServiceId
	toSerialize["name"] = o.Name
	toSerialize["value"] = o.Value
	if o.ValueSecretId.IsSet() {
		toSerialize["valueSecretId"] = o.ValueSecretId.Get()
	}
	if o.EnvType.IsSet() {
		toSerialize["envType"] = o.EnvType.Get()
	}
	toSerialize["createdAt"] = o.CreatedAt
	return toSerialize, nil
}

func (o *AppServiceToken) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"id",
		"appServiceId",
		"name",
		"value",
		"createdAt",
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err;
	}

	for _, requiredProperty := range(requiredProperties) {
		if _, exists := allProperties[requiredProperty]; !exists {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varAppServiceToken := _AppServiceToken{}

	decoder := json.NewDecoder(bytes.NewReader(data))
	decoder.DisallowUnknownFields()
	err = decoder.Decode(&varAppServiceToken)

	if err != nil {
		return err
	}

	*o = AppServiceToken(varAppServiceToken)

	return err
}

type NullableAppServiceToken struct {
	value *AppServiceToken
	isSet bool
}

func (v NullableAppServiceToken) Get() *AppServiceToken {
	return v.value
}

func (v *NullableAppServiceToken) Set(val *AppServiceToken) {
	v.value = val
	v.isSet = true
}

func (v NullableAppServiceToken) IsSet() bool {
	return v.isSet
}

func (v *NullableAppServiceToken) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableAppServiceToken(val *AppServiceToken) *NullableAppServiceToken {
	return &NullableAppServiceToken{value: val, isSet: true}
}

func (v NullableAppServiceToken) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableAppServiceToken) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


