/*
Wodby 2.0 Public API

Public REST API for customer SDKs and code integrations. GraphQL remains internal for the dashboard. This contract is the versioned public surface. 

API version: 1.0.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package client

import (
	"encoding/json"
)

// checks if the CreateBuildRequest type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &CreateBuildRequest{}

// CreateBuildRequest Specify either appServiceId for one service or appServiceIds for a multi-service build.
type CreateBuildRequest struct {
	AppServiceId *int32 `json:"appServiceId,omitempty"`
	AppServiceIds []int32 `json:"appServiceIds,omitempty"`
}

// NewCreateBuildRequest instantiates a new CreateBuildRequest object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewCreateBuildRequest() *CreateBuildRequest {
	this := CreateBuildRequest{}
	return &this
}

// NewCreateBuildRequestWithDefaults instantiates a new CreateBuildRequest object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewCreateBuildRequestWithDefaults() *CreateBuildRequest {
	this := CreateBuildRequest{}
	return &this
}

// GetAppServiceId returns the AppServiceId field value if set, zero value otherwise.
func (o *CreateBuildRequest) GetAppServiceId() int32 {
	if o == nil || IsNil(o.AppServiceId) {
		var ret int32
		return ret
	}
	return *o.AppServiceId
}

// GetAppServiceIdOk returns a tuple with the AppServiceId field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *CreateBuildRequest) GetAppServiceIdOk() (*int32, bool) {
	if o == nil || IsNil(o.AppServiceId) {
		return nil, false
	}
	return o.AppServiceId, true
}

// HasAppServiceId returns a boolean if a field has been set.
func (o *CreateBuildRequest) HasAppServiceId() bool {
	if o != nil && !IsNil(o.AppServiceId) {
		return true
	}

	return false
}

// SetAppServiceId gets a reference to the given int32 and assigns it to the AppServiceId field.
func (o *CreateBuildRequest) SetAppServiceId(v int32) {
	o.AppServiceId = &v
}

// GetAppServiceIds returns the AppServiceIds field value if set, zero value otherwise.
func (o *CreateBuildRequest) GetAppServiceIds() []int32 {
	if o == nil || IsNil(o.AppServiceIds) {
		var ret []int32
		return ret
	}
	return o.AppServiceIds
}

// GetAppServiceIdsOk returns a tuple with the AppServiceIds field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *CreateBuildRequest) GetAppServiceIdsOk() ([]int32, bool) {
	if o == nil || IsNil(o.AppServiceIds) {
		return nil, false
	}
	return o.AppServiceIds, true
}

// HasAppServiceIds returns a boolean if a field has been set.
func (o *CreateBuildRequest) HasAppServiceIds() bool {
	if o != nil && !IsNil(o.AppServiceIds) {
		return true
	}

	return false
}

// SetAppServiceIds gets a reference to the given []int32 and assigns it to the AppServiceIds field.
func (o *CreateBuildRequest) SetAppServiceIds(v []int32) {
	o.AppServiceIds = v
}

func (o CreateBuildRequest) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o CreateBuildRequest) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if !IsNil(o.AppServiceId) {
		toSerialize["appServiceId"] = o.AppServiceId
	}
	if !IsNil(o.AppServiceIds) {
		toSerialize["appServiceIds"] = o.AppServiceIds
	}
	return toSerialize, nil
}

type NullableCreateBuildRequest struct {
	value *CreateBuildRequest
	isSet bool
}

func (v NullableCreateBuildRequest) Get() *CreateBuildRequest {
	return v.value
}

func (v *NullableCreateBuildRequest) Set(val *CreateBuildRequest) {
	v.value = val
	v.isSet = true
}

func (v NullableCreateBuildRequest) IsSet() bool {
	return v.isSet
}

func (v *NullableCreateBuildRequest) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableCreateBuildRequest(val *CreateBuildRequest) *NullableCreateBuildRequest {
	return &NullableCreateBuildRequest{value: val, isSet: true}
}

func (v NullableCreateBuildRequest) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableCreateBuildRequest) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


