/*
Wodby 2 Public API

Public REST API for customer SDKs and code integrations. GraphQL remains internal for the dashboard. This contract is the versioned public surface. 

API version: 1.0.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package client

import (
	"encoding/json"
	"fmt"
)

// AppRouteSettingName the model 'AppRouteSettingName'
type AppRouteSettingName string

// List of AppRouteSettingName
const (
	HTTPS_REDIRECT AppRouteSettingName = "HTTPS_REDIRECT"
	NO_INDEX AppRouteSettingName = "NO_INDEX"
	REQUEST_BODY_SIZE AppRouteSettingName = "REQUEST_BODY_SIZE"
	SESSION_AFFINITY AppRouteSettingName = "SESSION_AFFINITY"
	PATH_REWRITE AppRouteSettingName = "PATH_REWRITE"
	HSTS AppRouteSettingName = "HSTS"
	REQUEST_TIMEOUT AppRouteSettingName = "REQUEST_TIMEOUT"
	BACKEND_REQUEST_TIMEOUT AppRouteSettingName = "BACKEND_REQUEST_TIMEOUT"
)

// All allowed values of AppRouteSettingName enum
var AllowedAppRouteSettingNameEnumValues = []AppRouteSettingName{
	"HTTPS_REDIRECT",
	"NO_INDEX",
	"REQUEST_BODY_SIZE",
	"SESSION_AFFINITY",
	"PATH_REWRITE",
	"HSTS",
	"REQUEST_TIMEOUT",
	"BACKEND_REQUEST_TIMEOUT",
}

func (v *AppRouteSettingName) UnmarshalJSON(src []byte) error {
	var value string
	err := json.Unmarshal(src, &value)
	if err != nil {
		return err
	}
	enumTypeValue := AppRouteSettingName(value)
	for _, existing := range AllowedAppRouteSettingNameEnumValues {
		if existing == enumTypeValue {
			*v = enumTypeValue
			return nil
		}
	}

	return fmt.Errorf("%+v is not a valid AppRouteSettingName", value)
}

// NewAppRouteSettingNameFromValue returns a pointer to a valid AppRouteSettingName
// for the value passed as argument, or an error if the value passed is not allowed by the enum
func NewAppRouteSettingNameFromValue(v string) (*AppRouteSettingName, error) {
	ev := AppRouteSettingName(v)
	if ev.IsValid() {
		return &ev, nil
	} else {
		return nil, fmt.Errorf("invalid value '%v' for AppRouteSettingName: valid values are %v", v, AllowedAppRouteSettingNameEnumValues)
	}
}

// IsValid return true if the value is valid for the enum, false otherwise
func (v AppRouteSettingName) IsValid() bool {
	for _, existing := range AllowedAppRouteSettingNameEnumValues {
		if existing == v {
			return true
		}
	}
	return false
}

// Ptr returns reference to AppRouteSettingName value
func (v AppRouteSettingName) Ptr() *AppRouteSettingName {
	return &v
}

type NullableAppRouteSettingName struct {
	value *AppRouteSettingName
	isSet bool
}

func (v NullableAppRouteSettingName) Get() *AppRouteSettingName {
	return v.value
}

func (v *NullableAppRouteSettingName) Set(val *AppRouteSettingName) {
	v.value = val
	v.isSet = true
}

func (v NullableAppRouteSettingName) IsSet() bool {
	return v.isSet
}

func (v *NullableAppRouteSettingName) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableAppRouteSettingName(val *AppRouteSettingName) *NullableAppRouteSettingName {
	return &NullableAppRouteSettingName{value: val, isSet: true}
}

func (v NullableAppRouteSettingName) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableAppRouteSettingName) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}

