/*
Wodby 2 Public API

Public REST API for customer SDKs and code integrations. GraphQL remains internal for the dashboard. This contract is the versioned public surface. 

API version: 1.0.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package client

import (
	"encoding/json"
	"bytes"
	"fmt"
)

// checks if the AppAccessProviderConfiguration type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &AppAccessProviderConfiguration{}

// AppAccessProviderConfiguration struct for AppAccessProviderConfiguration
type AppAccessProviderConfiguration struct {
	Mode string `json:"mode"`
	EndpointHostMode string `json:"endpointHostMode"`
	Fields []AppAccessProviderField `json:"fields"`
}

type _AppAccessProviderConfiguration AppAccessProviderConfiguration

// NewAppAccessProviderConfiguration instantiates a new AppAccessProviderConfiguration object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewAppAccessProviderConfiguration(mode string, endpointHostMode string, fields []AppAccessProviderField) *AppAccessProviderConfiguration {
	this := AppAccessProviderConfiguration{}
	this.Mode = mode
	this.EndpointHostMode = endpointHostMode
	this.Fields = fields
	return &this
}

// NewAppAccessProviderConfigurationWithDefaults instantiates a new AppAccessProviderConfiguration object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewAppAccessProviderConfigurationWithDefaults() *AppAccessProviderConfiguration {
	this := AppAccessProviderConfiguration{}
	return &this
}

// GetMode returns the Mode field value
func (o *AppAccessProviderConfiguration) GetMode() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Mode
}

// GetModeOk returns a tuple with the Mode field value
// and a boolean to check if the value has been set.
func (o *AppAccessProviderConfiguration) GetModeOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Mode, true
}

// SetMode sets field value
func (o *AppAccessProviderConfiguration) SetMode(v string) {
	o.Mode = v
}

// GetEndpointHostMode returns the EndpointHostMode field value
func (o *AppAccessProviderConfiguration) GetEndpointHostMode() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.EndpointHostMode
}

// GetEndpointHostModeOk returns a tuple with the EndpointHostMode field value
// and a boolean to check if the value has been set.
func (o *AppAccessProviderConfiguration) GetEndpointHostModeOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.EndpointHostMode, true
}

// SetEndpointHostMode sets field value
func (o *AppAccessProviderConfiguration) SetEndpointHostMode(v string) {
	o.EndpointHostMode = v
}

// GetFields returns the Fields field value
func (o *AppAccessProviderConfiguration) GetFields() []AppAccessProviderField {
	if o == nil {
		var ret []AppAccessProviderField
		return ret
	}

	return o.Fields
}

// GetFieldsOk returns a tuple with the Fields field value
// and a boolean to check if the value has been set.
func (o *AppAccessProviderConfiguration) GetFieldsOk() ([]AppAccessProviderField, bool) {
	if o == nil {
		return nil, false
	}
	return o.Fields, true
}

// SetFields sets field value
func (o *AppAccessProviderConfiguration) SetFields(v []AppAccessProviderField) {
	o.Fields = v
}

func (o AppAccessProviderConfiguration) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o AppAccessProviderConfiguration) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["mode"] = o.Mode
	toSerialize["endpointHostMode"] = o.EndpointHostMode
	toSerialize["fields"] = o.Fields
	return toSerialize, nil
}

func (o *AppAccessProviderConfiguration) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"mode",
		"endpointHostMode",
		"fields",
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err;
	}

	for _, requiredProperty := range(requiredProperties) {
		if _, exists := allProperties[requiredProperty]; !exists {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varAppAccessProviderConfiguration := _AppAccessProviderConfiguration{}

	decoder := json.NewDecoder(bytes.NewReader(data))
	decoder.DisallowUnknownFields()
	err = decoder.Decode(&varAppAccessProviderConfiguration)

	if err != nil {
		return err
	}

	*o = AppAccessProviderConfiguration(varAppAccessProviderConfiguration)

	return err
}

type NullableAppAccessProviderConfiguration struct {
	value *AppAccessProviderConfiguration
	isSet bool
}

func (v NullableAppAccessProviderConfiguration) Get() *AppAccessProviderConfiguration {
	return v.value
}

func (v *NullableAppAccessProviderConfiguration) Set(val *AppAccessProviderConfiguration) {
	v.value = val
	v.isSet = true
}

func (v NullableAppAccessProviderConfiguration) IsSet() bool {
	return v.isSet
}

func (v *NullableAppAccessProviderConfiguration) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableAppAccessProviderConfiguration(val *AppAccessProviderConfiguration) *NullableAppAccessProviderConfiguration {
	return &NullableAppAccessProviderConfiguration{value: val, isSet: true}
}

func (v NullableAppAccessProviderConfiguration) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableAppAccessProviderConfiguration) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


