/*
Wodby 2 Public API

Public REST API for customer SDKs and code integrations. GraphQL remains internal for the dashboard. This contract is the versioned public surface. 

API version: 1.0.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package client

import (
	"encoding/json"
	"bytes"
	"fmt"
)

// checks if the NewIntegrationInput type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &NewIntegrationInput{}

// NewIntegrationInput struct for NewIntegrationInput
type NewIntegrationInput struct {
	// Optional for API-key requests; defaults to the API key's organization.
	OrgId *int32 `json:"orgId,omitempty"`
	ProviderId int32 `json:"providerId"`
	Title string `json:"title"`
	Kinds []string `json:"kinds"`
	Auth NullableString `json:"auth,omitempty"`
	ProjectId NullableInt32 `json:"projectId,omitempty"`
	FieldsInput []FieldInput `json:"fieldsInput,omitempty"`
	Scope NullableString `json:"scope,omitempty"`
	EnvironmentPolicy *IntegrationEnvironmentPolicyInput `json:"environmentPolicy,omitempty"`
}

type _NewIntegrationInput NewIntegrationInput

// NewNewIntegrationInput instantiates a new NewIntegrationInput object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewNewIntegrationInput(providerId int32, title string, kinds []string) *NewIntegrationInput {
	this := NewIntegrationInput{}
	this.ProviderId = providerId
	this.Title = title
	this.Kinds = kinds
	return &this
}

// NewNewIntegrationInputWithDefaults instantiates a new NewIntegrationInput object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewNewIntegrationInputWithDefaults() *NewIntegrationInput {
	this := NewIntegrationInput{}
	return &this
}

// GetOrgId returns the OrgId field value if set, zero value otherwise.
func (o *NewIntegrationInput) GetOrgId() int32 {
	if o == nil || IsNil(o.OrgId) {
		var ret int32
		return ret
	}
	return *o.OrgId
}

// GetOrgIdOk returns a tuple with the OrgId field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *NewIntegrationInput) GetOrgIdOk() (*int32, bool) {
	if o == nil || IsNil(o.OrgId) {
		return nil, false
	}
	return o.OrgId, true
}

// HasOrgId returns a boolean if a field has been set.
func (o *NewIntegrationInput) HasOrgId() bool {
	if o != nil && !IsNil(o.OrgId) {
		return true
	}

	return false
}

// SetOrgId gets a reference to the given int32 and assigns it to the OrgId field.
func (o *NewIntegrationInput) SetOrgId(v int32) {
	o.OrgId = &v
}

// GetProviderId returns the ProviderId field value
func (o *NewIntegrationInput) GetProviderId() int32 {
	if o == nil {
		var ret int32
		return ret
	}

	return o.ProviderId
}

// GetProviderIdOk returns a tuple with the ProviderId field value
// and a boolean to check if the value has been set.
func (o *NewIntegrationInput) GetProviderIdOk() (*int32, bool) {
	if o == nil {
		return nil, false
	}
	return &o.ProviderId, true
}

// SetProviderId sets field value
func (o *NewIntegrationInput) SetProviderId(v int32) {
	o.ProviderId = v
}

// GetTitle returns the Title field value
func (o *NewIntegrationInput) GetTitle() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Title
}

// GetTitleOk returns a tuple with the Title field value
// and a boolean to check if the value has been set.
func (o *NewIntegrationInput) GetTitleOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Title, true
}

// SetTitle sets field value
func (o *NewIntegrationInput) SetTitle(v string) {
	o.Title = v
}

// GetKinds returns the Kinds field value
func (o *NewIntegrationInput) GetKinds() []string {
	if o == nil {
		var ret []string
		return ret
	}

	return o.Kinds
}

// GetKindsOk returns a tuple with the Kinds field value
// and a boolean to check if the value has been set.
func (o *NewIntegrationInput) GetKindsOk() ([]string, bool) {
	if o == nil {
		return nil, false
	}
	return o.Kinds, true
}

// SetKinds sets field value
func (o *NewIntegrationInput) SetKinds(v []string) {
	o.Kinds = v
}

// GetAuth returns the Auth field value if set, zero value otherwise (both if not set or set to explicit null).
func (o *NewIntegrationInput) GetAuth() string {
	if o == nil || IsNil(o.Auth.Get()) {
		var ret string
		return ret
	}
	return *o.Auth.Get()
}

// GetAuthOk returns a tuple with the Auth field value if set, nil otherwise
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *NewIntegrationInput) GetAuthOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return o.Auth.Get(), o.Auth.IsSet()
}

// HasAuth returns a boolean if a field has been set.
func (o *NewIntegrationInput) HasAuth() bool {
	if o != nil && o.Auth.IsSet() {
		return true
	}

	return false
}

// SetAuth gets a reference to the given NullableString and assigns it to the Auth field.
func (o *NewIntegrationInput) SetAuth(v string) {
	o.Auth.Set(&v)
}
// SetAuthNil sets the value for Auth to be an explicit nil
func (o *NewIntegrationInput) SetAuthNil() {
	o.Auth.Set(nil)
}

// UnsetAuth ensures that no value is present for Auth, not even an explicit nil
func (o *NewIntegrationInput) UnsetAuth() {
	o.Auth.Unset()
}

// GetProjectId returns the ProjectId field value if set, zero value otherwise (both if not set or set to explicit null).
func (o *NewIntegrationInput) GetProjectId() int32 {
	if o == nil || IsNil(o.ProjectId.Get()) {
		var ret int32
		return ret
	}
	return *o.ProjectId.Get()
}

// GetProjectIdOk returns a tuple with the ProjectId field value if set, nil otherwise
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *NewIntegrationInput) GetProjectIdOk() (*int32, bool) {
	if o == nil {
		return nil, false
	}
	return o.ProjectId.Get(), o.ProjectId.IsSet()
}

// HasProjectId returns a boolean if a field has been set.
func (o *NewIntegrationInput) HasProjectId() bool {
	if o != nil && o.ProjectId.IsSet() {
		return true
	}

	return false
}

// SetProjectId gets a reference to the given NullableInt32 and assigns it to the ProjectId field.
func (o *NewIntegrationInput) SetProjectId(v int32) {
	o.ProjectId.Set(&v)
}
// SetProjectIdNil sets the value for ProjectId to be an explicit nil
func (o *NewIntegrationInput) SetProjectIdNil() {
	o.ProjectId.Set(nil)
}

// UnsetProjectId ensures that no value is present for ProjectId, not even an explicit nil
func (o *NewIntegrationInput) UnsetProjectId() {
	o.ProjectId.Unset()
}

// GetFieldsInput returns the FieldsInput field value if set, zero value otherwise.
func (o *NewIntegrationInput) GetFieldsInput() []FieldInput {
	if o == nil || IsNil(o.FieldsInput) {
		var ret []FieldInput
		return ret
	}
	return o.FieldsInput
}

// GetFieldsInputOk returns a tuple with the FieldsInput field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *NewIntegrationInput) GetFieldsInputOk() ([]FieldInput, bool) {
	if o == nil || IsNil(o.FieldsInput) {
		return nil, false
	}
	return o.FieldsInput, true
}

// HasFieldsInput returns a boolean if a field has been set.
func (o *NewIntegrationInput) HasFieldsInput() bool {
	if o != nil && !IsNil(o.FieldsInput) {
		return true
	}

	return false
}

// SetFieldsInput gets a reference to the given []FieldInput and assigns it to the FieldsInput field.
func (o *NewIntegrationInput) SetFieldsInput(v []FieldInput) {
	o.FieldsInput = v
}

// GetScope returns the Scope field value if set, zero value otherwise (both if not set or set to explicit null).
func (o *NewIntegrationInput) GetScope() string {
	if o == nil || IsNil(o.Scope.Get()) {
		var ret string
		return ret
	}
	return *o.Scope.Get()
}

// GetScopeOk returns a tuple with the Scope field value if set, nil otherwise
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *NewIntegrationInput) GetScopeOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return o.Scope.Get(), o.Scope.IsSet()
}

// HasScope returns a boolean if a field has been set.
func (o *NewIntegrationInput) HasScope() bool {
	if o != nil && o.Scope.IsSet() {
		return true
	}

	return false
}

// SetScope gets a reference to the given NullableString and assigns it to the Scope field.
func (o *NewIntegrationInput) SetScope(v string) {
	o.Scope.Set(&v)
}
// SetScopeNil sets the value for Scope to be an explicit nil
func (o *NewIntegrationInput) SetScopeNil() {
	o.Scope.Set(nil)
}

// UnsetScope ensures that no value is present for Scope, not even an explicit nil
func (o *NewIntegrationInput) UnsetScope() {
	o.Scope.Unset()
}

// GetEnvironmentPolicy returns the EnvironmentPolicy field value if set, zero value otherwise.
func (o *NewIntegrationInput) GetEnvironmentPolicy() IntegrationEnvironmentPolicyInput {
	if o == nil || IsNil(o.EnvironmentPolicy) {
		var ret IntegrationEnvironmentPolicyInput
		return ret
	}
	return *o.EnvironmentPolicy
}

// GetEnvironmentPolicyOk returns a tuple with the EnvironmentPolicy field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *NewIntegrationInput) GetEnvironmentPolicyOk() (*IntegrationEnvironmentPolicyInput, bool) {
	if o == nil || IsNil(o.EnvironmentPolicy) {
		return nil, false
	}
	return o.EnvironmentPolicy, true
}

// HasEnvironmentPolicy returns a boolean if a field has been set.
func (o *NewIntegrationInput) HasEnvironmentPolicy() bool {
	if o != nil && !IsNil(o.EnvironmentPolicy) {
		return true
	}

	return false
}

// SetEnvironmentPolicy gets a reference to the given IntegrationEnvironmentPolicyInput and assigns it to the EnvironmentPolicy field.
func (o *NewIntegrationInput) SetEnvironmentPolicy(v IntegrationEnvironmentPolicyInput) {
	o.EnvironmentPolicy = &v
}

func (o NewIntegrationInput) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o NewIntegrationInput) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if !IsNil(o.OrgId) {
		toSerialize["orgId"] = o.OrgId
	}
	toSerialize["providerId"] = o.ProviderId
	toSerialize["title"] = o.Title
	toSerialize["kinds"] = o.Kinds
	if o.Auth.IsSet() {
		toSerialize["auth"] = o.Auth.Get()
	}
	if o.ProjectId.IsSet() {
		toSerialize["projectId"] = o.ProjectId.Get()
	}
	if !IsNil(o.FieldsInput) {
		toSerialize["fieldsInput"] = o.FieldsInput
	}
	if o.Scope.IsSet() {
		toSerialize["scope"] = o.Scope.Get()
	}
	if !IsNil(o.EnvironmentPolicy) {
		toSerialize["environmentPolicy"] = o.EnvironmentPolicy
	}
	return toSerialize, nil
}

func (o *NewIntegrationInput) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"providerId",
		"title",
		"kinds",
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err;
	}

	for _, requiredProperty := range(requiredProperties) {
		if _, exists := allProperties[requiredProperty]; !exists {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varNewIntegrationInput := _NewIntegrationInput{}

	decoder := json.NewDecoder(bytes.NewReader(data))
	decoder.DisallowUnknownFields()
	err = decoder.Decode(&varNewIntegrationInput)

	if err != nil {
		return err
	}

	*o = NewIntegrationInput(varNewIntegrationInput)

	return err
}

type NullableNewIntegrationInput struct {
	value *NewIntegrationInput
	isSet bool
}

func (v NullableNewIntegrationInput) Get() *NewIntegrationInput {
	return v.value
}

func (v *NullableNewIntegrationInput) Set(val *NewIntegrationInput) {
	v.value = val
	v.isSet = true
}

func (v NullableNewIntegrationInput) IsSet() bool {
	return v.isSet
}

func (v *NullableNewIntegrationInput) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableNewIntegrationInput(val *NewIntegrationInput) *NullableNewIntegrationInput {
	return &NullableNewIntegrationInput{value: val, isSet: true}
}

func (v NullableNewIntegrationInput) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableNewIntegrationInput) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


