/*
Wodby 2 Public API

Public REST API for customer SDKs and code integrations. GraphQL remains internal for the dashboard. This contract is the versioned public surface. 

API version: 1.0.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package client

import (
	"encoding/json"
	"bytes"
	"fmt"
)

// checks if the AppInstanceMaintenanceModeInput type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &AppInstanceMaintenanceModeInput{}

// AppInstanceMaintenanceModeInput struct for AppInstanceMaintenanceModeInput
type AppInstanceMaintenanceModeInput struct {
	Enabled bool `json:"enabled"`
}

type _AppInstanceMaintenanceModeInput AppInstanceMaintenanceModeInput

// NewAppInstanceMaintenanceModeInput instantiates a new AppInstanceMaintenanceModeInput object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewAppInstanceMaintenanceModeInput(enabled bool) *AppInstanceMaintenanceModeInput {
	this := AppInstanceMaintenanceModeInput{}
	this.Enabled = enabled
	return &this
}

// NewAppInstanceMaintenanceModeInputWithDefaults instantiates a new AppInstanceMaintenanceModeInput object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewAppInstanceMaintenanceModeInputWithDefaults() *AppInstanceMaintenanceModeInput {
	this := AppInstanceMaintenanceModeInput{}
	return &this
}

// GetEnabled returns the Enabled field value
func (o *AppInstanceMaintenanceModeInput) GetEnabled() bool {
	if o == nil {
		var ret bool
		return ret
	}

	return o.Enabled
}

// GetEnabledOk returns a tuple with the Enabled field value
// and a boolean to check if the value has been set.
func (o *AppInstanceMaintenanceModeInput) GetEnabledOk() (*bool, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Enabled, true
}

// SetEnabled sets field value
func (o *AppInstanceMaintenanceModeInput) SetEnabled(v bool) {
	o.Enabled = v
}

func (o AppInstanceMaintenanceModeInput) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o AppInstanceMaintenanceModeInput) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["enabled"] = o.Enabled
	return toSerialize, nil
}

func (o *AppInstanceMaintenanceModeInput) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"enabled",
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err;
	}

	for _, requiredProperty := range(requiredProperties) {
		if _, exists := allProperties[requiredProperty]; !exists {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varAppInstanceMaintenanceModeInput := _AppInstanceMaintenanceModeInput{}

	decoder := json.NewDecoder(bytes.NewReader(data))
	decoder.DisallowUnknownFields()
	err = decoder.Decode(&varAppInstanceMaintenanceModeInput)

	if err != nil {
		return err
	}

	*o = AppInstanceMaintenanceModeInput(varAppInstanceMaintenanceModeInput)

	return err
}

type NullableAppInstanceMaintenanceModeInput struct {
	value *AppInstanceMaintenanceModeInput
	isSet bool
}

func (v NullableAppInstanceMaintenanceModeInput) Get() *AppInstanceMaintenanceModeInput {
	return v.value
}

func (v *NullableAppInstanceMaintenanceModeInput) Set(val *AppInstanceMaintenanceModeInput) {
	v.value = val
	v.isSet = true
}

func (v NullableAppInstanceMaintenanceModeInput) IsSet() bool {
	return v.isSet
}

func (v *NullableAppInstanceMaintenanceModeInput) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableAppInstanceMaintenanceModeInput(val *AppInstanceMaintenanceModeInput) *NullableAppInstanceMaintenanceModeInput {
	return &NullableAppInstanceMaintenanceModeInput{value: val, isSet: true}
}

func (v NullableAppInstanceMaintenanceModeInput) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableAppInstanceMaintenanceModeInput) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


