/*
Wodby 2 Public API

Public REST API for customer SDKs and code integrations. GraphQL remains internal for the dashboard. This contract is the versioned public surface. 

API version: 1.0.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package client

import (
	"encoding/json"
	"bytes"
	"fmt"
)

// checks if the AppEnvironmentHealth type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &AppEnvironmentHealth{}

// AppEnvironmentHealth struct for AppEnvironmentHealth
type AppEnvironmentHealth struct {
	Cron AppEnvironmentCronHealth `json:"cron"`
	Backups AppEnvironmentBackupHealth `json:"backups"`
}

type _AppEnvironmentHealth AppEnvironmentHealth

// NewAppEnvironmentHealth instantiates a new AppEnvironmentHealth object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewAppEnvironmentHealth(cron AppEnvironmentCronHealth, backups AppEnvironmentBackupHealth) *AppEnvironmentHealth {
	this := AppEnvironmentHealth{}
	this.Cron = cron
	this.Backups = backups
	return &this
}

// NewAppEnvironmentHealthWithDefaults instantiates a new AppEnvironmentHealth object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewAppEnvironmentHealthWithDefaults() *AppEnvironmentHealth {
	this := AppEnvironmentHealth{}
	return &this
}

// GetCron returns the Cron field value
func (o *AppEnvironmentHealth) GetCron() AppEnvironmentCronHealth {
	if o == nil {
		var ret AppEnvironmentCronHealth
		return ret
	}

	return o.Cron
}

// GetCronOk returns a tuple with the Cron field value
// and a boolean to check if the value has been set.
func (o *AppEnvironmentHealth) GetCronOk() (*AppEnvironmentCronHealth, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Cron, true
}

// SetCron sets field value
func (o *AppEnvironmentHealth) SetCron(v AppEnvironmentCronHealth) {
	o.Cron = v
}

// GetBackups returns the Backups field value
func (o *AppEnvironmentHealth) GetBackups() AppEnvironmentBackupHealth {
	if o == nil {
		var ret AppEnvironmentBackupHealth
		return ret
	}

	return o.Backups
}

// GetBackupsOk returns a tuple with the Backups field value
// and a boolean to check if the value has been set.
func (o *AppEnvironmentHealth) GetBackupsOk() (*AppEnvironmentBackupHealth, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Backups, true
}

// SetBackups sets field value
func (o *AppEnvironmentHealth) SetBackups(v AppEnvironmentBackupHealth) {
	o.Backups = v
}

func (o AppEnvironmentHealth) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o AppEnvironmentHealth) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["cron"] = o.Cron
	toSerialize["backups"] = o.Backups
	return toSerialize, nil
}

func (o *AppEnvironmentHealth) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"cron",
		"backups",
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err;
	}

	for _, requiredProperty := range(requiredProperties) {
		if _, exists := allProperties[requiredProperty]; !exists {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varAppEnvironmentHealth := _AppEnvironmentHealth{}

	decoder := json.NewDecoder(bytes.NewReader(data))
	decoder.DisallowUnknownFields()
	err = decoder.Decode(&varAppEnvironmentHealth)

	if err != nil {
		return err
	}

	*o = AppEnvironmentHealth(varAppEnvironmentHealth)

	return err
}

type NullableAppEnvironmentHealth struct {
	value *AppEnvironmentHealth
	isSet bool
}

func (v NullableAppEnvironmentHealth) Get() *AppEnvironmentHealth {
	return v.value
}

func (v *NullableAppEnvironmentHealth) Set(val *AppEnvironmentHealth) {
	v.value = val
	v.isSet = true
}

func (v NullableAppEnvironmentHealth) IsSet() bool {
	return v.isSet
}

func (v *NullableAppEnvironmentHealth) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableAppEnvironmentHealth(val *AppEnvironmentHealth) *NullableAppEnvironmentHealth {
	return &NullableAppEnvironmentHealth{value: val, isSet: true}
}

func (v NullableAppEnvironmentHealth) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableAppEnvironmentHealth) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


