/*
Wodby 2 Public API

Public REST API for customer SDKs and code integrations. GraphQL remains internal for the dashboard. This contract is the versioned public surface. 

API version: 1.0.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package client

import (
	"encoding/json"
	"bytes"
	"fmt"
)

// checks if the HelmChartVolumeClaim type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &HelmChartVolumeClaim{}

// HelmChartVolumeClaim struct for HelmChartVolumeClaim
type HelmChartVolumeClaim struct {
	Name string `json:"name"`
	Size *string `json:"size,omitempty"`
	StorageClassName *string `json:"storageClassName,omitempty"`
	AccessModes []string `json:"accessModes,omitempty"`
}

type _HelmChartVolumeClaim HelmChartVolumeClaim

// NewHelmChartVolumeClaim instantiates a new HelmChartVolumeClaim object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewHelmChartVolumeClaim(name string) *HelmChartVolumeClaim {
	this := HelmChartVolumeClaim{}
	this.Name = name
	return &this
}

// NewHelmChartVolumeClaimWithDefaults instantiates a new HelmChartVolumeClaim object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewHelmChartVolumeClaimWithDefaults() *HelmChartVolumeClaim {
	this := HelmChartVolumeClaim{}
	return &this
}

// GetName returns the Name field value
func (o *HelmChartVolumeClaim) GetName() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Name
}

// GetNameOk returns a tuple with the Name field value
// and a boolean to check if the value has been set.
func (o *HelmChartVolumeClaim) GetNameOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Name, true
}

// SetName sets field value
func (o *HelmChartVolumeClaim) SetName(v string) {
	o.Name = v
}

// GetSize returns the Size field value if set, zero value otherwise.
func (o *HelmChartVolumeClaim) GetSize() string {
	if o == nil || IsNil(o.Size) {
		var ret string
		return ret
	}
	return *o.Size
}

// GetSizeOk returns a tuple with the Size field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *HelmChartVolumeClaim) GetSizeOk() (*string, bool) {
	if o == nil || IsNil(o.Size) {
		return nil, false
	}
	return o.Size, true
}

// HasSize returns a boolean if a field has been set.
func (o *HelmChartVolumeClaim) HasSize() bool {
	if o != nil && !IsNil(o.Size) {
		return true
	}

	return false
}

// SetSize gets a reference to the given string and assigns it to the Size field.
func (o *HelmChartVolumeClaim) SetSize(v string) {
	o.Size = &v
}

// GetStorageClassName returns the StorageClassName field value if set, zero value otherwise.
func (o *HelmChartVolumeClaim) GetStorageClassName() string {
	if o == nil || IsNil(o.StorageClassName) {
		var ret string
		return ret
	}
	return *o.StorageClassName
}

// GetStorageClassNameOk returns a tuple with the StorageClassName field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *HelmChartVolumeClaim) GetStorageClassNameOk() (*string, bool) {
	if o == nil || IsNil(o.StorageClassName) {
		return nil, false
	}
	return o.StorageClassName, true
}

// HasStorageClassName returns a boolean if a field has been set.
func (o *HelmChartVolumeClaim) HasStorageClassName() bool {
	if o != nil && !IsNil(o.StorageClassName) {
		return true
	}

	return false
}

// SetStorageClassName gets a reference to the given string and assigns it to the StorageClassName field.
func (o *HelmChartVolumeClaim) SetStorageClassName(v string) {
	o.StorageClassName = &v
}

// GetAccessModes returns the AccessModes field value if set, zero value otherwise.
func (o *HelmChartVolumeClaim) GetAccessModes() []string {
	if o == nil || IsNil(o.AccessModes) {
		var ret []string
		return ret
	}
	return o.AccessModes
}

// GetAccessModesOk returns a tuple with the AccessModes field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *HelmChartVolumeClaim) GetAccessModesOk() ([]string, bool) {
	if o == nil || IsNil(o.AccessModes) {
		return nil, false
	}
	return o.AccessModes, true
}

// HasAccessModes returns a boolean if a field has been set.
func (o *HelmChartVolumeClaim) HasAccessModes() bool {
	if o != nil && !IsNil(o.AccessModes) {
		return true
	}

	return false
}

// SetAccessModes gets a reference to the given []string and assigns it to the AccessModes field.
func (o *HelmChartVolumeClaim) SetAccessModes(v []string) {
	o.AccessModes = v
}

func (o HelmChartVolumeClaim) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o HelmChartVolumeClaim) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["name"] = o.Name
	if !IsNil(o.Size) {
		toSerialize["size"] = o.Size
	}
	if !IsNil(o.StorageClassName) {
		toSerialize["storageClassName"] = o.StorageClassName
	}
	if !IsNil(o.AccessModes) {
		toSerialize["accessModes"] = o.AccessModes
	}
	return toSerialize, nil
}

func (o *HelmChartVolumeClaim) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"name",
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err;
	}

	for _, requiredProperty := range(requiredProperties) {
		if _, exists := allProperties[requiredProperty]; !exists {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varHelmChartVolumeClaim := _HelmChartVolumeClaim{}

	decoder := json.NewDecoder(bytes.NewReader(data))
	decoder.DisallowUnknownFields()
	err = decoder.Decode(&varHelmChartVolumeClaim)

	if err != nil {
		return err
	}

	*o = HelmChartVolumeClaim(varHelmChartVolumeClaim)

	return err
}

type NullableHelmChartVolumeClaim struct {
	value *HelmChartVolumeClaim
	isSet bool
}

func (v NullableHelmChartVolumeClaim) Get() *HelmChartVolumeClaim {
	return v.value
}

func (v *NullableHelmChartVolumeClaim) Set(val *HelmChartVolumeClaim) {
	v.value = val
	v.isSet = true
}

func (v NullableHelmChartVolumeClaim) IsSet() bool {
	return v.isSet
}

func (v *NullableHelmChartVolumeClaim) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableHelmChartVolumeClaim(val *HelmChartVolumeClaim) *NullableHelmChartVolumeClaim {
	return &NullableHelmChartVolumeClaim{value: val, isSet: true}
}

func (v NullableHelmChartVolumeClaim) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableHelmChartVolumeClaim) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


