/*
Wodby 2 Public API

Public REST API for customer SDKs and code integrations. GraphQL remains internal for the dashboard. This contract is the versioned public surface. 

API version: 1.0.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package client

import (
	"encoding/json"
	"bytes"
	"fmt"
)

// checks if the AppEnvironmentStackReconciliationInput type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &AppEnvironmentStackReconciliationInput{}

// AppEnvironmentStackReconciliationInput struct for AppEnvironmentStackReconciliationInput
type AppEnvironmentStackReconciliationInput struct {
	Versions bool `json:"versions"`
	Replicas bool `json:"replicas"`
	Resources bool `json:"resources"`
	Integrations bool `json:"integrations"`
	Services bool `json:"services"`
	Settings bool `json:"settings"`
	Links bool `json:"links"`
	Tokens bool `json:"tokens"`
	Configs bool `json:"configs"`
	Cron bool `json:"cron"`
	Volumes bool `json:"volumes"`
	Main bool `json:"main"`
}

type _AppEnvironmentStackReconciliationInput AppEnvironmentStackReconciliationInput

// NewAppEnvironmentStackReconciliationInput instantiates a new AppEnvironmentStackReconciliationInput object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewAppEnvironmentStackReconciliationInput(versions bool, replicas bool, resources bool, integrations bool, services bool, settings bool, links bool, tokens bool, configs bool, cron bool, volumes bool, main bool) *AppEnvironmentStackReconciliationInput {
	this := AppEnvironmentStackReconciliationInput{}
	this.Versions = versions
	this.Replicas = replicas
	this.Resources = resources
	this.Integrations = integrations
	this.Services = services
	this.Settings = settings
	this.Links = links
	this.Tokens = tokens
	this.Configs = configs
	this.Cron = cron
	this.Volumes = volumes
	this.Main = main
	return &this
}

// NewAppEnvironmentStackReconciliationInputWithDefaults instantiates a new AppEnvironmentStackReconciliationInput object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewAppEnvironmentStackReconciliationInputWithDefaults() *AppEnvironmentStackReconciliationInput {
	this := AppEnvironmentStackReconciliationInput{}
	return &this
}

// GetVersions returns the Versions field value
func (o *AppEnvironmentStackReconciliationInput) GetVersions() bool {
	if o == nil {
		var ret bool
		return ret
	}

	return o.Versions
}

// GetVersionsOk returns a tuple with the Versions field value
// and a boolean to check if the value has been set.
func (o *AppEnvironmentStackReconciliationInput) GetVersionsOk() (*bool, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Versions, true
}

// SetVersions sets field value
func (o *AppEnvironmentStackReconciliationInput) SetVersions(v bool) {
	o.Versions = v
}

// GetReplicas returns the Replicas field value
func (o *AppEnvironmentStackReconciliationInput) GetReplicas() bool {
	if o == nil {
		var ret bool
		return ret
	}

	return o.Replicas
}

// GetReplicasOk returns a tuple with the Replicas field value
// and a boolean to check if the value has been set.
func (o *AppEnvironmentStackReconciliationInput) GetReplicasOk() (*bool, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Replicas, true
}

// SetReplicas sets field value
func (o *AppEnvironmentStackReconciliationInput) SetReplicas(v bool) {
	o.Replicas = v
}

// GetResources returns the Resources field value
func (o *AppEnvironmentStackReconciliationInput) GetResources() bool {
	if o == nil {
		var ret bool
		return ret
	}

	return o.Resources
}

// GetResourcesOk returns a tuple with the Resources field value
// and a boolean to check if the value has been set.
func (o *AppEnvironmentStackReconciliationInput) GetResourcesOk() (*bool, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Resources, true
}

// SetResources sets field value
func (o *AppEnvironmentStackReconciliationInput) SetResources(v bool) {
	o.Resources = v
}

// GetIntegrations returns the Integrations field value
func (o *AppEnvironmentStackReconciliationInput) GetIntegrations() bool {
	if o == nil {
		var ret bool
		return ret
	}

	return o.Integrations
}

// GetIntegrationsOk returns a tuple with the Integrations field value
// and a boolean to check if the value has been set.
func (o *AppEnvironmentStackReconciliationInput) GetIntegrationsOk() (*bool, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Integrations, true
}

// SetIntegrations sets field value
func (o *AppEnvironmentStackReconciliationInput) SetIntegrations(v bool) {
	o.Integrations = v
}

// GetServices returns the Services field value
func (o *AppEnvironmentStackReconciliationInput) GetServices() bool {
	if o == nil {
		var ret bool
		return ret
	}

	return o.Services
}

// GetServicesOk returns a tuple with the Services field value
// and a boolean to check if the value has been set.
func (o *AppEnvironmentStackReconciliationInput) GetServicesOk() (*bool, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Services, true
}

// SetServices sets field value
func (o *AppEnvironmentStackReconciliationInput) SetServices(v bool) {
	o.Services = v
}

// GetSettings returns the Settings field value
func (o *AppEnvironmentStackReconciliationInput) GetSettings() bool {
	if o == nil {
		var ret bool
		return ret
	}

	return o.Settings
}

// GetSettingsOk returns a tuple with the Settings field value
// and a boolean to check if the value has been set.
func (o *AppEnvironmentStackReconciliationInput) GetSettingsOk() (*bool, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Settings, true
}

// SetSettings sets field value
func (o *AppEnvironmentStackReconciliationInput) SetSettings(v bool) {
	o.Settings = v
}

// GetLinks returns the Links field value
func (o *AppEnvironmentStackReconciliationInput) GetLinks() bool {
	if o == nil {
		var ret bool
		return ret
	}

	return o.Links
}

// GetLinksOk returns a tuple with the Links field value
// and a boolean to check if the value has been set.
func (o *AppEnvironmentStackReconciliationInput) GetLinksOk() (*bool, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Links, true
}

// SetLinks sets field value
func (o *AppEnvironmentStackReconciliationInput) SetLinks(v bool) {
	o.Links = v
}

// GetTokens returns the Tokens field value
func (o *AppEnvironmentStackReconciliationInput) GetTokens() bool {
	if o == nil {
		var ret bool
		return ret
	}

	return o.Tokens
}

// GetTokensOk returns a tuple with the Tokens field value
// and a boolean to check if the value has been set.
func (o *AppEnvironmentStackReconciliationInput) GetTokensOk() (*bool, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Tokens, true
}

// SetTokens sets field value
func (o *AppEnvironmentStackReconciliationInput) SetTokens(v bool) {
	o.Tokens = v
}

// GetConfigs returns the Configs field value
func (o *AppEnvironmentStackReconciliationInput) GetConfigs() bool {
	if o == nil {
		var ret bool
		return ret
	}

	return o.Configs
}

// GetConfigsOk returns a tuple with the Configs field value
// and a boolean to check if the value has been set.
func (o *AppEnvironmentStackReconciliationInput) GetConfigsOk() (*bool, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Configs, true
}

// SetConfigs sets field value
func (o *AppEnvironmentStackReconciliationInput) SetConfigs(v bool) {
	o.Configs = v
}

// GetCron returns the Cron field value
func (o *AppEnvironmentStackReconciliationInput) GetCron() bool {
	if o == nil {
		var ret bool
		return ret
	}

	return o.Cron
}

// GetCronOk returns a tuple with the Cron field value
// and a boolean to check if the value has been set.
func (o *AppEnvironmentStackReconciliationInput) GetCronOk() (*bool, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Cron, true
}

// SetCron sets field value
func (o *AppEnvironmentStackReconciliationInput) SetCron(v bool) {
	o.Cron = v
}

// GetVolumes returns the Volumes field value
func (o *AppEnvironmentStackReconciliationInput) GetVolumes() bool {
	if o == nil {
		var ret bool
		return ret
	}

	return o.Volumes
}

// GetVolumesOk returns a tuple with the Volumes field value
// and a boolean to check if the value has been set.
func (o *AppEnvironmentStackReconciliationInput) GetVolumesOk() (*bool, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Volumes, true
}

// SetVolumes sets field value
func (o *AppEnvironmentStackReconciliationInput) SetVolumes(v bool) {
	o.Volumes = v
}

// GetMain returns the Main field value
func (o *AppEnvironmentStackReconciliationInput) GetMain() bool {
	if o == nil {
		var ret bool
		return ret
	}

	return o.Main
}

// GetMainOk returns a tuple with the Main field value
// and a boolean to check if the value has been set.
func (o *AppEnvironmentStackReconciliationInput) GetMainOk() (*bool, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Main, true
}

// SetMain sets field value
func (o *AppEnvironmentStackReconciliationInput) SetMain(v bool) {
	o.Main = v
}

func (o AppEnvironmentStackReconciliationInput) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o AppEnvironmentStackReconciliationInput) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["versions"] = o.Versions
	toSerialize["replicas"] = o.Replicas
	toSerialize["resources"] = o.Resources
	toSerialize["integrations"] = o.Integrations
	toSerialize["services"] = o.Services
	toSerialize["settings"] = o.Settings
	toSerialize["links"] = o.Links
	toSerialize["tokens"] = o.Tokens
	toSerialize["configs"] = o.Configs
	toSerialize["cron"] = o.Cron
	toSerialize["volumes"] = o.Volumes
	toSerialize["main"] = o.Main
	return toSerialize, nil
}

func (o *AppEnvironmentStackReconciliationInput) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"versions",
		"replicas",
		"resources",
		"integrations",
		"services",
		"settings",
		"links",
		"tokens",
		"configs",
		"cron",
		"volumes",
		"main",
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err;
	}

	for _, requiredProperty := range(requiredProperties) {
		if _, exists := allProperties[requiredProperty]; !exists {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varAppEnvironmentStackReconciliationInput := _AppEnvironmentStackReconciliationInput{}

	decoder := json.NewDecoder(bytes.NewReader(data))
	decoder.DisallowUnknownFields()
	err = decoder.Decode(&varAppEnvironmentStackReconciliationInput)

	if err != nil {
		return err
	}

	*o = AppEnvironmentStackReconciliationInput(varAppEnvironmentStackReconciliationInput)

	return err
}

type NullableAppEnvironmentStackReconciliationInput struct {
	value *AppEnvironmentStackReconciliationInput
	isSet bool
}

func (v NullableAppEnvironmentStackReconciliationInput) Get() *AppEnvironmentStackReconciliationInput {
	return v.value
}

func (v *NullableAppEnvironmentStackReconciliationInput) Set(val *AppEnvironmentStackReconciliationInput) {
	v.value = val
	v.isSet = true
}

func (v NullableAppEnvironmentStackReconciliationInput) IsSet() bool {
	return v.isSet
}

func (v *NullableAppEnvironmentStackReconciliationInput) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableAppEnvironmentStackReconciliationInput(val *AppEnvironmentStackReconciliationInput) *NullableAppEnvironmentStackReconciliationInput {
	return &NullableAppEnvironmentStackReconciliationInput{value: val, isSet: true}
}

func (v NullableAppEnvironmentStackReconciliationInput) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableAppEnvironmentStackReconciliationInput) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


