/*
Wodby 2 Public API

Public REST API for customer SDKs and code integrations. GraphQL remains internal for the dashboard. This contract is the versioned public surface. 

API version: 1.0.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package client

import (
	"encoding/json"
	"bytes"
	"fmt"
)

// checks if the ServiceManifestUpdateInput type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &ServiceManifestUpdateInput{}

// ServiceManifestUpdateInput struct for ServiceManifestUpdateInput
type ServiceManifestUpdateInput struct {
	// Optional service revision version; defaults to the current service version.
	Version *string `json:"version,omitempty"`
	// Complete Wodby service.yml manifest content.
	ManifestYaml string `json:"manifestYaml"`
	// Optional referenced file contents keyed by manifest-relative path, for example Dockerfile or configs/app.conf.
	Files *map[string]string `json:"files,omitempty"`
}

type _ServiceManifestUpdateInput ServiceManifestUpdateInput

// NewServiceManifestUpdateInput instantiates a new ServiceManifestUpdateInput object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewServiceManifestUpdateInput(manifestYaml string) *ServiceManifestUpdateInput {
	this := ServiceManifestUpdateInput{}
	this.ManifestYaml = manifestYaml
	return &this
}

// NewServiceManifestUpdateInputWithDefaults instantiates a new ServiceManifestUpdateInput object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewServiceManifestUpdateInputWithDefaults() *ServiceManifestUpdateInput {
	this := ServiceManifestUpdateInput{}
	return &this
}

// GetVersion returns the Version field value if set, zero value otherwise.
func (o *ServiceManifestUpdateInput) GetVersion() string {
	if o == nil || IsNil(o.Version) {
		var ret string
		return ret
	}
	return *o.Version
}

// GetVersionOk returns a tuple with the Version field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *ServiceManifestUpdateInput) GetVersionOk() (*string, bool) {
	if o == nil || IsNil(o.Version) {
		return nil, false
	}
	return o.Version, true
}

// HasVersion returns a boolean if a field has been set.
func (o *ServiceManifestUpdateInput) HasVersion() bool {
	if o != nil && !IsNil(o.Version) {
		return true
	}

	return false
}

// SetVersion gets a reference to the given string and assigns it to the Version field.
func (o *ServiceManifestUpdateInput) SetVersion(v string) {
	o.Version = &v
}

// GetManifestYaml returns the ManifestYaml field value
func (o *ServiceManifestUpdateInput) GetManifestYaml() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.ManifestYaml
}

// GetManifestYamlOk returns a tuple with the ManifestYaml field value
// and a boolean to check if the value has been set.
func (o *ServiceManifestUpdateInput) GetManifestYamlOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.ManifestYaml, true
}

// SetManifestYaml sets field value
func (o *ServiceManifestUpdateInput) SetManifestYaml(v string) {
	o.ManifestYaml = v
}

// GetFiles returns the Files field value if set, zero value otherwise.
func (o *ServiceManifestUpdateInput) GetFiles() map[string]string {
	if o == nil || IsNil(o.Files) {
		var ret map[string]string
		return ret
	}
	return *o.Files
}

// GetFilesOk returns a tuple with the Files field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *ServiceManifestUpdateInput) GetFilesOk() (*map[string]string, bool) {
	if o == nil || IsNil(o.Files) {
		return nil, false
	}
	return o.Files, true
}

// HasFiles returns a boolean if a field has been set.
func (o *ServiceManifestUpdateInput) HasFiles() bool {
	if o != nil && !IsNil(o.Files) {
		return true
	}

	return false
}

// SetFiles gets a reference to the given map[string]string and assigns it to the Files field.
func (o *ServiceManifestUpdateInput) SetFiles(v map[string]string) {
	o.Files = &v
}

func (o ServiceManifestUpdateInput) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o ServiceManifestUpdateInput) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if !IsNil(o.Version) {
		toSerialize["version"] = o.Version
	}
	toSerialize["manifestYaml"] = o.ManifestYaml
	if !IsNil(o.Files) {
		toSerialize["files"] = o.Files
	}
	return toSerialize, nil
}

func (o *ServiceManifestUpdateInput) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"manifestYaml",
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err;
	}

	for _, requiredProperty := range(requiredProperties) {
		if _, exists := allProperties[requiredProperty]; !exists {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varServiceManifestUpdateInput := _ServiceManifestUpdateInput{}

	decoder := json.NewDecoder(bytes.NewReader(data))
	decoder.DisallowUnknownFields()
	err = decoder.Decode(&varServiceManifestUpdateInput)

	if err != nil {
		return err
	}

	*o = ServiceManifestUpdateInput(varServiceManifestUpdateInput)

	return err
}

type NullableServiceManifestUpdateInput struct {
	value *ServiceManifestUpdateInput
	isSet bool
}

func (v NullableServiceManifestUpdateInput) Get() *ServiceManifestUpdateInput {
	return v.value
}

func (v *NullableServiceManifestUpdateInput) Set(val *ServiceManifestUpdateInput) {
	v.value = val
	v.isSet = true
}

func (v NullableServiceManifestUpdateInput) IsSet() bool {
	return v.isSet
}

func (v *NullableServiceManifestUpdateInput) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableServiceManifestUpdateInput(val *ServiceManifestUpdateInput) *NullableServiceManifestUpdateInput {
	return &NullableServiceManifestUpdateInput{value: val, isSet: true}
}

func (v NullableServiceManifestUpdateInput) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableServiceManifestUpdateInput) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


