/*
Wodby 2 Public API

Public REST API for customer SDKs and code integrations. GraphQL remains internal for the dashboard. This contract is the versioned public surface. 

API version: 1.0.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package client

import (
	"encoding/json"
	"time"
	"bytes"
	"fmt"
)

// checks if the Import type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &Import{}

// Import struct for Import
type Import struct {
	Id int32 `json:"id"`
	Name string `json:"name"`
	Source string `json:"source"`
	Status string `json:"status"`
	Filename NullableString `json:"filename,omitempty"`
	Size NullableInt64 `json:"size,omitempty"`
	AppInstanceId NullableInt32 `json:"appInstanceId,omitempty"`
	AppServiceId NullableInt32 `json:"appServiceId,omitempty"`
	DatabaseId NullableInt32 `json:"databaseId,omitempty"`
	DatabaseDbId NullableInt32 `json:"databaseDbId,omitempty"`
	AppServiceDeploymentId NullableInt32 `json:"appServiceDeploymentId,omitempty"`
	TaskId NullableInt32 `json:"taskId,omitempty"`
	BackupId NullableInt32 `json:"backupId,omitempty"`
	CreatedAt time.Time `json:"createdAt"`
	UpdatedAt time.Time `json:"updatedAt"`
	StartedAt NullableTime `json:"startedAt,omitempty"`
	EndedAt NullableTime `json:"endedAt,omitempty"`
}

type _Import Import

// NewImport instantiates a new Import object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewImport(id int32, name string, source string, status string, createdAt time.Time, updatedAt time.Time) *Import {
	this := Import{}
	this.Id = id
	this.Name = name
	this.Source = source
	this.Status = status
	this.CreatedAt = createdAt
	this.UpdatedAt = updatedAt
	return &this
}

// NewImportWithDefaults instantiates a new Import object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewImportWithDefaults() *Import {
	this := Import{}
	return &this
}

// GetId returns the Id field value
func (o *Import) GetId() int32 {
	if o == nil {
		var ret int32
		return ret
	}

	return o.Id
}

// GetIdOk returns a tuple with the Id field value
// and a boolean to check if the value has been set.
func (o *Import) GetIdOk() (*int32, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Id, true
}

// SetId sets field value
func (o *Import) SetId(v int32) {
	o.Id = v
}

// GetName returns the Name field value
func (o *Import) GetName() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Name
}

// GetNameOk returns a tuple with the Name field value
// and a boolean to check if the value has been set.
func (o *Import) GetNameOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Name, true
}

// SetName sets field value
func (o *Import) SetName(v string) {
	o.Name = v
}

// GetSource returns the Source field value
func (o *Import) GetSource() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Source
}

// GetSourceOk returns a tuple with the Source field value
// and a boolean to check if the value has been set.
func (o *Import) GetSourceOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Source, true
}

// SetSource sets field value
func (o *Import) SetSource(v string) {
	o.Source = v
}

// GetStatus returns the Status field value
func (o *Import) GetStatus() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Status
}

// GetStatusOk returns a tuple with the Status field value
// and a boolean to check if the value has been set.
func (o *Import) GetStatusOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Status, true
}

// SetStatus sets field value
func (o *Import) SetStatus(v string) {
	o.Status = v
}

// GetFilename returns the Filename field value if set, zero value otherwise (both if not set or set to explicit null).
func (o *Import) GetFilename() string {
	if o == nil || IsNil(o.Filename.Get()) {
		var ret string
		return ret
	}
	return *o.Filename.Get()
}

// GetFilenameOk returns a tuple with the Filename field value if set, nil otherwise
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *Import) GetFilenameOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return o.Filename.Get(), o.Filename.IsSet()
}

// HasFilename returns a boolean if a field has been set.
func (o *Import) HasFilename() bool {
	if o != nil && o.Filename.IsSet() {
		return true
	}

	return false
}

// SetFilename gets a reference to the given NullableString and assigns it to the Filename field.
func (o *Import) SetFilename(v string) {
	o.Filename.Set(&v)
}
// SetFilenameNil sets the value for Filename to be an explicit nil
func (o *Import) SetFilenameNil() {
	o.Filename.Set(nil)
}

// UnsetFilename ensures that no value is present for Filename, not even an explicit nil
func (o *Import) UnsetFilename() {
	o.Filename.Unset()
}

// GetSize returns the Size field value if set, zero value otherwise (both if not set or set to explicit null).
func (o *Import) GetSize() int64 {
	if o == nil || IsNil(o.Size.Get()) {
		var ret int64
		return ret
	}
	return *o.Size.Get()
}

// GetSizeOk returns a tuple with the Size field value if set, nil otherwise
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *Import) GetSizeOk() (*int64, bool) {
	if o == nil {
		return nil, false
	}
	return o.Size.Get(), o.Size.IsSet()
}

// HasSize returns a boolean if a field has been set.
func (o *Import) HasSize() bool {
	if o != nil && o.Size.IsSet() {
		return true
	}

	return false
}

// SetSize gets a reference to the given NullableInt64 and assigns it to the Size field.
func (o *Import) SetSize(v int64) {
	o.Size.Set(&v)
}
// SetSizeNil sets the value for Size to be an explicit nil
func (o *Import) SetSizeNil() {
	o.Size.Set(nil)
}

// UnsetSize ensures that no value is present for Size, not even an explicit nil
func (o *Import) UnsetSize() {
	o.Size.Unset()
}

// GetAppInstanceId returns the AppInstanceId field value if set, zero value otherwise (both if not set or set to explicit null).
func (o *Import) GetAppInstanceId() int32 {
	if o == nil || IsNil(o.AppInstanceId.Get()) {
		var ret int32
		return ret
	}
	return *o.AppInstanceId.Get()
}

// GetAppInstanceIdOk returns a tuple with the AppInstanceId field value if set, nil otherwise
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *Import) GetAppInstanceIdOk() (*int32, bool) {
	if o == nil {
		return nil, false
	}
	return o.AppInstanceId.Get(), o.AppInstanceId.IsSet()
}

// HasAppInstanceId returns a boolean if a field has been set.
func (o *Import) HasAppInstanceId() bool {
	if o != nil && o.AppInstanceId.IsSet() {
		return true
	}

	return false
}

// SetAppInstanceId gets a reference to the given NullableInt32 and assigns it to the AppInstanceId field.
func (o *Import) SetAppInstanceId(v int32) {
	o.AppInstanceId.Set(&v)
}
// SetAppInstanceIdNil sets the value for AppInstanceId to be an explicit nil
func (o *Import) SetAppInstanceIdNil() {
	o.AppInstanceId.Set(nil)
}

// UnsetAppInstanceId ensures that no value is present for AppInstanceId, not even an explicit nil
func (o *Import) UnsetAppInstanceId() {
	o.AppInstanceId.Unset()
}

// GetAppServiceId returns the AppServiceId field value if set, zero value otherwise (both if not set or set to explicit null).
func (o *Import) GetAppServiceId() int32 {
	if o == nil || IsNil(o.AppServiceId.Get()) {
		var ret int32
		return ret
	}
	return *o.AppServiceId.Get()
}

// GetAppServiceIdOk returns a tuple with the AppServiceId field value if set, nil otherwise
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *Import) GetAppServiceIdOk() (*int32, bool) {
	if o == nil {
		return nil, false
	}
	return o.AppServiceId.Get(), o.AppServiceId.IsSet()
}

// HasAppServiceId returns a boolean if a field has been set.
func (o *Import) HasAppServiceId() bool {
	if o != nil && o.AppServiceId.IsSet() {
		return true
	}

	return false
}

// SetAppServiceId gets a reference to the given NullableInt32 and assigns it to the AppServiceId field.
func (o *Import) SetAppServiceId(v int32) {
	o.AppServiceId.Set(&v)
}
// SetAppServiceIdNil sets the value for AppServiceId to be an explicit nil
func (o *Import) SetAppServiceIdNil() {
	o.AppServiceId.Set(nil)
}

// UnsetAppServiceId ensures that no value is present for AppServiceId, not even an explicit nil
func (o *Import) UnsetAppServiceId() {
	o.AppServiceId.Unset()
}

// GetDatabaseId returns the DatabaseId field value if set, zero value otherwise (both if not set or set to explicit null).
func (o *Import) GetDatabaseId() int32 {
	if o == nil || IsNil(o.DatabaseId.Get()) {
		var ret int32
		return ret
	}
	return *o.DatabaseId.Get()
}

// GetDatabaseIdOk returns a tuple with the DatabaseId field value if set, nil otherwise
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *Import) GetDatabaseIdOk() (*int32, bool) {
	if o == nil {
		return nil, false
	}
	return o.DatabaseId.Get(), o.DatabaseId.IsSet()
}

// HasDatabaseId returns a boolean if a field has been set.
func (o *Import) HasDatabaseId() bool {
	if o != nil && o.DatabaseId.IsSet() {
		return true
	}

	return false
}

// SetDatabaseId gets a reference to the given NullableInt32 and assigns it to the DatabaseId field.
func (o *Import) SetDatabaseId(v int32) {
	o.DatabaseId.Set(&v)
}
// SetDatabaseIdNil sets the value for DatabaseId to be an explicit nil
func (o *Import) SetDatabaseIdNil() {
	o.DatabaseId.Set(nil)
}

// UnsetDatabaseId ensures that no value is present for DatabaseId, not even an explicit nil
func (o *Import) UnsetDatabaseId() {
	o.DatabaseId.Unset()
}

// GetDatabaseDbId returns the DatabaseDbId field value if set, zero value otherwise (both if not set or set to explicit null).
func (o *Import) GetDatabaseDbId() int32 {
	if o == nil || IsNil(o.DatabaseDbId.Get()) {
		var ret int32
		return ret
	}
	return *o.DatabaseDbId.Get()
}

// GetDatabaseDbIdOk returns a tuple with the DatabaseDbId field value if set, nil otherwise
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *Import) GetDatabaseDbIdOk() (*int32, bool) {
	if o == nil {
		return nil, false
	}
	return o.DatabaseDbId.Get(), o.DatabaseDbId.IsSet()
}

// HasDatabaseDbId returns a boolean if a field has been set.
func (o *Import) HasDatabaseDbId() bool {
	if o != nil && o.DatabaseDbId.IsSet() {
		return true
	}

	return false
}

// SetDatabaseDbId gets a reference to the given NullableInt32 and assigns it to the DatabaseDbId field.
func (o *Import) SetDatabaseDbId(v int32) {
	o.DatabaseDbId.Set(&v)
}
// SetDatabaseDbIdNil sets the value for DatabaseDbId to be an explicit nil
func (o *Import) SetDatabaseDbIdNil() {
	o.DatabaseDbId.Set(nil)
}

// UnsetDatabaseDbId ensures that no value is present for DatabaseDbId, not even an explicit nil
func (o *Import) UnsetDatabaseDbId() {
	o.DatabaseDbId.Unset()
}

// GetAppServiceDeploymentId returns the AppServiceDeploymentId field value if set, zero value otherwise (both if not set or set to explicit null).
func (o *Import) GetAppServiceDeploymentId() int32 {
	if o == nil || IsNil(o.AppServiceDeploymentId.Get()) {
		var ret int32
		return ret
	}
	return *o.AppServiceDeploymentId.Get()
}

// GetAppServiceDeploymentIdOk returns a tuple with the AppServiceDeploymentId field value if set, nil otherwise
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *Import) GetAppServiceDeploymentIdOk() (*int32, bool) {
	if o == nil {
		return nil, false
	}
	return o.AppServiceDeploymentId.Get(), o.AppServiceDeploymentId.IsSet()
}

// HasAppServiceDeploymentId returns a boolean if a field has been set.
func (o *Import) HasAppServiceDeploymentId() bool {
	if o != nil && o.AppServiceDeploymentId.IsSet() {
		return true
	}

	return false
}

// SetAppServiceDeploymentId gets a reference to the given NullableInt32 and assigns it to the AppServiceDeploymentId field.
func (o *Import) SetAppServiceDeploymentId(v int32) {
	o.AppServiceDeploymentId.Set(&v)
}
// SetAppServiceDeploymentIdNil sets the value for AppServiceDeploymentId to be an explicit nil
func (o *Import) SetAppServiceDeploymentIdNil() {
	o.AppServiceDeploymentId.Set(nil)
}

// UnsetAppServiceDeploymentId ensures that no value is present for AppServiceDeploymentId, not even an explicit nil
func (o *Import) UnsetAppServiceDeploymentId() {
	o.AppServiceDeploymentId.Unset()
}

// GetTaskId returns the TaskId field value if set, zero value otherwise (both if not set or set to explicit null).
func (o *Import) GetTaskId() int32 {
	if o == nil || IsNil(o.TaskId.Get()) {
		var ret int32
		return ret
	}
	return *o.TaskId.Get()
}

// GetTaskIdOk returns a tuple with the TaskId field value if set, nil otherwise
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *Import) GetTaskIdOk() (*int32, bool) {
	if o == nil {
		return nil, false
	}
	return o.TaskId.Get(), o.TaskId.IsSet()
}

// HasTaskId returns a boolean if a field has been set.
func (o *Import) HasTaskId() bool {
	if o != nil && o.TaskId.IsSet() {
		return true
	}

	return false
}

// SetTaskId gets a reference to the given NullableInt32 and assigns it to the TaskId field.
func (o *Import) SetTaskId(v int32) {
	o.TaskId.Set(&v)
}
// SetTaskIdNil sets the value for TaskId to be an explicit nil
func (o *Import) SetTaskIdNil() {
	o.TaskId.Set(nil)
}

// UnsetTaskId ensures that no value is present for TaskId, not even an explicit nil
func (o *Import) UnsetTaskId() {
	o.TaskId.Unset()
}

// GetBackupId returns the BackupId field value if set, zero value otherwise (both if not set or set to explicit null).
func (o *Import) GetBackupId() int32 {
	if o == nil || IsNil(o.BackupId.Get()) {
		var ret int32
		return ret
	}
	return *o.BackupId.Get()
}

// GetBackupIdOk returns a tuple with the BackupId field value if set, nil otherwise
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *Import) GetBackupIdOk() (*int32, bool) {
	if o == nil {
		return nil, false
	}
	return o.BackupId.Get(), o.BackupId.IsSet()
}

// HasBackupId returns a boolean if a field has been set.
func (o *Import) HasBackupId() bool {
	if o != nil && o.BackupId.IsSet() {
		return true
	}

	return false
}

// SetBackupId gets a reference to the given NullableInt32 and assigns it to the BackupId field.
func (o *Import) SetBackupId(v int32) {
	o.BackupId.Set(&v)
}
// SetBackupIdNil sets the value for BackupId to be an explicit nil
func (o *Import) SetBackupIdNil() {
	o.BackupId.Set(nil)
}

// UnsetBackupId ensures that no value is present for BackupId, not even an explicit nil
func (o *Import) UnsetBackupId() {
	o.BackupId.Unset()
}

// GetCreatedAt returns the CreatedAt field value
func (o *Import) GetCreatedAt() time.Time {
	if o == nil {
		var ret time.Time
		return ret
	}

	return o.CreatedAt
}

// GetCreatedAtOk returns a tuple with the CreatedAt field value
// and a boolean to check if the value has been set.
func (o *Import) GetCreatedAtOk() (*time.Time, bool) {
	if o == nil {
		return nil, false
	}
	return &o.CreatedAt, true
}

// SetCreatedAt sets field value
func (o *Import) SetCreatedAt(v time.Time) {
	o.CreatedAt = v
}

// GetUpdatedAt returns the UpdatedAt field value
func (o *Import) GetUpdatedAt() time.Time {
	if o == nil {
		var ret time.Time
		return ret
	}

	return o.UpdatedAt
}

// GetUpdatedAtOk returns a tuple with the UpdatedAt field value
// and a boolean to check if the value has been set.
func (o *Import) GetUpdatedAtOk() (*time.Time, bool) {
	if o == nil {
		return nil, false
	}
	return &o.UpdatedAt, true
}

// SetUpdatedAt sets field value
func (o *Import) SetUpdatedAt(v time.Time) {
	o.UpdatedAt = v
}

// GetStartedAt returns the StartedAt field value if set, zero value otherwise (both if not set or set to explicit null).
func (o *Import) GetStartedAt() time.Time {
	if o == nil || IsNil(o.StartedAt.Get()) {
		var ret time.Time
		return ret
	}
	return *o.StartedAt.Get()
}

// GetStartedAtOk returns a tuple with the StartedAt field value if set, nil otherwise
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *Import) GetStartedAtOk() (*time.Time, bool) {
	if o == nil {
		return nil, false
	}
	return o.StartedAt.Get(), o.StartedAt.IsSet()
}

// HasStartedAt returns a boolean if a field has been set.
func (o *Import) HasStartedAt() bool {
	if o != nil && o.StartedAt.IsSet() {
		return true
	}

	return false
}

// SetStartedAt gets a reference to the given NullableTime and assigns it to the StartedAt field.
func (o *Import) SetStartedAt(v time.Time) {
	o.StartedAt.Set(&v)
}
// SetStartedAtNil sets the value for StartedAt to be an explicit nil
func (o *Import) SetStartedAtNil() {
	o.StartedAt.Set(nil)
}

// UnsetStartedAt ensures that no value is present for StartedAt, not even an explicit nil
func (o *Import) UnsetStartedAt() {
	o.StartedAt.Unset()
}

// GetEndedAt returns the EndedAt field value if set, zero value otherwise (both if not set or set to explicit null).
func (o *Import) GetEndedAt() time.Time {
	if o == nil || IsNil(o.EndedAt.Get()) {
		var ret time.Time
		return ret
	}
	return *o.EndedAt.Get()
}

// GetEndedAtOk returns a tuple with the EndedAt field value if set, nil otherwise
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *Import) GetEndedAtOk() (*time.Time, bool) {
	if o == nil {
		return nil, false
	}
	return o.EndedAt.Get(), o.EndedAt.IsSet()
}

// HasEndedAt returns a boolean if a field has been set.
func (o *Import) HasEndedAt() bool {
	if o != nil && o.EndedAt.IsSet() {
		return true
	}

	return false
}

// SetEndedAt gets a reference to the given NullableTime and assigns it to the EndedAt field.
func (o *Import) SetEndedAt(v time.Time) {
	o.EndedAt.Set(&v)
}
// SetEndedAtNil sets the value for EndedAt to be an explicit nil
func (o *Import) SetEndedAtNil() {
	o.EndedAt.Set(nil)
}

// UnsetEndedAt ensures that no value is present for EndedAt, not even an explicit nil
func (o *Import) UnsetEndedAt() {
	o.EndedAt.Unset()
}

func (o Import) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o Import) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["id"] = o.Id
	toSerialize["name"] = o.Name
	toSerialize["source"] = o.Source
	toSerialize["status"] = o.Status
	if o.Filename.IsSet() {
		toSerialize["filename"] = o.Filename.Get()
	}
	if o.Size.IsSet() {
		toSerialize["size"] = o.Size.Get()
	}
	if o.AppInstanceId.IsSet() {
		toSerialize["appInstanceId"] = o.AppInstanceId.Get()
	}
	if o.AppServiceId.IsSet() {
		toSerialize["appServiceId"] = o.AppServiceId.Get()
	}
	if o.DatabaseId.IsSet() {
		toSerialize["databaseId"] = o.DatabaseId.Get()
	}
	if o.DatabaseDbId.IsSet() {
		toSerialize["databaseDbId"] = o.DatabaseDbId.Get()
	}
	if o.AppServiceDeploymentId.IsSet() {
		toSerialize["appServiceDeploymentId"] = o.AppServiceDeploymentId.Get()
	}
	if o.TaskId.IsSet() {
		toSerialize["taskId"] = o.TaskId.Get()
	}
	if o.BackupId.IsSet() {
		toSerialize["backupId"] = o.BackupId.Get()
	}
	toSerialize["createdAt"] = o.CreatedAt
	toSerialize["updatedAt"] = o.UpdatedAt
	if o.StartedAt.IsSet() {
		toSerialize["startedAt"] = o.StartedAt.Get()
	}
	if o.EndedAt.IsSet() {
		toSerialize["endedAt"] = o.EndedAt.Get()
	}
	return toSerialize, nil
}

func (o *Import) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"id",
		"name",
		"source",
		"status",
		"createdAt",
		"updatedAt",
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err;
	}

	for _, requiredProperty := range(requiredProperties) {
		if _, exists := allProperties[requiredProperty]; !exists {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varImport := _Import{}

	decoder := json.NewDecoder(bytes.NewReader(data))
	decoder.DisallowUnknownFields()
	err = decoder.Decode(&varImport)

	if err != nil {
		return err
	}

	*o = Import(varImport)

	return err
}

type NullableImport struct {
	value *Import
	isSet bool
}

func (v NullableImport) Get() *Import {
	return v.value
}

func (v *NullableImport) Set(val *Import) {
	v.value = val
	v.isSet = true
}

func (v NullableImport) IsSet() bool {
	return v.isSet
}

func (v *NullableImport) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableImport(val *Import) *NullableImport {
	return &NullableImport{value: val, isSet: true}
}

func (v NullableImport) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableImport) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


