/*
Wodby 2 Public API

Public REST API for customer SDKs and code integrations. GraphQL remains internal for the dashboard. This contract is the versioned public surface. 

API version: 1.0.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package client

import (
	"encoding/json"
	"bytes"
	"fmt"
)

// checks if the IntegrationEnvironmentPolicyInput type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &IntegrationEnvironmentPolicyInput{}

// IntegrationEnvironmentPolicyInput Use primaryEnvType and allowedEnvTypes. Legacy ID fields remain accepted but cannot be mixed with their type equivalents.
type IntegrationEnvironmentPolicyInput struct {
	// Deprecated
	PrimaryEnvId NullableInt32 `json:"primaryEnvId,omitempty"`
	PrimaryEnvType NullableString `json:"primaryEnvType,omitempty"`
	Scope string `json:"scope"`
	// Deprecated
	AllowedEnvIds []int32 `json:"allowedEnvIds,omitempty"`
	AllowedEnvTypes []string `json:"allowedEnvTypes,omitempty"`
}

type _IntegrationEnvironmentPolicyInput IntegrationEnvironmentPolicyInput

// NewIntegrationEnvironmentPolicyInput instantiates a new IntegrationEnvironmentPolicyInput object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewIntegrationEnvironmentPolicyInput(scope string) *IntegrationEnvironmentPolicyInput {
	this := IntegrationEnvironmentPolicyInput{}
	this.Scope = scope
	return &this
}

// NewIntegrationEnvironmentPolicyInputWithDefaults instantiates a new IntegrationEnvironmentPolicyInput object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewIntegrationEnvironmentPolicyInputWithDefaults() *IntegrationEnvironmentPolicyInput {
	this := IntegrationEnvironmentPolicyInput{}
	return &this
}

// GetPrimaryEnvId returns the PrimaryEnvId field value if set, zero value otherwise (both if not set or set to explicit null).
// Deprecated
func (o *IntegrationEnvironmentPolicyInput) GetPrimaryEnvId() int32 {
	if o == nil || IsNil(o.PrimaryEnvId.Get()) {
		var ret int32
		return ret
	}
	return *o.PrimaryEnvId.Get()
}

// GetPrimaryEnvIdOk returns a tuple with the PrimaryEnvId field value if set, nil otherwise
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
// Deprecated
func (o *IntegrationEnvironmentPolicyInput) GetPrimaryEnvIdOk() (*int32, bool) {
	if o == nil {
		return nil, false
	}
	return o.PrimaryEnvId.Get(), o.PrimaryEnvId.IsSet()
}

// HasPrimaryEnvId returns a boolean if a field has been set.
func (o *IntegrationEnvironmentPolicyInput) HasPrimaryEnvId() bool {
	if o != nil && o.PrimaryEnvId.IsSet() {
		return true
	}

	return false
}

// SetPrimaryEnvId gets a reference to the given NullableInt32 and assigns it to the PrimaryEnvId field.
// Deprecated
func (o *IntegrationEnvironmentPolicyInput) SetPrimaryEnvId(v int32) {
	o.PrimaryEnvId.Set(&v)
}
// SetPrimaryEnvIdNil sets the value for PrimaryEnvId to be an explicit nil
func (o *IntegrationEnvironmentPolicyInput) SetPrimaryEnvIdNil() {
	o.PrimaryEnvId.Set(nil)
}

// UnsetPrimaryEnvId ensures that no value is present for PrimaryEnvId, not even an explicit nil
func (o *IntegrationEnvironmentPolicyInput) UnsetPrimaryEnvId() {
	o.PrimaryEnvId.Unset()
}

// GetPrimaryEnvType returns the PrimaryEnvType field value if set, zero value otherwise (both if not set or set to explicit null).
func (o *IntegrationEnvironmentPolicyInput) GetPrimaryEnvType() string {
	if o == nil || IsNil(o.PrimaryEnvType.Get()) {
		var ret string
		return ret
	}
	return *o.PrimaryEnvType.Get()
}

// GetPrimaryEnvTypeOk returns a tuple with the PrimaryEnvType field value if set, nil otherwise
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *IntegrationEnvironmentPolicyInput) GetPrimaryEnvTypeOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return o.PrimaryEnvType.Get(), o.PrimaryEnvType.IsSet()
}

// HasPrimaryEnvType returns a boolean if a field has been set.
func (o *IntegrationEnvironmentPolicyInput) HasPrimaryEnvType() bool {
	if o != nil && o.PrimaryEnvType.IsSet() {
		return true
	}

	return false
}

// SetPrimaryEnvType gets a reference to the given NullableString and assigns it to the PrimaryEnvType field.
func (o *IntegrationEnvironmentPolicyInput) SetPrimaryEnvType(v string) {
	o.PrimaryEnvType.Set(&v)
}
// SetPrimaryEnvTypeNil sets the value for PrimaryEnvType to be an explicit nil
func (o *IntegrationEnvironmentPolicyInput) SetPrimaryEnvTypeNil() {
	o.PrimaryEnvType.Set(nil)
}

// UnsetPrimaryEnvType ensures that no value is present for PrimaryEnvType, not even an explicit nil
func (o *IntegrationEnvironmentPolicyInput) UnsetPrimaryEnvType() {
	o.PrimaryEnvType.Unset()
}

// GetScope returns the Scope field value
func (o *IntegrationEnvironmentPolicyInput) GetScope() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Scope
}

// GetScopeOk returns a tuple with the Scope field value
// and a boolean to check if the value has been set.
func (o *IntegrationEnvironmentPolicyInput) GetScopeOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Scope, true
}

// SetScope sets field value
func (o *IntegrationEnvironmentPolicyInput) SetScope(v string) {
	o.Scope = v
}

// GetAllowedEnvIds returns the AllowedEnvIds field value if set, zero value otherwise.
// Deprecated
func (o *IntegrationEnvironmentPolicyInput) GetAllowedEnvIds() []int32 {
	if o == nil || IsNil(o.AllowedEnvIds) {
		var ret []int32
		return ret
	}
	return o.AllowedEnvIds
}

// GetAllowedEnvIdsOk returns a tuple with the AllowedEnvIds field value if set, nil otherwise
// and a boolean to check if the value has been set.
// Deprecated
func (o *IntegrationEnvironmentPolicyInput) GetAllowedEnvIdsOk() ([]int32, bool) {
	if o == nil || IsNil(o.AllowedEnvIds) {
		return nil, false
	}
	return o.AllowedEnvIds, true
}

// HasAllowedEnvIds returns a boolean if a field has been set.
func (o *IntegrationEnvironmentPolicyInput) HasAllowedEnvIds() bool {
	if o != nil && !IsNil(o.AllowedEnvIds) {
		return true
	}

	return false
}

// SetAllowedEnvIds gets a reference to the given []int32 and assigns it to the AllowedEnvIds field.
// Deprecated
func (o *IntegrationEnvironmentPolicyInput) SetAllowedEnvIds(v []int32) {
	o.AllowedEnvIds = v
}

// GetAllowedEnvTypes returns the AllowedEnvTypes field value if set, zero value otherwise.
func (o *IntegrationEnvironmentPolicyInput) GetAllowedEnvTypes() []string {
	if o == nil || IsNil(o.AllowedEnvTypes) {
		var ret []string
		return ret
	}
	return o.AllowedEnvTypes
}

// GetAllowedEnvTypesOk returns a tuple with the AllowedEnvTypes field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *IntegrationEnvironmentPolicyInput) GetAllowedEnvTypesOk() ([]string, bool) {
	if o == nil || IsNil(o.AllowedEnvTypes) {
		return nil, false
	}
	return o.AllowedEnvTypes, true
}

// HasAllowedEnvTypes returns a boolean if a field has been set.
func (o *IntegrationEnvironmentPolicyInput) HasAllowedEnvTypes() bool {
	if o != nil && !IsNil(o.AllowedEnvTypes) {
		return true
	}

	return false
}

// SetAllowedEnvTypes gets a reference to the given []string and assigns it to the AllowedEnvTypes field.
func (o *IntegrationEnvironmentPolicyInput) SetAllowedEnvTypes(v []string) {
	o.AllowedEnvTypes = v
}

func (o IntegrationEnvironmentPolicyInput) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o IntegrationEnvironmentPolicyInput) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if o.PrimaryEnvId.IsSet() {
		toSerialize["primaryEnvId"] = o.PrimaryEnvId.Get()
	}
	if o.PrimaryEnvType.IsSet() {
		toSerialize["primaryEnvType"] = o.PrimaryEnvType.Get()
	}
	toSerialize["scope"] = o.Scope
	if !IsNil(o.AllowedEnvIds) {
		toSerialize["allowedEnvIds"] = o.AllowedEnvIds
	}
	if !IsNil(o.AllowedEnvTypes) {
		toSerialize["allowedEnvTypes"] = o.AllowedEnvTypes
	}
	return toSerialize, nil
}

func (o *IntegrationEnvironmentPolicyInput) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"scope",
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err;
	}

	for _, requiredProperty := range(requiredProperties) {
		if _, exists := allProperties[requiredProperty]; !exists {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varIntegrationEnvironmentPolicyInput := _IntegrationEnvironmentPolicyInput{}

	decoder := json.NewDecoder(bytes.NewReader(data))
	decoder.DisallowUnknownFields()
	err = decoder.Decode(&varIntegrationEnvironmentPolicyInput)

	if err != nil {
		return err
	}

	*o = IntegrationEnvironmentPolicyInput(varIntegrationEnvironmentPolicyInput)

	return err
}

type NullableIntegrationEnvironmentPolicyInput struct {
	value *IntegrationEnvironmentPolicyInput
	isSet bool
}

func (v NullableIntegrationEnvironmentPolicyInput) Get() *IntegrationEnvironmentPolicyInput {
	return v.value
}

func (v *NullableIntegrationEnvironmentPolicyInput) Set(val *IntegrationEnvironmentPolicyInput) {
	v.value = val
	v.isSet = true
}

func (v NullableIntegrationEnvironmentPolicyInput) IsSet() bool {
	return v.isSet
}

func (v *NullableIntegrationEnvironmentPolicyInput) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableIntegrationEnvironmentPolicyInput(val *IntegrationEnvironmentPolicyInput) *NullableIntegrationEnvironmentPolicyInput {
	return &NullableIntegrationEnvironmentPolicyInput{value: val, isSet: true}
}

func (v NullableIntegrationEnvironmentPolicyInput) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableIntegrationEnvironmentPolicyInput) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


