/*
Wodby 2.0 Public API

Public REST API for customer SDKs and code integrations. GraphQL remains internal for the dashboard. This contract is the versioned public surface. 

API version: 1.0.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package client

import (
	"encoding/json"
	"bytes"
	"fmt"
)

// checks if the NewImportInput type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &NewImportInput{}

// NewImportInput struct for NewImportInput
type NewImportInput struct {
	AppServiceID NullableInt32 `json:"appServiceID,omitempty"`
	DatabaseDBID NullableInt32 `json:"databaseDBID,omitempty"`
	Import ImportInput `json:"import"`
}

type _NewImportInput NewImportInput

// NewNewImportInput instantiates a new NewImportInput object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewNewImportInput(import_ ImportInput) *NewImportInput {
	this := NewImportInput{}
	this.Import = import_
	return &this
}

// NewNewImportInputWithDefaults instantiates a new NewImportInput object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewNewImportInputWithDefaults() *NewImportInput {
	this := NewImportInput{}
	return &this
}

// GetAppServiceID returns the AppServiceID field value if set, zero value otherwise (both if not set or set to explicit null).
func (o *NewImportInput) GetAppServiceID() int32 {
	if o == nil || IsNil(o.AppServiceID.Get()) {
		var ret int32
		return ret
	}
	return *o.AppServiceID.Get()
}

// GetAppServiceIDOk returns a tuple with the AppServiceID field value if set, nil otherwise
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *NewImportInput) GetAppServiceIDOk() (*int32, bool) {
	if o == nil {
		return nil, false
	}
	return o.AppServiceID.Get(), o.AppServiceID.IsSet()
}

// HasAppServiceID returns a boolean if a field has been set.
func (o *NewImportInput) HasAppServiceID() bool {
	if o != nil && o.AppServiceID.IsSet() {
		return true
	}

	return false
}

// SetAppServiceID gets a reference to the given NullableInt32 and assigns it to the AppServiceID field.
func (o *NewImportInput) SetAppServiceID(v int32) {
	o.AppServiceID.Set(&v)
}
// SetAppServiceIDNil sets the value for AppServiceID to be an explicit nil
func (o *NewImportInput) SetAppServiceIDNil() {
	o.AppServiceID.Set(nil)
}

// UnsetAppServiceID ensures that no value is present for AppServiceID, not even an explicit nil
func (o *NewImportInput) UnsetAppServiceID() {
	o.AppServiceID.Unset()
}

// GetDatabaseDBID returns the DatabaseDBID field value if set, zero value otherwise (both if not set or set to explicit null).
func (o *NewImportInput) GetDatabaseDBID() int32 {
	if o == nil || IsNil(o.DatabaseDBID.Get()) {
		var ret int32
		return ret
	}
	return *o.DatabaseDBID.Get()
}

// GetDatabaseDBIDOk returns a tuple with the DatabaseDBID field value if set, nil otherwise
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *NewImportInput) GetDatabaseDBIDOk() (*int32, bool) {
	if o == nil {
		return nil, false
	}
	return o.DatabaseDBID.Get(), o.DatabaseDBID.IsSet()
}

// HasDatabaseDBID returns a boolean if a field has been set.
func (o *NewImportInput) HasDatabaseDBID() bool {
	if o != nil && o.DatabaseDBID.IsSet() {
		return true
	}

	return false
}

// SetDatabaseDBID gets a reference to the given NullableInt32 and assigns it to the DatabaseDBID field.
func (o *NewImportInput) SetDatabaseDBID(v int32) {
	o.DatabaseDBID.Set(&v)
}
// SetDatabaseDBIDNil sets the value for DatabaseDBID to be an explicit nil
func (o *NewImportInput) SetDatabaseDBIDNil() {
	o.DatabaseDBID.Set(nil)
}

// UnsetDatabaseDBID ensures that no value is present for DatabaseDBID, not even an explicit nil
func (o *NewImportInput) UnsetDatabaseDBID() {
	o.DatabaseDBID.Unset()
}

// GetImport returns the Import field value
func (o *NewImportInput) GetImport() ImportInput {
	if o == nil {
		var ret ImportInput
		return ret
	}

	return o.Import
}

// GetImportOk returns a tuple with the Import field value
// and a boolean to check if the value has been set.
func (o *NewImportInput) GetImportOk() (*ImportInput, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Import, true
}

// SetImport sets field value
func (o *NewImportInput) SetImport(v ImportInput) {
	o.Import = v
}

func (o NewImportInput) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o NewImportInput) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if o.AppServiceID.IsSet() {
		toSerialize["appServiceID"] = o.AppServiceID.Get()
	}
	if o.DatabaseDBID.IsSet() {
		toSerialize["databaseDBID"] = o.DatabaseDBID.Get()
	}
	toSerialize["import"] = o.Import
	return toSerialize, nil
}

func (o *NewImportInput) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"import",
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err;
	}

	for _, requiredProperty := range(requiredProperties) {
		if _, exists := allProperties[requiredProperty]; !exists {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varNewImportInput := _NewImportInput{}

	decoder := json.NewDecoder(bytes.NewReader(data))
	decoder.DisallowUnknownFields()
	err = decoder.Decode(&varNewImportInput)

	if err != nil {
		return err
	}

	*o = NewImportInput(varNewImportInput)

	return err
}

type NullableNewImportInput struct {
	value *NewImportInput
	isSet bool
}

func (v NullableNewImportInput) Get() *NewImportInput {
	return v.value
}

func (v *NullableNewImportInput) Set(val *NewImportInput) {
	v.value = val
	v.isSet = true
}

func (v NullableNewImportInput) IsSet() bool {
	return v.isSet
}

func (v *NullableNewImportInput) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableNewImportInput(val *NewImportInput) *NullableNewImportInput {
	return &NullableNewImportInput{value: val, isSet: true}
}

func (v NullableNewImportInput) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableNewImportInput) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


