/*
Wodby 2 Public API

Public REST API for customer SDKs and code integrations. GraphQL remains internal for the dashboard. This contract is the versioned public surface. 

API version: 1.0.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package client

import (
	"encoding/json"
	"bytes"
	"fmt"
)

// checks if the NewStackServiceScopedValueInput type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &NewStackServiceScopedValueInput{}

// NewStackServiceScopedValueInput struct for NewStackServiceScopedValueInput
type NewStackServiceScopedValueInput struct {
	Name string `json:"name"`
	Value string `json:"value"`
	Secret bool `json:"secret"`
	EnvType NullableString `json:"envType,omitempty"`
}

type _NewStackServiceScopedValueInput NewStackServiceScopedValueInput

// NewNewStackServiceScopedValueInput instantiates a new NewStackServiceScopedValueInput object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewNewStackServiceScopedValueInput(name string, value string, secret bool) *NewStackServiceScopedValueInput {
	this := NewStackServiceScopedValueInput{}
	this.Name = name
	this.Value = value
	this.Secret = secret
	return &this
}

// NewNewStackServiceScopedValueInputWithDefaults instantiates a new NewStackServiceScopedValueInput object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewNewStackServiceScopedValueInputWithDefaults() *NewStackServiceScopedValueInput {
	this := NewStackServiceScopedValueInput{}
	return &this
}

// GetName returns the Name field value
func (o *NewStackServiceScopedValueInput) GetName() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Name
}

// GetNameOk returns a tuple with the Name field value
// and a boolean to check if the value has been set.
func (o *NewStackServiceScopedValueInput) GetNameOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Name, true
}

// SetName sets field value
func (o *NewStackServiceScopedValueInput) SetName(v string) {
	o.Name = v
}

// GetValue returns the Value field value
func (o *NewStackServiceScopedValueInput) GetValue() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Value
}

// GetValueOk returns a tuple with the Value field value
// and a boolean to check if the value has been set.
func (o *NewStackServiceScopedValueInput) GetValueOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Value, true
}

// SetValue sets field value
func (o *NewStackServiceScopedValueInput) SetValue(v string) {
	o.Value = v
}

// GetSecret returns the Secret field value
func (o *NewStackServiceScopedValueInput) GetSecret() bool {
	if o == nil {
		var ret bool
		return ret
	}

	return o.Secret
}

// GetSecretOk returns a tuple with the Secret field value
// and a boolean to check if the value has been set.
func (o *NewStackServiceScopedValueInput) GetSecretOk() (*bool, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Secret, true
}

// SetSecret sets field value
func (o *NewStackServiceScopedValueInput) SetSecret(v bool) {
	o.Secret = v
}

// GetEnvType returns the EnvType field value if set, zero value otherwise (both if not set or set to explicit null).
func (o *NewStackServiceScopedValueInput) GetEnvType() string {
	if o == nil || IsNil(o.EnvType.Get()) {
		var ret string
		return ret
	}
	return *o.EnvType.Get()
}

// GetEnvTypeOk returns a tuple with the EnvType field value if set, nil otherwise
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *NewStackServiceScopedValueInput) GetEnvTypeOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return o.EnvType.Get(), o.EnvType.IsSet()
}

// HasEnvType returns a boolean if a field has been set.
func (o *NewStackServiceScopedValueInput) HasEnvType() bool {
	if o != nil && o.EnvType.IsSet() {
		return true
	}

	return false
}

// SetEnvType gets a reference to the given NullableString and assigns it to the EnvType field.
func (o *NewStackServiceScopedValueInput) SetEnvType(v string) {
	o.EnvType.Set(&v)
}
// SetEnvTypeNil sets the value for EnvType to be an explicit nil
func (o *NewStackServiceScopedValueInput) SetEnvTypeNil() {
	o.EnvType.Set(nil)
}

// UnsetEnvType ensures that no value is present for EnvType, not even an explicit nil
func (o *NewStackServiceScopedValueInput) UnsetEnvType() {
	o.EnvType.Unset()
}

func (o NewStackServiceScopedValueInput) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o NewStackServiceScopedValueInput) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["name"] = o.Name
	toSerialize["value"] = o.Value
	toSerialize["secret"] = o.Secret
	if o.EnvType.IsSet() {
		toSerialize["envType"] = o.EnvType.Get()
	}
	return toSerialize, nil
}

func (o *NewStackServiceScopedValueInput) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"name",
		"value",
		"secret",
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err;
	}

	for _, requiredProperty := range(requiredProperties) {
		if _, exists := allProperties[requiredProperty]; !exists {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varNewStackServiceScopedValueInput := _NewStackServiceScopedValueInput{}

	decoder := json.NewDecoder(bytes.NewReader(data))
	decoder.DisallowUnknownFields()
	err = decoder.Decode(&varNewStackServiceScopedValueInput)

	if err != nil {
		return err
	}

	*o = NewStackServiceScopedValueInput(varNewStackServiceScopedValueInput)

	return err
}

type NullableNewStackServiceScopedValueInput struct {
	value *NewStackServiceScopedValueInput
	isSet bool
}

func (v NullableNewStackServiceScopedValueInput) Get() *NewStackServiceScopedValueInput {
	return v.value
}

func (v *NullableNewStackServiceScopedValueInput) Set(val *NewStackServiceScopedValueInput) {
	v.value = val
	v.isSet = true
}

func (v NullableNewStackServiceScopedValueInput) IsSet() bool {
	return v.isSet
}

func (v *NullableNewStackServiceScopedValueInput) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableNewStackServiceScopedValueInput(val *NewStackServiceScopedValueInput) *NullableNewStackServiceScopedValueInput {
	return &NullableNewStackServiceScopedValueInput{value: val, isSet: true}
}

func (v NullableNewStackServiceScopedValueInput) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableNewStackServiceScopedValueInput) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


