/*
 * Wodby API (beta)
 *
 * Documentation https://docs.wodby.com/dev GitHub https://github.com/wodby/wodby-api 
 *
 * API version: 3.0.x
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */

package wodby-api

type RequestInstanceCreate struct {

	AppId *Uuid `json:"app_id"`

	ServerId *Uuid `json:"server_id"`

	Type_ *InstanceType `json:"type"`

	Name string `json:"name"`

	Title string `json:"title,omitempty"`

	PostDeployment bool `json:"post_deployment,omitempty"`

	Git *RequestInstanceCreateGit `json:"git,omitempty"`
}
